import React from "react";
import {
  LayoutDashboard,
  Workflow,
  Network,
  Sparkles,
  CheckCircle2,
  Settings,
  FileText,
  Scissors,
  Search,
  ImageIcon,
  Camera,
  Box,
  GitBranch,
  Scan,
  Target,
  Sliders,
  Globe,
  Play,
  Video,
  Monitor,
  Store,
  TestTube2,
  Database,
  BarChart3,
  AlertCircle,
  BookOpen,
  ScanSearch,
} from "lucide-react";
import type { NavItem } from "./types";

// =============================================================================
// Dev-only and admin-only navigation items.
//
// Production items come from qontinui-navigation shared package
// via shared-nav-adapter.ts. Only dev-only and admin items remain here.
// =============================================================================

export const devNavItems: NavItem[] = [
  // ===========================================================================
  // Dev Dashboard (dev-only, top-level for easy access)
  // ===========================================================================
  {
    id: "dev-dashboard",
    label: "Dev Dashboard",
    description: "Fleet monitoring across all runners and machines",
    icon: React.createElement(LayoutDashboard, { className: "size-5" }),
    route: "/dev-dashboard",
    color: "#10B981",
    hiddenInProd: true,
    productMode: "ai",
    group: "Dev",
  },

  // ===========================================================================
  // Hidden items (dev-only, AI mode)
  // ===========================================================================
  {
    id: "inspector",
    label: "Inspector",
    description: "UI Bridge element inspection (dev debugging tool)",
    icon: React.createElement(ScanSearch, { className: "size-5" }),
    route: "/tools/inspector",
    color: "var(--brand-secondary)",
    hiddenInProd: true,
    productMode: "ai",
  },
  {
    id: "review",
    label: "Review",
    description: "UI Bridge full project review",
    icon: React.createElement(ScanSearch, { className: "size-5" }),
    route: "/build/review-workflow",
    color: "var(--brand-secondary)",
    hiddenInProd: true,
    productMode: "ai",
  },
  {
    id: "state-machine-dev",
    label: "State Machine",
    description: "UI Bridge state machine builder",
    icon: React.createElement(Network, { className: "size-5" }),
    route: "/automation-builder/ui-bridge-states",
    color: "var(--brand-secondary)",
    hiddenInProd: true,
    productMode: "ai",
  },
  {
    id: "build-flow-designer",
    label: "Flow Designer",
    description: "AI-assisted workflow structure designer",
    icon: React.createElement(GitBranch, { className: "size-5" }),
    route: "/build/flow-designer",
    color: "var(--brand-secondary)",
    hiddenInProd: true,
    productMode: "ai",
  },

  // ===========================================================================
  // Visual Automation (visible in "visual" product mode)
  // Flattened as top-level items with group labels for the visual mode sidebar.
  // ===========================================================================
  {
    id: "visual-automation-execute",
    label: "Execute",
    description: "GUI automation control surface",
    icon: React.createElement(Play, { className: "size-5" }),
    route: "/tools/visual-automation",
    color: "#10B981",
    productMode: "visual",
    group: "Run",
  },
  {
    id: "visual-automation-monitor",
    label: "Monitor",
    description: "Real-time automation monitoring",
    icon: React.createElement(Monitor, { className: "size-5" }),
    route: "/monitor",
    color: "#10B981",
    productMode: "visual",
  },
  {
    id: "visual-automation-capture",
    label: "Capture",
    description: "Screen capture and recording",
    icon: React.createElement(Video, { className: "size-5" }),
    route: "/tools/capture",
    color: "#10B981",
    productMode: "visual",
  },
  {
    id: "va-build",
    label: "GUI Build",
    icon: React.createElement(Network, { className: "size-5" }),
    route: "/automation-builder/states",
    color: "var(--brand-secondary)",
    productMode: "visual",
    group: "Build",
    children: [
      {
        id: "va-state-machine",
        label: "State Machine",
        description: "Define states and transitions",
        icon: React.createElement(Network, { className: "size-4" }),
        route: "/automation-builder/states",
        color: "var(--brand-secondary)",
        productMode: "visual",
      },
      {
        id: "va-workflows",
        label: "Workflows",
        description: "Create automation action sequences",
        icon: React.createElement(Workflow, { className: "size-4" }),
        route: "/automation-builder",
        color: "var(--brand-secondary)",
        productMode: "visual",
      },
      {
        id: "va-variables",
        label: "Variables",
        description: "Global configuration values",
        icon: React.createElement(Sliders, { className: "size-4" }),
        route: "/automation-builder/variables",
        color: "var(--brand-secondary)",
        productMode: "visual",
      },
      {
        id: "va-contexts",
        label: "AI Contexts",
        description: "Domain knowledge for AI tasks",
        icon: React.createElement(BookOpen, { className: "size-4" }),
        route: "/automation-builder/contexts",
        color: "var(--brand-secondary)",
        productMode: "visual",
      },
      {
        id: "va-marketplace",
        label: "Marketplace",
        description: "Community automation packages",
        icon: React.createElement(Store, { className: "size-4" }),
        route: "/marketplace",
        color: "var(--brand-secondary)",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-assets",
    label: "Assets",
    icon: React.createElement(ImageIcon, { className: "size-5" }),
    route: "/automation-builder/images",
    color: "#8B5CF6",
    productMode: "visual",
    children: [
      {
        id: "va-images",
        label: "Images",
        description: "Pattern image library",
        icon: React.createElement(ImageIcon, { className: "size-4" }),
        route: "/automation-builder/images",
        color: "#8B5CF6",
        productMode: "visual",
      },
      {
        id: "va-screenshots",
        label: "Screenshots",
        description: "Uploaded screenshots for pattern creation",
        icon: React.createElement(Camera, { className: "size-4" }),
        route: "/automation-builder/screenshots",
        color: "#8B5CF6",
        productMode: "visual",
      },
      {
        id: "va-recordings",
        label: "Recordings",
        description: "Video recordings for state discovery",
        icon: React.createElement(Video, { className: "size-4" }),
        route: "/recordings",
        color: "#8B5CF6",
        productMode: "visual",
      },
      {
        id: "va-visual-index",
        label: "Visual Index",
        description: "Indexed elements for visual search",
        icon: React.createElement(Database, { className: "size-4" }),
        route: "/projects/:projectId/rag",
        color: "#8B5CF6",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-create",
    label: "Create",
    icon: React.createElement(Sparkles, { className: "size-5" }),
    route: "/automation-builder/image-extraction",
    color: "var(--brand-success)",
    productMode: "visual",
    children: [
      {
        id: "va-extract-images",
        label: "Extract Images",
        description: "Cut pattern images from screenshots",
        icon: React.createElement(Scissors, { className: "size-4" }),
        route: "/automation-builder/image-extraction",
        color: "var(--brand-success)",
        productMode: "visual",
      },
      {
        id: "va-pattern-extraction",
        label: "Pattern Extraction",
        description: "Extract robust patterns from screenshots",
        icon: React.createElement(Sparkles, { className: "size-4" }),
        route: "/automation-builder/pattern-optimization",
        color: "var(--brand-success)",
        productMode: "visual",
      },
      {
        id: "va-annotations",
        label: "Annotations",
        description: "Create regions and locations for states",
        icon: React.createElement(Scan, { className: "size-4" }),
        route: "/automation-builder/annotations",
        color: "var(--brand-success)",
        productMode: "visual",
      },
      {
        id: "va-template-capture",
        label: "Template Capture",
        description: "Click-to-template element detection",
        icon: React.createElement(Target, { className: "size-4" }),
        route: "/automation-builder/template-capture",
        color: "var(--brand-success)",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-discover",
    label: "Discover",
    icon: React.createElement(Search, { className: "size-5" }),
    route: "/automation-builder/snapshot-tests",
    color: "#4ECDC4",
    productMode: "visual",
    children: [
      {
        id: "va-snapshot-tests",
        label: "Snapshot Tests",
        description: "Generate tests from page snapshot",
        icon: React.createElement(Camera, { className: "size-4" }),
        route: "/automation-builder/snapshot-tests",
        color: "#10b981",
        productMode: "visual",
      },
      {
        id: "va-navigation-tests",
        label: "Navigation Tests",
        description: "Generate tests from exploration",
        icon: React.createElement(GitBranch, { className: "size-4" }),
        route: "/automation-builder/navigation-tests",
        color: "#10b981",
        productMode: "visual",
      },
      {
        id: "va-discover-states",
        label: "Discover States",
        description: "Automatically discover UI states",
        icon: React.createElement(Search, { className: "size-4" }),
        route: "/automation-builder/state-discovery",
        color: "#4ECDC4",
        productMode: "visual",
      },
      {
        id: "va-extraction",
        label: "Discover",
        description: "Discover states from web, desktop, or render logs",
        icon: React.createElement(Globe, { className: "size-4" }),
        route: "/automation-builder/extraction",
        color: "#4ECDC4",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-config-testing",
    label: "Config Testing",
    icon: React.createElement(CheckCircle2, { className: "size-5" }),
    route: "/automation-builder/pattern-tests",
    color: "#FF6B6B",
    productMode: "visual",
    group: "Test",
    children: [
      {
        id: "va-pattern-tests",
        label: "Pattern Tests",
        description: "Test pattern recognition accuracy",
        icon: React.createElement(Target, { className: "size-4" }),
        route: "/automation-builder/pattern-tests",
        color: "#FF6B6B",
        productMode: "visual",
      },
      {
        id: "va-integration-tests",
        label: "Integration Tests",
        description: "End-to-end workflow testing",
        icon: React.createElement(TestTube2, { className: "size-4" }),
        route: "/integration-testing",
        color: "#FF6B6B",
        productMode: "visual",
      },
      {
        id: "va-semantic-analysis",
        label: "Semantic Analysis",
        description: "Analyze UI element semantics",
        icon: React.createElement(Scan, { className: "size-4" }),
        route: "/automation-builder/semantic-analysis",
        color: "#FF6B6B",
        productMode: "visual",
      },
      {
        id: "va-rag-testing",
        label: "RAG Testing",
        description: "Test RAG element matching with SAM3/CLIP",
        icon: React.createElement(Target, { className: "size-4" }),
        route: "/automation-builder/rag-testing",
        color: "#FF6B6B",
        productMode: "visual",
      },
      {
        id: "va-workflow-runner",
        label: "Workflow Runner",
        description: "Execute and debug workflows",
        icon: React.createElement(Play, { className: "size-4" }),
        route: "/workflow-viz",
        color: "#FF6B6B",
        productMode: "visual",
      },
      {
        id: "va-captures",
        label: "Captures",
        description: "Execution recordings with input events",
        icon: React.createElement(Camera, { className: "size-4" }),
        route: "/captures",
        color: "#FF6B6B",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-qa-testing",
    label: "QA Testing",
    icon: React.createElement(TestTube2, { className: "size-5" }),
    route: "/qa-dashboard",
    color: "#F59E0B",
    productMode: "visual",
    children: [
      {
        id: "va-qa-dashboard",
        label: "Dashboard",
        description: "QA testing overview and metrics",
        icon: React.createElement(LayoutDashboard, {
          className: "size-4",
        }),
        route: "/qa-dashboard",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-test-runs",
        label: "Test Runs",
        description: "View test execution history",
        icon: React.createElement(Play, { className: "size-4" }),
        route: "/testing",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-qa-runs",
        label: "QA Runs",
        description: "QA test run history",
        icon: React.createElement(TestTube2, { className: "size-4" }),
        route: "/qa-dashboard/runs",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-coverage",
        label: "Coverage",
        description: "Test coverage analysis",
        icon: React.createElement(BarChart3, { className: "size-4" }),
        route: "/qa-dashboard/coverage",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-deficiencies",
        label: "Deficiencies",
        description: "Track testing deficiencies",
        icon: React.createElement(Target, { className: "size-4" }),
        route: "/qa-dashboard/deficiencies",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-compare",
        label: "Compare",
        description: "Compare test results",
        icon: React.createElement(GitBranch, { className: "size-4" }),
        route: "/qa-dashboard/compare",
        color: "#F59E0B",
        productMode: "visual",
      },
      {
        id: "va-execution-history",
        label: "Execution History",
        description: "View detailed execution tree events",
        icon: React.createElement(Play, { className: "size-4" }),
        route: "/execution-history",
        color: "#F59E0B",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-ai-tasks",
    label: "AI Tasks",
    icon: React.createElement(Sparkles, { className: "size-5" }),
    route: "/ai-tasks",
    color: "#9333EA",
    productMode: "visual",
    group: "Tools",
    children: [
      {
        id: "va-ai-tasks-list",
        label: "All Tasks",
        description: "View all AI analysis tasks",
        icon: React.createElement(Sparkles, { className: "size-4" }),
        route: "/ai-tasks",
        color: "#9333EA",
        productMode: "visual",
      },
    ],
  },
  {
    id: "va-project-tools",
    label: "Project Tools",
    icon: React.createElement(Box, { className: "size-5" }),
    route: "/automation-builder/overview",
    color: "var(--brand-primary)",
    productMode: "visual",
    children: [
      {
        id: "va-overview",
        label: "Overview",
        description: "Project summary and quick access",
        icon: React.createElement(LayoutDashboard, {
          className: "size-4",
        }),
        route: "/automation-builder/overview",
        color: "var(--brand-primary)",
        productMode: "visual",
      },
      {
        id: "va-dependencies",
        label: "Dependencies",
        description: "View state and workflow relationships",
        icon: React.createElement(GitBranch, { className: "size-4" }),
        route: "/automation-builder/dependencies",
        color: "var(--brand-primary)",
        productMode: "visual",
      },
      {
        id: "va-documentation",
        label: "Documentation",
        description: "Auto-generated project docs",
        icon: React.createElement(FileText, { className: "size-4" }),
        route: "/automation-builder/documentation",
        color: "var(--brand-primary)",
        productMode: "visual",
      },
      {
        id: "va-automation-analytics",
        label: "Automation Analytics",
        description: "Performance metrics and insights",
        icon: React.createElement(BarChart3, { className: "size-4" }),
        route: "/automation-builder/analytics",
        color: "var(--brand-primary)",
        productMode: "visual",
      },
      {
        id: "va-issues",
        label: "Issues",
        description: "Track and manage project issues",
        icon: React.createElement(AlertCircle, { className: "size-4" }),
        route: "/issues",
        color: "var(--brand-primary)",
        productMode: "visual",
      },
    ],
  },

  // ===========================================================================
  // Admin (superuser only)
  // ===========================================================================
  {
    id: "admin",
    label: "Admin",
    icon: React.createElement(Settings, { className: "size-5" }),
    route: "/admin",
    color: "#FF6B6B",
    adminOnly: true,
    group: "Admin",
    children: [
      {
        id: "admin-dashboard",
        label: "Dashboard",
        description: "Admin overview and metrics",
        icon: React.createElement(LayoutDashboard, { className: "size-4" }),
        route: "/admin",
        color: "#FF6B6B",
        adminOnly: true,
      },
      {
        id: "admin-annotations",
        label: "Annotations",
        description: "Manage training data annotations",
        icon: React.createElement(Scan, { className: "size-4" }),
        route: "/admin/annotations",
        color: "#FF6B6B",
        adminOnly: true,
      },
      {
        id: "admin-analysis",
        label: "GUI Analysis",
        description: "Analyze GUI elements globally",
        icon: React.createElement(Search, { className: "size-4" }),
        route: "/admin/analysis",
        color: "#FF6B6B",
        adminOnly: true,
      },
    ],
  },
];
