import React from "react";
import {
  LayoutDashboard,
  Workflow,
  Network,
  Sparkles,
  CheckCircle2,
  Settings,
  FileText,
  Scissors,
  Search,
  ImageIcon,
  Camera,
  Box,
  GitBranch,
  Scan,
  Target,
  Sliders,
  Globe,
  Play,
  Video,
  Monitor,
  Server,
  Store,
  CreditCard,
  TestTube2,
  Download,
  Database,
  BarChart3,
  AlertCircle,
  BookOpen,
  History,
  Activity,
  Bug,
  TrendingUp,
  Brain,
  Wrench,
  Eye,
  Webhook,
  Library,
  ScanSearch,
  Bot,
  ShieldCheck,
  FlaskConical,
  Wifi,
  FolderOpen,
  HardDrive,
  Archive,
  Layers,
  ListChecks,
  HelpCircle,
} from "lucide-react";
import type { NavItem } from "./types";

// =============================================================================
// Navigation Items
//
// Items with `hidden: true` only appear in development mode.
// Items with `adminOnly: true` only appear for superusers.
// Items with `group: "Label"` render a section separator above them.
// =============================================================================

export const navItems: NavItem[] = [
  // ===========================================================================
  // Build — Create and design workflows and steps
  // ===========================================================================
  {
    id: "workflows",
    label: "Workflows",
    description: "Workflow editor and AI generator",
    icon: React.createElement(Workflow, { className: "size-5" }),
    route: "/build/workflows",
    color: "var(--brand-secondary)",
    group: "Build",
  },
  {
    id: "step-builders",
    label: "Step Builders",
    description: "Build individual workflow steps",
    icon: React.createElement(Layers, { className: "size-5" }),
    route: "/build/templates",
    color: "var(--brand-secondary)",
  },
  {
    id: "step-library",
    label: "Step Library",
    description: "Browse and manage all created steps",
    icon: React.createElement(Library, { className: "size-5" }),
    route: "/library",
    color: "var(--brand-secondary)",
  },
  {
    id: "page-sweep",
    label: "Page Sweep",
    description: "Spec-driven workflows for every page",
    icon: React.createElement(Globe, { className: "size-5" }),
    route: "/build/page-sweep",
    color: "var(--brand-secondary)",
  },

  // ===========================================================================
  // Run — Execute workflows and view results
  // ===========================================================================
  {
    id: "execute",
    label: "Execute",
    description: "Run and schedule workflows",
    icon: React.createElement(Play, { className: "size-5" }),
    route: "/execute",
    color: "#10B981",
    group: "Run",
  },
  {
    id: "runs",
    label: "Runs",
    icon: React.createElement(History, { className: "size-5" }),
    route: "/runs",
    color: "#4A90D9",
    children: [
      {
        id: "runs-active",
        label: "Active",
        description: "Live monitoring dashboard",
        icon: React.createElement(Activity, { className: "size-4" }),
        route: "/runs/active",
        color: "#4A90D9",
      },
      {
        id: "runs-history",
        label: "History",
        description: "Run history browser",
        icon: React.createElement(History, { className: "size-4" }),
        route: "/runs",
        color: "#4A90D9",
      },
      {
        id: "runs-errors",
        label: "Errors",
        description: "Error monitoring and resolution",
        icon: React.createElement(AlertCircle, { className: "size-4" }),
        route: "/tools/error-monitor",
        color: "#4A90D9",
      },
      {
        id: "runs-findings",
        label: "Findings",
        description: "Cross-run findings",
        icon: React.createElement(Bug, { className: "size-4" }),
        route: "/runs/findings",
        color: "#4A90D9",
      },
      {
        id: "runs-statistics",
        label: "Statistics",
        description: "Performance analytics",
        icon: React.createElement(TrendingUp, { className: "size-4" }),
        route: "/runs/statistics",
        color: "#4A90D9",
      },
      {
        id: "runs-learning",
        label: "Learning",
        description: "ML insights dashboard",
        icon: React.createElement(Brain, { className: "size-4" }),
        route: "/runs/learning",
        color: "#4A90D9",
        hidden: true,
      },
      {
        id: "runs-checkpoints",
        label: "Checkpoints",
        description: "Execution checkpoint browser",
        icon: React.createElement(ListChecks, { className: "size-4" }),
        route: "/runs/checkpoints",
        color: "#4A90D9",
        hidden: true,
      },
      {
        id: "runs-discoveries",
        label: "Discoveries",
        description: "GUI state exploration results",
        icon: React.createElement(Search, { className: "size-4" }),
        route: "/runs/discoveries",
        color: "#4A90D9",
        hidden: true,
      },
    ],
  },

  // ===========================================================================
  // Manage — Infrastructure and configuration
  // ===========================================================================
  {
    id: "runners",
    label: "Runners",
    description: "Connected desktop runners",
    icon: React.createElement(Server, { className: "size-5" }),
    route: "/runners",
    color: "#10B981",
    group: "Manage",
  },
  {
    id: "settings",
    label: "Settings",
    icon: React.createElement(Settings, { className: "size-5" }),
    route: "/settings",
    color: "#FFD700",
    children: [
      {
        id: "settings-account",
        label: "Account",
        description: "Connection and identity",
        icon: React.createElement(Settings, { className: "size-4" }),
        route: "/settings/account",
        color: "#FFD700",
      },
      {
        id: "settings-ai",
        label: "AI Providers",
        description: "AI provider configuration",
        icon: React.createElement(Bot, { className: "size-4" }),
        route: "/settings/ai",
        color: "#FFD700",
      },
      {
        id: "settings-general",
        label: "General",
        description: "Application preferences",
        icon: React.createElement(Wrench, { className: "size-4" }),
        route: "/settings/general",
        color: "#FFD700",
      },
      {
        id: "settings-agentic",
        label: "Advanced AI",
        description: "Memory, retry, routing",
        icon: React.createElement(Brain, { className: "size-4" }),
        route: "/settings/agentic",
        color: "#FFD700",
      },
      {
        id: "settings-self-healing",
        label: "Self-Healing",
        description: "Automation recovery",
        icon: React.createElement(ShieldCheck, { className: "size-4" }),
        route: "/settings/self-healing",
        color: "#FFD700",
      },
      {
        id: "settings-playwright",
        label: "Playwright",
        description: "Test configuration",
        icon: React.createElement(FlaskConical, { className: "size-4" }),
        route: "/settings/playwright",
        color: "#FFD700",
      },
      {
        id: "settings-mcp",
        label: "MCP Servers",
        description: "External tool servers",
        icon: React.createElement(Wifi, { className: "size-4" }),
        route: "/settings/mcp",
        color: "#FFD700",
      },
      {
        id: "settings-log-sources",
        label: "Log Sources",
        description: "Log file monitoring config",
        icon: React.createElement(FolderOpen, { className: "size-4" }),
        route: "/settings/log-sources",
        color: "#FFD700",
      },
      {
        id: "settings-finding-rules",
        label: "Finding Rules",
        description: "Finding categories and rules",
        icon: React.createElement(ListChecks, { className: "size-4" }),
        route: "/configure/finding-rules",
        color: "#FFD700",
      },
      {
        id: "settings-hooks",
        label: "Hooks",
        description: "Workflow lifecycle hooks",
        icon: React.createElement(Webhook, { className: "size-4" }),
        route: "/configure/hooks",
        color: "#FFD700",
      },
      {
        id: "settings-storage",
        label: "Storage",
        description: "Local file management",
        icon: React.createElement(HardDrive, { className: "size-4" }),
        route: "/settings/storage",
        color: "#FFD700",
      },
      {
        id: "settings-backup",
        label: "Backup",
        description: "Export and restore data",
        icon: React.createElement(Archive, { className: "size-4" }),
        route: "/settings/backup",
        color: "#FFD700",
      },
      {
        id: "settings-updates",
        label: "Updates",
        description: "Version and updates",
        icon: React.createElement(Download, { className: "size-4" }),
        route: "/settings/updates",
        color: "#FFD700",
      },
      {
        id: "settings-debug",
        label: "Debug",
        description: "Diagnostics and debug",
        icon: React.createElement(FlaskConical, { className: "size-4" }),
        route: "/settings/debug",
        color: "#FFD700",
      },
    ],
  },
  {
    id: "help",
    label: "Help",
    icon: React.createElement(HelpCircle, { className: "size-5" }),
    route: "/help",
    color: "#9CA3AF",
  },

  // ===========================================================================
  // Hidden items (dev-only)
  // ===========================================================================
  {
    id: "inspector",
    label: "Inspector",
    description: "UI Bridge element inspection (dev debugging tool)",
    icon: React.createElement(ScanSearch, { className: "size-5" }),
    route: "/tools/inspector",
    color: "var(--brand-secondary)",
    hidden: true,
  },
  {
    id: "dashboard",
    label: "Dashboard",
    icon: React.createElement(LayoutDashboard, { className: "size-5" }),
    route: "/build/workflows",
    color: "var(--brand-primary)",
    hidden: true,
  },
  {
    id: "discover",
    label: "Discover",
    description: "AI-powered workflow generation (duplicate of Workflows)",
    icon: React.createElement(Sparkles, { className: "size-5" }),
    route: "/build/discover",
    color: "var(--brand-secondary)",
    hidden: true,
  },
  {
    id: "review",
    label: "Review",
    description: "UI Bridge full project review",
    icon: React.createElement(ScanSearch, { className: "size-5" }),
    route: "/build/review-workflow",
    color: "var(--brand-secondary)",
    hidden: true,
  },
  {
    id: "state-machine",
    label: "State Machine",
    description: "UI Bridge state machine builder",
    icon: React.createElement(Network, { className: "size-5" }),
    route: "/automation-builder/ui-bridge-states",
    color: "var(--brand-secondary)",
    hidden: true,
  },
  {
    id: "run-plan",
    label: "Run Plan",
    description: "Plan/schedule executions",
    icon: React.createElement(Sliders, { className: "size-5" }),
    route: "/tools/run-plan",
    color: "var(--brand-secondary)",
    hidden: true,
  },
  {
    id: "build-flow-designer",
    label: "Flow Designer",
    description: "AI-assisted workflow structure designer",
    icon: React.createElement(GitBranch, { className: "size-5" }),
    route: "/build/flow-designer",
    color: "var(--brand-secondary)",
    hidden: true,
  },

  // ===========================================================================
  // Visual Automation (hidden in production, visible in dev mode)
  // Preserves the pre-refactor sidebar structure for GUI automation pages.
  // ===========================================================================
  {
    id: "visual-automation",
    label: "Visual Automation",
    icon: React.createElement(Eye, { className: "size-5" }),
    route: "/automation-builder/states",
    color: "#06B6D4",
    hidden: true,
    children: [
      {
        id: "visual-automation-execute",
        label: "Execute",
        description: "GUI automation control surface",
        icon: React.createElement(Play, { className: "size-4" }),
        route: "/tools/visual-automation",
        color: "#10B981",
        hidden: true,
      },
      {
        id: "visual-automation-monitor",
        label: "Monitor",
        description: "Real-time automation monitoring",
        icon: React.createElement(Monitor, { className: "size-4" }),
        route: "/monitor",
        color: "#10B981",
        hidden: true,
      },
      {
        id: "visual-automation-capture",
        label: "Capture",
        description: "Screen capture and recording",
        icon: React.createElement(Video, { className: "size-4" }),
        route: "/tools/capture",
        color: "#10B981",
        hidden: true,
      },
      {
        id: "va-build",
        label: "GUI Build",
        icon: React.createElement(Network, { className: "size-4" }),
        route: "/automation-builder/states",
        color: "var(--brand-secondary)",
        hidden: true,
        children: [
          {
            id: "va-state-machine",
            label: "State Machine",
            description: "Define states and transitions",
            icon: React.createElement(Network, { className: "size-4" }),
            route: "/automation-builder/states",
            color: "var(--brand-secondary)",
            hidden: true,
          },
          {
            id: "va-workflows",
            label: "Workflows",
            description: "Create automation action sequences",
            icon: React.createElement(Workflow, { className: "size-4" }),
            route: "/automation-builder",
            color: "var(--brand-secondary)",
            hidden: true,
          },
          {
            id: "va-variables",
            label: "Variables",
            description: "Global configuration values",
            icon: React.createElement(Sliders, { className: "size-4" }),
            route: "/automation-builder/variables",
            color: "var(--brand-secondary)",
            hidden: true,
          },
          {
            id: "va-contexts",
            label: "AI Contexts",
            description: "Domain knowledge for AI tasks",
            icon: React.createElement(BookOpen, { className: "size-4" }),
            route: "/automation-builder/contexts",
            color: "var(--brand-secondary)",
            hidden: true,
          },
          {
            id: "va-marketplace",
            label: "Marketplace",
            description: "Community automation packages",
            icon: React.createElement(Store, { className: "size-4" }),
            route: "/marketplace",
            color: "var(--brand-secondary)",
            hidden: true,
          },
        ],
      },
      {
        id: "va-assets",
        label: "Assets",
        icon: React.createElement(ImageIcon, { className: "size-4" }),
        route: "/automation-builder/images",
        color: "#8B5CF6",
        hidden: true,
        children: [
          {
            id: "va-images",
            label: "Images",
            description: "Pattern image library",
            icon: React.createElement(ImageIcon, { className: "size-4" }),
            route: "/automation-builder/images",
            color: "#8B5CF6",
            hidden: true,
          },
          {
            id: "va-screenshots",
            label: "Screenshots",
            description: "Uploaded screenshots for pattern creation",
            icon: React.createElement(Camera, { className: "size-4" }),
            route: "/automation-builder/screenshots",
            color: "#8B5CF6",
            hidden: true,
          },
          {
            id: "va-recordings",
            label: "Recordings",
            description: "Video recordings for state discovery",
            icon: React.createElement(Video, { className: "size-4" }),
            route: "/recordings",
            color: "#8B5CF6",
            hidden: true,
          },
          {
            id: "va-visual-index",
            label: "Visual Index",
            description: "Indexed elements for visual search",
            icon: React.createElement(Database, { className: "size-4" }),
            route: "/projects/:projectId/rag",
            color: "#8B5CF6",
            hidden: true,
          },
        ],
      },
      {
        id: "va-create",
        label: "Create",
        icon: React.createElement(Sparkles, { className: "size-4" }),
        route: "/automation-builder/image-extraction",
        color: "var(--brand-success)",
        hidden: true,
        children: [
          {
            id: "va-extract-images",
            label: "Extract Images",
            description: "Cut pattern images from screenshots",
            icon: React.createElement(Scissors, { className: "size-4" }),
            route: "/automation-builder/image-extraction",
            color: "var(--brand-success)",
            hidden: true,
          },
          {
            id: "va-pattern-extraction",
            label: "Pattern Extraction",
            description: "Extract robust patterns from screenshots",
            icon: React.createElement(Sparkles, { className: "size-4" }),
            route: "/automation-builder/pattern-optimization",
            color: "var(--brand-success)",
            hidden: true,
          },
          {
            id: "va-annotations",
            label: "Annotations",
            description: "Create regions and locations for states",
            icon: React.createElement(Scan, { className: "size-4" }),
            route: "/automation-builder/annotations",
            color: "var(--brand-success)",
            hidden: true,
          },
          {
            id: "va-template-capture",
            label: "Template Capture",
            description: "Click-to-template element detection",
            icon: React.createElement(Target, { className: "size-4" }),
            route: "/automation-builder/template-capture",
            color: "var(--brand-success)",
            hidden: true,
          },
        ],
      },
      {
        id: "va-discover",
        label: "Discover",
        icon: React.createElement(Search, { className: "size-4" }),
        route: "/automation-builder/snapshot-tests",
        color: "#4ECDC4",
        hidden: true,
        children: [
          {
            id: "va-snapshot-tests",
            label: "Snapshot Tests",
            description: "Generate tests from page snapshot",
            icon: React.createElement(Camera, { className: "size-4" }),
            route: "/automation-builder/snapshot-tests",
            color: "#10b981",
            hidden: true,
          },
          {
            id: "va-navigation-tests",
            label: "Navigation Tests",
            description: "Generate tests from exploration",
            icon: React.createElement(GitBranch, { className: "size-4" }),
            route: "/automation-builder/navigation-tests",
            color: "#10b981",
            hidden: true,
          },
          {
            id: "va-discover-states",
            label: "Discover States",
            description: "Automatically discover UI states",
            icon: React.createElement(Search, { className: "size-4" }),
            route: "/automation-builder/state-discovery",
            color: "#4ECDC4",
            hidden: true,
          },
          {
            id: "va-extraction",
            label: "Discover",
            description: "Discover states from web, desktop, or render logs",
            icon: React.createElement(Globe, { className: "size-4" }),
            route: "/automation-builder/extraction",
            color: "#4ECDC4",
            hidden: true,
          },
        ],
      },
      {
        id: "va-config-testing",
        label: "Config Testing",
        icon: React.createElement(CheckCircle2, { className: "size-4" }),
        route: "/automation-builder/pattern-tests",
        color: "#FF6B6B",
        hidden: true,
        children: [
          {
            id: "va-pattern-tests",
            label: "Pattern Tests",
            description: "Test pattern recognition accuracy",
            icon: React.createElement(Target, { className: "size-4" }),
            route: "/automation-builder/pattern-tests",
            color: "#FF6B6B",
            hidden: true,
          },
          {
            id: "va-integration-tests",
            label: "Integration Tests",
            description: "End-to-end workflow testing",
            icon: React.createElement(TestTube2, { className: "size-4" }),
            route: "/integration-testing",
            color: "#FF6B6B",
            hidden: true,
          },
          {
            id: "va-semantic-analysis",
            label: "Semantic Analysis",
            description: "Analyze UI element semantics",
            icon: React.createElement(Scan, { className: "size-4" }),
            route: "/automation-builder/semantic-analysis",
            color: "#FF6B6B",
            hidden: true,
          },
          {
            id: "va-rag-testing",
            label: "RAG Testing",
            description: "Test RAG element matching with SAM3/CLIP",
            icon: React.createElement(Target, { className: "size-4" }),
            route: "/automation-builder/rag-testing",
            color: "#FF6B6B",
            hidden: true,
          },
          {
            id: "va-workflow-runner",
            label: "Workflow Runner",
            description: "Execute and debug workflows",
            icon: React.createElement(Play, { className: "size-4" }),
            route: "/workflow-viz",
            color: "#FF6B6B",
            hidden: true,
          },
          {
            id: "va-captures",
            label: "Captures",
            description: "Execution recordings with input events",
            icon: React.createElement(Camera, { className: "size-4" }),
            route: "/captures",
            color: "#FF6B6B",
            hidden: true,
          },
        ],
      },
      {
        id: "va-qa-testing",
        label: "QA Testing",
        icon: React.createElement(TestTube2, { className: "size-4" }),
        route: "/qa-dashboard",
        color: "#F59E0B",
        hidden: true,
        children: [
          {
            id: "va-qa-dashboard",
            label: "Dashboard",
            description: "QA testing overview and metrics",
            icon: React.createElement(LayoutDashboard, { className: "size-4" }),
            route: "/qa-dashboard",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-test-runs",
            label: "Test Runs",
            description: "View test execution history",
            icon: React.createElement(Play, { className: "size-4" }),
            route: "/testing",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-qa-runs",
            label: "QA Runs",
            description: "QA test run history",
            icon: React.createElement(TestTube2, { className: "size-4" }),
            route: "/qa-dashboard/runs",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-coverage",
            label: "Coverage",
            description: "Test coverage analysis",
            icon: React.createElement(BarChart3, { className: "size-4" }),
            route: "/qa-dashboard/coverage",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-deficiencies",
            label: "Deficiencies",
            description: "Track testing deficiencies",
            icon: React.createElement(Target, { className: "size-4" }),
            route: "/qa-dashboard/deficiencies",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-compare",
            label: "Compare",
            description: "Compare test results",
            icon: React.createElement(GitBranch, { className: "size-4" }),
            route: "/qa-dashboard/compare",
            color: "#F59E0B",
            hidden: true,
          },
          {
            id: "va-execution-history",
            label: "Execution History",
            description: "View detailed execution tree events",
            icon: React.createElement(Play, { className: "size-4" }),
            route: "/execution-history",
            color: "#F59E0B",
            hidden: true,
          },
        ],
      },
      {
        id: "va-ai-tasks",
        label: "AI Tasks",
        icon: React.createElement(Sparkles, { className: "size-4" }),
        route: "/ai-tasks",
        color: "#9333EA",
        hidden: true,
        children: [
          {
            id: "va-ai-tasks-list",
            label: "All Tasks",
            description: "View all AI analysis tasks",
            icon: React.createElement(Sparkles, { className: "size-4" }),
            route: "/ai-tasks",
            color: "#9333EA",
            hidden: true,
          },
        ],
      },
      {
        id: "va-project-tools",
        label: "Project Tools",
        icon: React.createElement(Box, { className: "size-4" }),
        route: "/automation-builder/overview",
        color: "var(--brand-primary)",
        hidden: true,
        children: [
          {
            id: "va-overview",
            label: "Overview",
            description: "Project summary and quick access",
            icon: React.createElement(LayoutDashboard, { className: "size-4" }),
            route: "/automation-builder/overview",
            color: "var(--brand-primary)",
            hidden: true,
          },
          {
            id: "va-dependencies",
            label: "Dependencies",
            description: "View state and workflow relationships",
            icon: React.createElement(GitBranch, { className: "size-4" }),
            route: "/automation-builder/dependencies",
            color: "var(--brand-primary)",
            hidden: true,
          },
          {
            id: "va-documentation",
            label: "Documentation",
            description: "Auto-generated project docs",
            icon: React.createElement(FileText, { className: "size-4" }),
            route: "/automation-builder/documentation",
            color: "var(--brand-primary)",
            hidden: true,
          },
          {
            id: "va-automation-analytics",
            label: "Automation Analytics",
            description: "Performance metrics and insights",
            icon: React.createElement(BarChart3, { className: "size-4" }),
            route: "/automation-builder/analytics",
            color: "var(--brand-primary)",
            hidden: true,
          },
          {
            id: "va-issues",
            label: "Issues",
            description: "Track and manage project issues",
            icon: React.createElement(AlertCircle, { className: "size-4" }),
            route: "/issues",
            color: "var(--brand-primary)",
            hidden: true,
          },
        ],
      },
      {
        id: "va-settings",
        label: "Settings",
        icon: React.createElement(Settings, { className: "size-4" }),
        route: "/automation-builder/settings",
        color: "#FFD700",
        hidden: true,
        children: [
          {
            id: "va-automation-settings",
            label: "Automation",
            description: "Configure automation preferences",
            icon: React.createElement(Sliders, { className: "size-4" }),
            route: "/automation-builder/settings",
            color: "#FFD700",
            hidden: true,
          },
          {
            id: "va-profile",
            label: "Profile",
            description: "Manage your account settings",
            icon: React.createElement(Settings, { className: "size-4" }),
            route: "/profile",
            color: "#FFD700",
            hidden: true,
          },
          {
            id: "va-pricing",
            label: "Pricing",
            description: "View plans and billing",
            icon: React.createElement(CreditCard, { className: "size-4" }),
            route: "/pricing",
            color: "#FFD700",
            hidden: true,
          },
        ],
      },
    ],
  },

  // ===========================================================================
  // Admin (superuser only)
  // ===========================================================================
  {
    id: "admin",
    label: "Admin",
    icon: React.createElement(Settings, { className: "size-5" }),
    route: "/admin",
    color: "#FF6B6B",
    adminOnly: true,
    children: [
      {
        id: "admin-dashboard",
        label: "Dashboard",
        description: "Admin overview and metrics",
        icon: React.createElement(LayoutDashboard, { className: "size-4" }),
        route: "/admin",
        color: "#FF6B6B",
        adminOnly: true,
      },
      {
        id: "admin-annotations",
        label: "Annotations",
        description: "Manage training data annotations",
        icon: React.createElement(Scan, { className: "size-4" }),
        route: "/admin/annotations",
        color: "#FF6B6B",
        adminOnly: true,
      },
      {
        id: "admin-analysis",
        label: "GUI Analysis",
        description: "Analyze GUI elements globally",
        icon: React.createElement(Search, { className: "size-4" }),
        route: "/admin/analysis",
        color: "#FF6B6B",
        adminOnly: true,
      },
    ],
  },
];
