import { LayoutStyle } from "@/lib/workflow-layout/auto-layout";
import type { LayoutPreset, LayoutStyleInfo } from "./auto-layout-types";

export const BUILTIN_PRESETS: LayoutPreset[] = [
  {
    id: "compact-hierarchical",
    name: "Compact Hierarchical",
    description: "Dense top-to-bottom layout",
    category: "compact",
    style: LayoutStyle.HIERARCHICAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 150,
      verticalSpacing: 100,
      branchOffset: 120,
      minNodeSpacing: 15,
    },
  },
  {
    id: "spacious-hierarchical",
    name: "Spacious Hierarchical",
    description: "Roomy top-to-bottom layout",
    category: "spacious",
    style: LayoutStyle.HIERARCHICAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 250,
      verticalSpacing: 150,
      branchOffset: 180,
      minNodeSpacing: 30,
    },
  },
  {
    id: "balanced-hierarchical",
    name: "Balanced Hierarchical",
    description: "Standard top-to-bottom layout",
    category: "balanced",
    style: LayoutStyle.HIERARCHICAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 200,
      verticalSpacing: 120,
      branchOffset: 150,
      minNodeSpacing: 20,
    },
  },
  {
    id: "compact-horizontal",
    name: "Compact Horizontal",
    description: "Dense left-to-right layout",
    category: "compact",
    style: LayoutStyle.HORIZONTAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 150,
      verticalSpacing: 100,
      branchOffset: 120,
      minNodeSpacing: 15,
    },
  },
  {
    id: "spacious-horizontal",
    name: "Spacious Horizontal",
    description: "Roomy left-to-right layout",
    category: "spacious",
    style: LayoutStyle.HORIZONTAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 250,
      verticalSpacing: 150,
      branchOffset: 180,
      minNodeSpacing: 30,
    },
  },
  {
    id: "balanced-tree",
    name: "Balanced Tree",
    description: "Standard tree layout",
    category: "balanced",
    style: LayoutStyle.TREE,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 180,
      verticalSpacing: 110,
      branchOffset: 140,
      minNodeSpacing: 20,
    },
  },
  {
    id: "force-directed-default",
    name: "Force-Directed Default",
    description: "Physics-based organic layout",
    category: "balanced",
    style: LayoutStyle.FORCE_DIRECTED,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 200,
      verticalSpacing: 120,
      branchOffset: 150,
      minNodeSpacing: 25,
    },
  },
  {
    id: "circular-default",
    name: "Circular Default",
    description: "Nodes arranged in a circle",
    category: "balanced",
    style: LayoutStyle.CIRCULAR,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 200,
      verticalSpacing: 120,
      branchOffset: 150,
      minNodeSpacing: 20,
    },
  },
  {
    id: "presentation-mode",
    name: "Presentation Mode",
    description: "Extra spacious for presentations",
    category: "spacious",
    style: LayoutStyle.HIERARCHICAL,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 300,
      verticalSpacing: 180,
      branchOffset: 200,
      minNodeSpacing: 40,
    },
  },
  {
    id: "debug-mode",
    name: "Debug Mode",
    description: "Ultra compact for debugging",
    category: "compact",
    style: LayoutStyle.TREE,
    options: {
      nodeWidth: 180,
      nodeHeight: 80,
      horizontalSpacing: 120,
      verticalSpacing: 90,
      branchOffset: 100,
      minNodeSpacing: 10,
    },
  },
];

export const LAYOUT_STYLES: Record<LayoutStyle, LayoutStyleInfo> = {
  [LayoutStyle.HIERARCHICAL]: {
    name: "Hierarchical",
    description: "Top-to-bottom flow",
    icon: "\u2B07\uFE0F",
    bestFor: ["Branching workflows", "Deep hierarchies", "General purpose"],
  },
  [LayoutStyle.HORIZONTAL]: {
    name: "Horizontal",
    description: "Left-to-right flow",
    icon: "\u27A1\uFE0F",
    bestFor: ["Linear workflows", "Sequential processes", "Timelines"],
  },
  [LayoutStyle.TREE]: {
    name: "Tree",
    description: "Compact tree structure",
    icon: "\uD83C\uDF33",
    bestFor: ["Deeply nested workflows", "Compact layouts", "Decision trees"],
  },
  [LayoutStyle.FORCE_DIRECTED]: {
    name: "Force-Directed",
    description: "Physics-based layout",
    icon: "\uD83D\uDD2E",
    bestFor: ["Complex graphs", "Interconnected nodes", "Organic structures"],
  },
  [LayoutStyle.CIRCULAR]: {
    name: "Circular",
    description: "Circular arrangement",
    icon: "\u2B55",
    bestFor: ["Small workflows", "Cycles", "Visualization"],
  },
};
