[tox]
skipsdist = true
envlist = py312, lint, type, format

[testenv]
allowlist_externals = poetry
commands =
    poetry install -v
    poetry run pytest tests/

[testenv:lint]
allowlist_externals = poetry
commands =
    poetry install -v
    poetry run ruff check backend/
    poetry run flake8 backend/
    poetry run pylint backend/

[testenv:type]
allowlist_externals = poetry
commands =
    poetry install -v
    poetry run mypy backend/

[testenv:format]
allowlist_externals = poetry
commands =
    poetry install -v
    poetry run black --check backend/
    poetry run isort --check-only backend/
