"""
Verification test model for defining reusable test specifications.

Supports multiple test types: Playwright browser tests, vision-based tests,
Python code tests, and repo/CLI test runners.
"""

from datetime import datetime
from enum import StrEnum
from uuid import UUID, uuid4

from qontinui_schemas.common import utc_now
from sqlalchemy import Boolean, DateTime, Enum, ForeignKey, Integer, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class VerificationTestType(StrEnum):
    """Test type enumeration."""

    PLAYWRIGHT = "playwright"
    VISION = "vision"
    PYTHON = "python"
    REPO_TEST = "repo_test"
    CUSTOM = "custom"


class VerificationTestCategory(StrEnum):
    """Test category enumeration."""

    SMOKE = "smoke"
    REGRESSION = "regression"
    INTEGRATION = "integration"
    E2E = "e2e"
    UNIT = "unit"
    PERFORMANCE = "performance"
    SECURITY = "security"
    ACCESSIBILITY = "accessibility"
    VISUAL = "visual"
    CUSTOM = "custom"


class VerificationTest(Base):
    """
    Verification test definition for reusable test specifications.

    Supports multiple test execution methods:
    - Playwright: Browser automation tests
    - Vision: Visual verification using Qontinui
    - Python: Custom Python test code
    - Repo Test: External test runners (pytest, jest, etc.)
    """

    __tablename__ = "verification_tests"

    # Primary key
    id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        primary_key=True,
        default=uuid4,
        server_default=text("gen_random_uuid()"),
    )

    # Foreign keys
    project_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    created_by_user_id: Mapped[UUID | None] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("runner.users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # Test identification
    name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )

    # Test classification
    test_type: Mapped[str] = mapped_column(
        Enum(
            VerificationTestType,
            name="verification_test_type",
            create_type=False,
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=False,
        index=True,
    )

    category: Mapped[str | None] = mapped_column(
        Enum(
            VerificationTestCategory,
            name="verification_test_category",
            create_type=False,
            values_callable=lambda x: [e.value for e in x],
        ),
        nullable=True,
        index=True,
    )

    # Playwright test configuration
    playwright_code: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Playwright test code (TypeScript)",
    )

    # Vision test configuration
    vision_config: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Vision test configuration (patterns, assertions)",
    )

    # Python test configuration
    python_code: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Python test code",
    )

    # Repo test configuration
    repo_test_config: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="External test runner config (command, working_dir, etc.)",
    )

    # Success criteria
    success_criteria: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Human-readable success criteria",
    )

    # General configuration
    config: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        server_default=text("'{}'::jsonb"),
        comment="Additional test configuration",
    )

    timeout_seconds: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=300,
        comment="Test timeout in seconds",
    )

    # Flags
    is_critical: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether test failure should block deployment",
    )

    enabled: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        index=True,
    )

    ai_generated: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        comment="Whether test was generated by AI",
    )

    # Tags for organization
    tags: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
        server_default=text("'[]'::jsonb"),
    )

    # Audit timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        server_default=text("now()"),
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
        server_default=text("now()"),
    )

    # Relationships
    project = relationship("Project", back_populates="verification_tests")

    created_by = relationship("User", back_populates="verification_tests")

    results = relationship(
        "TestResult",
        back_populates="test",
        cascade="all, delete-orphan",
        lazy="select",
    )

    workflow_associations = relationship(
        "WorkflowTestAssociation",
        back_populates="test",
        cascade="all, delete-orphan",
        lazy="select",
    )

    def __repr__(self) -> str:
        """Return string representation of VerificationTest."""
        return f"<VerificationTest(id={self.id}, name='{self.name}', type='{self.test_type}')>"
