#!/usr/bin/env python3
"""Vendor the slash lookalikes out of Unicode TR39 ``confusables.txt``.

One-time (re-run only to adopt a newer TR39 release; never at test or CI
time — nothing in the suite touches the network)::

    curl -sSfL https://www.unicode.org/Public/security/latest/confusables.txt \\
        -o /tmp/confusables.txt
    python -I backend/scripts/vendor_slash_confusables.py /tmp/confusables.txt

Writes ``backend/app/services/build_record_slash_confusables.py``: the code
points the build-record scanner folds to ``/`` before it looks for
``owner/name`` tokens, together with the ``Version`` and ``Date`` header of
the ``confusables.txt`` they came from.

The rule (no hand-picking): every entry whose SOURCE is a single code point
and whose TARGET (TR39 prototype) is U+002F SOLIDUS, optionally repeated and
optionally followed by combining marks (category ``Mn``) — so ``⫽`` (``//``)
and ``⧶`` (``/`` + combining macron) are included. Every slash-like character
TR39 knows (U+2215 DIVISION SLASH, U+2044 FRACTION SLASH, …) has U+002F as its
prototype, so this one rule covers them all.
"""

from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

BACKEND = Path(__file__).resolve().parents[1]
OUTPUT = BACKEND / "app" / "services" / "build_record_slash_confusables.py"
SOURCE_URL = "https://www.unicode.org/Public/security/latest/confusables.txt"


def slash_sources(text: str) -> list[int]:
    found: set[int] = set()
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [f.strip() for f in line.split(";")]
        source, target = fields[0].split(), fields[1].split()
        if len(source) != 1 or not target or target[0] != "002F":
            continue
        if all(
            t == "002F" or unicodedata.category(chr(int(t, 16))) == "Mn"
            for t in target[1:]
        ):
            found.add(int(source[0], 16))
    return sorted(found)


def header(text: str, key: str) -> str:
    match = re.search(rf"^#\s*{key}:\s*(.+)$", text, re.MULTILINE)
    if match is None:
        raise SystemExit(f"confusables.txt has no `# {key}:` header")
    return match.group(1).strip()


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    text = Path(argv[1]).read_text(encoding="utf-8")
    version, date = header(text, "Version"), header(text, "Date")
    points = slash_sources(text)
    lines = "\n".join(
        f"    0x{p:04X},  # {unicodedata.name(chr(p), 'UNNAMED')}" for p in points
    )
    OUTPUT.write_text(
        f'''"""GENERATED by backend/scripts/vendor_slash_confusables.py — do not edit.

Code points Unicode TR39 ``confusables.txt`` maps to U+002F SOLIDUS (see the
script for the exact rule), folded to ``/`` by the build-record scanner.

Source: {SOURCE_URL}
Version: {version}
Date: {date}
"""

CONFUSABLES_VERSION = "{version}"
CONFUSABLES_DATE = "{date}"

TR39_SLASH_CONFUSABLES: tuple[int, ...] = (
{lines}
)
''',
        encoding="utf-8",
    )
    print(f"wrote {OUTPUT.relative_to(BACKEND.parent)}: {len(points)} code points")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
