import type {
  ProjectOverviewData,
  OverviewSettings,
  LabourBillingType,
} from "./types";

const baseSettings = (
  projectName: string,
  baseCurrency: string,
  labourBilling: LabourBillingType,
  estimate?: OverviewSettings["estimate"]
): OverviewSettings => ({
  projectName,
  baseCurrency,
  labourBilling,
  estimate,
  canEdit: true,
});

// Scenario A: Warehouse Analytics Platform
export const scenarioA: ProjectOverviewData = {
  settings: baseSettings(
    "Warehouse Analytics Platform",
    "EUR",
    "unbilled",
    {
      name: "Delivery plan v0.1",
      purpose: "comparison",
      tiers: [
        { name: "Low", multiplier: 0.9, primary: false },
        { name: "Mid", multiplier: 1.0, primary: true },
        { name: "High", multiplier: 1.12, primary: false },
      ],
      contingencyPct: 10,
    }
  ),
  about:
    "A modern analytics platform for warehouse operations gives logistics teams real-time visibility into inventory, shipping, and staffing challenges.\n\nThe platform consolidates data from ERP, WMS, and labour systems into a single source of truth, making it safe to reduce error-prone manual reconciliation.\n\nSuccess means fewer reconciliation requests in support, faster decision-making during peak season, and better forecasting of staffing needs.",
  goals: [
    {
      title: "Reduce reconciliation requests",
      description: "Teams find discrepancies and resolve them without calling support.",
      status: "In progress",
    },
    {
      title: "Enable faster decision-making",
      description: "Managers see staff and inventory status in one view during peak periods.",
      status: "Planned",
    },
    {
      title: "Improve forecast accuracy",
      description: "Better data leads to better staffing and purchasing decisions.",
      status: "Planned",
    },
  ],
  recentProgress: [
    {
      title: "ERP integration complete",
      date: "2026-09-15",
      detail: "Real-time sync with inventory records established.",
    },
    {
      title: "First user testing session completed",
      date: "2026-09-08",
      detail: "Five warehouse managers validated the dashboard layout.",
    },
    {
      title: "Data validation rules finalized",
      date: "2026-08-31",
      detail: "Defined thresholds for flag and alert conditions.",
    },
  ],
  phases: [
    {
      id: "w0",
      name: "Discovery",
      plannedStart: "2025-05-01",
      plannedEnd: "2025-07-31",
      actualStart: "2025-05-01",
      actualEnd: "2025-07-28",
      status: "Done",
    },
    {
      id: "w1",
      name: "Design & Prototyping",
      plannedStart: "2025-08-01",
      plannedEnd: "2025-10-31",
      actualStart: "2025-08-04",
      actualEnd: "2025-10-22",
      status: "Done",
    },
    {
      id: "w2",
      name: "MVP Development",
      plannedStart: "2025-11-01",
      plannedEnd: "2026-02-28",
      actualStart: "2025-11-05",
      actualEnd: undefined,
      status: "In progress",
    },
    {
      id: "w3",
      name: "Refinement & Testing",
      plannedStart: "2026-03-01",
      plannedEnd: "2026-05-31",
      status: "Planned",
    },
    {
      id: "w4",
      name: "Handover",
      plannedStart: "2026-06-01",
      plannedEnd: "2026-07-15",
      status: "Planned",
    },
  ],
  tasks: [
    {
      id: "t1",
      phaseId: "w2",
      title: "Core dashboard layout",
      plannedStart: "2025-11-05",
      plannedEnd: "2025-12-05",
      actualStart: "2025-11-05",
      actualEnd: "2025-12-08",
      critical: true,
      status: "Done",
    },
    {
      id: "t2",
      phaseId: "w2",
      title: "ERP data integration",
      plannedStart: "2025-11-15",
      plannedEnd: "2026-01-15",
      actualStart: "2025-11-18",
      status: "In progress",
      critical: true,
    },
  ],
  gates: [
    {
      id: "g1",
      phaseId: "w1",
      name: "Design review gate",
      plannedDate: "2025-10-31",
      criteria: "All 5 core screens approved by steering committee",
      status: "Passed",
      actualDate: "2025-10-22",
    },
    {
      id: "g2",
      phaseId: "w2",
      name: "MVP readiness",
      plannedDate: "2026-02-28",
      criteria: "Core workflows tested with 3 pilot users",
      status: "Pending",
    },
  ],
  milestones: [
    {
      id: "m1",
      title: "Project kickoff",
      date: "2025-05-01",
      status: "Done",
    },
    {
      id: "m2",
      title: "Design freeze",
      date: "2025-10-15",
      status: "Done",
    },
    {
      id: "m3",
      title: "Pilot release",
      date: "2026-04-01",
      status: "Planned",
    },
  ],
  decisions: [
    {
      id: "d1",
      code: "D001",
      question: "Should we build a mobile app or focus on web first?",
      status: "Decided",
      neededBy: "w0",
      decision: "Web first; mobile in phase 2.",
      decidedOn: "2025-06-15",
    },
    {
      id: "d2",
      code: "D002",
      question: "Real-time or batch sync for ERP data?",
      status: "Blocking",
      neededBy: "w2",
    },
  ],
  risks: [
    {
      id: "r1",
      code: "R001",
      risk: "ERP API rate limits",
      consequence: "Data sync delays during peak times",
      mitigation: "Implement local caching and queue management",
      owner: "Tech Lead",
      status: "Open",
      likelihood: 3,
      impact: 4,
    },
    {
      id: "r2",
      code: "R002",
      risk: "User adoption challenges",
      consequence: "Platform underutilization",
      mitigation: "Early training program with super-users",
      owner: "Product Manager",
      status: "Mitigating",
      likelihood: 2,
      impact: 4,
    },
  ],
  vendors: [
    {
      id: "v1",
      name: "Claude Code",
      category: "AI subscriptions",
      status: "Recurring",
      description: "3 seats × $20/mo",
    },
    {
      id: "v2",
      name: "AWS",
      category: "Cloud",
      status: "Connected",
      lastSyncDate: "2026-09-18",
    },
    {
      id: "v3",
      name: "GitHub",
      category: "Source hosting",
      status: "Failed",
      lastSyncDate: "2026-09-12",
    },
  ],
  costs: [
    {
      id: "c1",
      vendorId: "v1",
      date: "2026-09-01",
      amountMicros: 60000000,
      originalCurrency: "USD",
      originalAmountMicros: 65217391,
      category: "Software",
      description: "Claude Code subscription",
      phaseId: "w2",
      repeatsMonthly: true,
      seatsOrUnits: 3,
      unitPriceMicros: 20000000,
    },
    {
      id: "c2",
      vendorId: "v2",
      date: "2026-09-15",
      amountMicros: 1842000000,
      originalCurrency: "USD",
      originalAmountMicros: 2002173913,
      category: "Cloud",
      description: "AWS compute and storage",
      phaseId: "w2",
    },
    {
      id: "c3",
      vendorId: "v3",
      date: "2026-08-01",
      amountMicros: 400000000,
      originalCurrency: "USD",
      originalAmountMicros: 434782609,
      category: "Hosting",
      description: "GitHub Team plan",
      phaseId: "w2",
      repeatsMonthly: true,
    },
  ],
  timeEntries: [
    {
      id: "te1",
      date: "2025-05-10",
      person: "Alice Chen",
      hours: 8,
      phaseId: "w0",
      note: "Discovery kickoff",
    },
    {
      id: "te2",
      date: "2025-05-10",
      person: "Bob Smith",
      hours: 6,
      phaseId: "w0",
      note: "Stakeholder interviews",
    },
  ],
  documents: [
    {
      id: "doc1",
      title: "Project Charter",
      type: "Written",
      documentNumber: "DOC-001",
      status: "Final",
      owner: "Project Manager",
      content: "# Project Charter\n\nThis document establishes the authority and mission of the Warehouse Analytics project.",
      updatedDate: "2025-05-15",
      updatedBy: "PM",
    },
    {
      id: "doc2",
      title: "Delivery Plan",
      type: "Written",
      documentNumber: "DOC-002",
      content: "# Delivery Plan v0.1\n\nPhase breakdown and timeline.",
      updatedDate: "2026-09-01",
      updatedBy: "Tech Lead",
    },
  ],
  wikiTopics: [
    {
      id: "wiki1",
      title: "Warehouse Operations",
      slug: "warehouse-operations",
      content: "Key terms related to warehouse operations.",
      updatedDate: "2026-09-01",
    },
    {
      id: "wiki2",
      title: "Analytics",
      slug: "analytics",
      content: "Our approach to data and reporting.",
      updatedDate: "2026-09-05",
    },
  ],
  slides: [
    {
      id: "slide1",
      title: "Warehouse Analytics Platform",
      updatedDate: "2026-09-18",
      slides: [{ id: "s1", content: "# Warehouse Analytics Platform\n## Executive Summary\n---\n# Status\nCurrently in MVP Development phase", notes: "This is the title slide." }],
    },
  ],
  diagrams: [
    {
      id: "diag1",
      title: "System Context",
      description: "High-level system interactions",
      source:
        "graph TB\n  subgraph External\n    ERP[ERP System]\n    WMS[Warehouse System]\n    HR[HR System]\n  end\n  subgraph Analytics\n    API[API Layer]\n    DB[(Database)]\n    UI[Analytics UI]\n  end\n  ERP -->|Extract| API\n  WMS -->|Extract| API\n  HR -->|Extract| API\n  API -->|Store| DB\n  DB -->|Query| UI",
      updatedDate: "2026-09-01",
    },
  ],
};

// Scenario B: Mobile Banking Refresh
export const scenarioB: ProjectOverviewData = {
  settings: baseSettings("Mobile Banking Refresh", "USD", "day_rates", {
    name: "Phase Budget",
    purpose: "budget",
  }),
  about:
    "The existing mobile banking app is showing its age. This refresh modernizes the UI, improves performance, and adds features customers are requesting.\n\nWe're keeping the core journey intact while making it faster and more intuitive.\n\nSuccess means improved app store ratings, fewer performance complaints, and higher engagement on new features.",
  goals: [
    {
      title: "Improve app store rating",
      description: "Target 4.5 stars or higher in both stores.",
      status: "In progress",
    },
    {
      title: "Reduce transaction time",
      description: "Critical paths complete in under 2 seconds.",
      status: "In progress",
    },
    {
      title: "Launch bill payment",
      description: "Customers can pay bills directly from the app.",
      status: "At risk",
    },
  ],
  recentProgress: [
    {
      title: "Auth flow redesigned and tested",
      date: "2026-09-10",
      detail: "New login flow shows 25% fewer steps.",
    },
    {
      title: "Performance improvements shipped",
      date: "2026-09-03",
      detail: "App load time cut by 40%.",
    },
    {
      title: "Design system finalized",
      date: "2026-08-27",
      detail: "All 45 components approved and documented.",
    },
  ],
  phases: [
    {
      id: "p1",
      name: "Phase 1",
      plannedStart: "2026-01-15",
      plannedEnd: "2026-03-15",
      actualStart: "2026-01-15",
      actualEnd: "2026-03-10",
      status: "Done",
    },
    {
      id: "p2",
      name: "Phase 2",
      plannedStart: "2026-03-20",
      plannedEnd: "2026-05-20",
      actualStart: "2026-03-20",
      actualEnd: "2026-05-25",
      status: "Done",
    },
    {
      id: "p3",
      name: "Phase 3",
      plannedStart: "2026-05-25",
      plannedEnd: "2026-07-25",
      actualStart: "2026-05-25",
      actualEnd: undefined,
      status: "In progress",
    },
    {
      id: "p4",
      name: "Phase 4",
      plannedStart: "2026-07-26",
      plannedEnd: "2026-09-30",
      status: "Planned",
    },
  ],
  tasks: [
    {
      id: "task1",
      phaseId: "p3",
      title: "Bill payment integration",
      plannedStart: "2026-06-01",
      plannedEnd: "2026-07-15",
      actualStart: "2026-06-05",
      status: "In progress",
      critical: true,
    },
  ],
  gates: [
    {
      id: "gate1",
      phaseId: "p2",
      name: "Phase 2 Review",
      plannedDate: "2026-05-20",
      criteria: "Performance targets met",
      status: "Passed",
      actualDate: "2026-05-25",
    },
  ],
  milestones: [
    {
      id: "mil1",
      title: "Phase 1 Complete",
      date: "2026-03-10",
      status: "Done",
    },
    {
      id: "mil2",
      title: "Phase 3 Complete (planned)",
      date: "2026-07-25",
      status: "Planned",
    },
  ],
  decisions: [
    {
      id: "dec1",
      code: "D101",
      question: "Should we support iOS 13+?",
      status: "Decided",
      neededBy: "p1",
      decision: "Yes, iOS 14+",
      decidedOn: "2026-01-20",
    },
    {
      id: "dec2",
      code: "D102",
      question: "Which payment processor?",
      status: "Blocking",
      neededBy: "p3",
    },
  ],
  risks: [
    {
      id: "risk1",
      code: "R101",
      risk: "Integration complexity with legacy auth",
      consequence: "Phase delays, increased rework",
      mitigation: "Early spike and prototype",
      owner: "Tech Lead",
      status: "Mitigating",
      likelihood: 3,
      impact: 3,
    },
    {
      id: "risk2",
      code: "R102",
      risk: "Platform dependency updates",
      consequence: "Unexpected bugs or delays",
      mitigation: "Weekly dependency review",
      owner: "Dev Lead",
      status: "Open",
      likelihood: 2,
      impact: 2,
    },
  ],
  vendors: [
    {
      id: "vb1",
      name: "AppCenter",
      category: "CI/CD",
      status: "Connected",
      lastSyncDate: "2026-09-18",
    },
    {
      id: "vb2",
      name: "DataDog",
      category: "Monitoring",
      status: "Recurring",
      description: "Performance monitoring",
    },
  ],
  costs: [
    {
      id: "cb1",
      vendorId: "vb1",
      date: "2026-09-01",
      amountMicros: 1500000000,
      category: "Tools",
      description: "App Center CI/CD",
      phaseId: "p3",
      repeatsMonthly: true,
    },
    {
      id: "cb2",
      vendorId: "vb2",
      date: "2026-09-01",
      amountMicros: 800000000,
      category: "Monitoring",
      description: "DataDog APM",
      phaseId: "p3",
      repeatsMonthly: true,
    },
  ],
  timeEntries: [
    {
      id: "teb1",
      date: "2026-09-10",
      person: "Carol Jones",
      hours: 8,
      role: "Senior Dev",
      phaseId: "p3",
      note: "Payment integration work",
    },
    {
      id: "teb2",
      date: "2026-09-10",
      person: "David Lee",
      hours: 6,
      role: "QA",
      phaseId: "p3",
      note: "Integration testing",
    },
  ],
  documents: [
    {
      id: "docb1",
      title: "Requirements",
      type: "Written",
      documentNumber: "REQ-001",
      content: "# Mobile Banking Refresh Requirements",
      updatedDate: "2026-01-15",
    },
  ],
  wikiTopics: [
    {
      id: "wikib1",
      title: "Mobile Architecture",
      slug: "mobile-architecture",
      content: "Our mobile app structure and patterns.",
      updatedDate: "2026-05-01",
    },
  ],
  slides: [
    {
      id: "slideb1",
      title: "Mobile Banking Refresh",
      updatedDate: "2026-09-12",
      slides: [{ id: "sb1", content: "# Mobile Banking Refresh\n## Progress Update\n---\n# Status", notes: "Update for steering committee" }],
    },
  ],
  diagrams: [
    {
      id: "diagb1",
      title: "Architecture",
      description: "Mobile app architecture",
      source:
        "graph TB\n  iOS[iOS App]\n  Android[Android App]\n  API[API Gateway]\n  Services[Microservices]\n  iOS --> API\n  Android --> API\n  API --> Services",
      updatedDate: "2026-01-15",
    },
  ],
};

// Scenario C: Minimal (no estimate, no vendors, no phases)
export const scenarioC: ProjectOverviewData = {
  settings: baseSettings("New Exploratory Project", "USD", "unbilled"),
  recentProgress: [],
  phases: [],
  tasks: [],
  gates: [],
  milestones: [],
  decisions: [],
  risks: [],
  vendors: [],
  costs: [],
  timeEntries: [],
  documents: [],
  wikiTopics: [],
  slides: [],
  diagrams: [],
};
