"""The plan-library keyset walk and the shared cursor codec behind it.

Plan ``2026-09-05-every-bounded-read-is-a-page-that-reads-as-a-corpus``
Phase 4. Four guarantees, each pinned here:

1. **The Python codec IS the Rust codec.** ``app.core.bounded_read`` decodes
   tokens Rust ``page.rs`` minted (a committed fixture, never regenerated by
   Python) and re-mints them byte for byte — the cross-language guard Phase 1
   deferred to the codec's first consumer.
2. **A bad cursor is a typed 400** ``cursor_malformed`` naming ``cursor`` —
   garbage, a padded token, a token replayed under different filters — never a
   500 and never a silently different page.
3. **D8: the sort key is immutable.** Every walk keys on ``created_at``; a grep
   over ``app/`` and the migrations proves nothing UPDATEs it. A walk keeps
   every row even when an unreached row is UPDATED mid-walk — which the old
   ``updated_at DESC`` + ``OFFSET`` order could not.
4. **No silent truncation.** ``/candidates`` discloses a capped coord walk on
   the wire (``work_unit_population_state: "truncated"``, a non-exact bound),
   and a ``?q=`` search page carries ``total`` / ``truncated`` / a cursor.
"""

from __future__ import annotations

import base64
import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, patch
from uuid import UUID, uuid4

import httpx
import pytest
import pytest_asyncio
from fastapi import HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from app.core import bounded_read as br
from app.crud import work_artifact as crud
from tests.test_plan_library_api import API_PREFIX, _build_app, _payload
from tests.test_plan_library_candidates import _coord_unit


@pytest_asyncio.fixture()
async def client(async_db_session: AsyncSession):
    """``test_plan_library_api``'s app, authenticated as a fresh user."""
    from app.models.user import User

    user = User(
        email=f"keyset_{uuid4().hex[:8]}@example.com",
        username=f"keyset_{uuid4().hex[:8]}",
        full_name="Keyset Tester",
        is_active=True,
        is_verified=True,
    )
    async_db_session.add(user)
    await async_db_session.commit()
    await async_db_session.refresh(user)
    app = _build_app(db_session=async_db_session, user=user)
    async with httpx.AsyncClient(
        transport=httpx.ASGITransport(app=app), base_url="http://test"
    ) as http_client:
        yield http_client


BACKEND = Path(__file__).resolve().parents[1]
FIXTURE = BACKEND / "tests" / "fixtures" / "bounded_read" / "rust_minted_cursors.json"

#: Fixture scope ``type`` → the Python builder method (Rust's ``bool`` is
#: ``boolean`` here, so it does not shadow the builtin inside the class).
_SCOPE_METHODS = {
    "opt_str": "opt_str",
    "uuid": "uuid",
    "opt_uuid": "opt_uuid",
    "bool": "boolean",
    "i64": "i64",
    "str_set": "str_set",
}


def _fixture_cases() -> list[dict[str, Any]]:
    return list(json.loads(FIXTURE.read_text(encoding="utf-8"))["cases"])


def _fingerprint(case: dict[str, Any]) -> br.ScopeFingerprint:
    scope = br.CursorScope(br.SortKey(case["sort_key"]))
    for field in case["scope"]:
        value = field["value"]
        if field["type"] in ("uuid", "opt_uuid") and value is not None:
            value = UUID(value)
        getattr(scope, _SCOPE_METHODS[field["type"]])(field["name"], value)
    return scope.finish()


def _b64(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


# ===========================================================================
# 1. Cross-language: Rust-minted tokens
# ===========================================================================


class TestRustMintedTokens:
    @pytest.mark.parametrize("case", _fixture_cases(), ids=lambda c: c["name"])
    def test_python_fingerprints_the_scope_exactly_as_rust_did(
        self, case: dict[str, Any]
    ) -> None:
        assert _fingerprint(case).hex == case["fingerprint"]

    @pytest.mark.parametrize("case", _fixture_cases(), ids=lambda c: c["name"])
    def test_python_decodes_the_rust_token_to_the_rust_position(
        self, case: dict[str, Any]
    ) -> None:
        pos = _fingerprint(case).decode(case["token"])
        assert br._to_micros(pos.at) == case["position"]["at_micros"]
        assert str(pos.id) == case["position"]["id"]

    @pytest.mark.parametrize("case", _fixture_cases(), ids=lambda c: c["name"])
    def test_python_mints_the_byte_identical_token(self, case: dict[str, Any]) -> None:
        """Encode is the strict inverse: Rust will decode what web mints."""
        fp = _fingerprint(case)
        assert fp.encode(fp.decode(case["token"])) == case["token"]

    def test_the_fixture_covers_every_scope_value_type(self) -> None:
        seen = {f["type"] for c in _fixture_cases() for f in c["scope"]}
        assert seen == set(_SCOPE_METHODS)

    def test_a_rust_token_for_another_sort_key_is_refused(self) -> None:
        cases = {c["name"]: c for c in _fixture_cases()}
        other = cases["other_sort_key"]
        with pytest.raises(br.CursorError) as exc:
            _fingerprint(cases["empty_scope"]).decode(other["token"])
        assert exc.value.reason is br.CursorRejection.SORT_KEY


# ===========================================================================
# 2. Strict decode, typed refusal
# ===========================================================================


_KEY = br.SortKey("test.rows:created_at,id")


def _fp(tenant: str = "a") -> br.ScopeFingerprint:
    return br.CursorScope(_KEY).opt_str("tenant", tenant).finish()


def _payload_token(fp: br.ScopeFingerprint, **override: Any) -> str:
    body: dict[str, Any] = {
        "v": 1,
        "s": fp.sort_key.id,
        "k": 1_700_000_000_000_000,
        "i": str(uuid4()),
        "f": fp.hex,
    }
    body.update(override)
    return _b64(json.dumps(body, separators=(",", ":")).encode())


class TestStrictDecode:
    def test_round_trip_at_microsecond_resolution(self) -> None:
        pos = br.KeysetPosition(
            at=datetime(2026, 9, 5, 1, 2, 3, 456789, tzinfo=UTC), id=uuid4()
        )
        assert _fp().decode(_fp().encode(pos)) == pos

    @pytest.mark.parametrize(
        ("token", "reason"),
        [
            ("", br.CursorRejection.EMPTY),
            ("   ", br.CursorRejection.EMPTY),
            ("A" * (br.CURSOR_MAX_TOKEN_LEN + 1), br.CursorRejection.TOO_LONG),
            ("not base64!", br.CursorRejection.ENCODING),
            ("abc+/", br.CursorRejection.ENCODING),
            ("A", br.CursorRejection.ENCODING),
            (_b64(b"not json"), br.CursorRejection.PAYLOAD),
            (_b64(b"[1,2]"), br.CursorRejection.PAYLOAD),
        ],
    )
    def test_garbage_is_a_cursor_error_never_a_crash(
        self, token: str, reason: br.CursorRejection
    ) -> None:
        with pytest.raises(br.CursorError) as exc:
            _fp().decode(token)
        assert exc.value.reason is reason

    def test_a_padded_token_is_refused(self) -> None:
        token = _fp().encode(br.KeysetPosition(at=datetime.now(UTC), id=uuid4()))
        padded = token + "=" * (-len(token) % 4 or 4)
        with pytest.raises(br.CursorError) as exc:
            _fp().decode(padded)
        assert exc.value.reason is br.CursorRejection.ENCODING

    def test_non_canonical_trailing_bits_are_refused(self) -> None:
        """The Rust engine refuses them; so must the twin."""
        token = _fp().encode(br.KeysetPosition(at=datetime.now(UTC), id=uuid4()))
        if len(token) % 4 == 0:  # pragma: no cover — no spare bits to flip
            pytest.skip("this token length carries no trailing bits")
        alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
        last = alphabet.index(token[-1])
        tweaked = token[:-1] + alphabet[last ^ 1]
        with pytest.raises(br.CursorError) as exc:
            _fp().decode(tweaked)
        assert exc.value.reason in (
            br.CursorRejection.ENCODING,
            br.CursorRejection.PAYLOAD,
        )

    @pytest.mark.parametrize(
        "override",
        [
            {"x": 1},  # an unknown field
            {"k": 1.5},
            {"k": True},
            {"v": "1"},
            {"v": 256},
            {"i": "not-a-uuid"},
            {"k": 2**63},
        ],
    )
    def test_a_payload_rust_would_not_parse_is_refused(
        self, override: dict[str, Any]
    ) -> None:
        with pytest.raises(br.CursorError) as exc:
            _fp().decode(_payload_token(_fp(), **override))
        assert exc.value.reason is br.CursorRejection.PAYLOAD

    def test_a_duplicate_field_is_refused(self) -> None:
        fp = _fp()
        raw = (
            f'{{"v":1,"v":1,"s":"{fp.sort_key.id}","k":0,'
            f'"i":"{uuid4()}","f":"{fp.hex}"}}'
        ).encode()
        with pytest.raises(br.CursorError) as exc:
            fp.decode(_b64(raw))
        assert exc.value.reason is br.CursorRejection.PAYLOAD

    def test_version_sort_key_scope_and_range_each_refuse(self) -> None:
        fp = _fp()
        for override, reason in (
            ({"v": 2}, br.CursorRejection.VERSION),
            ({"s": "other:created_at,id"}, br.CursorRejection.SORT_KEY),
            ({"f": _fp("b").hex}, br.CursorRejection.SCOPE),
            ({"k": -(2**62)}, br.CursorRejection.TIMESTAMP),
        ):
            with pytest.raises(br.CursorError) as exc:
                fp.decode(_payload_token(fp, **override))
            assert exc.value.reason is reason, override

    def test_an_empty_cursor_param_is_the_first_page(self) -> None:
        """``?cursor=`` reads as no cursor (coord's grammar); ``decode`` itself
        stays strict about an empty token."""
        for token in (None, "", "   "):
            assert _fp().decode_param(token, surface="GET /x") is None

    def test_the_refusal_is_a_typed_400_naming_the_parameter(self) -> None:
        with pytest.raises(HTTPException) as exc:
            _fp().decode_param("garbage!", surface="GET /x")
        assert exc.value.status_code == 400
        detail = exc.value.detail
        assert isinstance(detail, dict)
        assert detail["error"] == "cursor_malformed"
        assert detail["parameter"] == "cursor"
        assert "GET /x" in detail["message"]
        assert "garbage" not in json.dumps(detail), "the token must not echo"

    def test_scope_fields_are_tagged_so_absence_never_collides(self) -> None:
        none = br.CursorScope(_KEY).opt_str("q", None).finish()
        empty = br.CursorScope(_KEY).opt_str("q", "").finish()
        literal_n = br.CursorScope(_KEY).opt_str("q", "n").finish()
        assert len({none.hex, empty.hex, literal_n.hex}) == 3

    def test_str_set_is_order_and_duplicate_insensitive(self) -> None:
        a = br.CursorScope(_KEY).str_set("r", ["b", "a", "a"]).finish()
        b = br.CursorScope(_KEY).str_set("r", ["a", "b"]).finish()
        assert a == b


class TestStemPosition:
    def test_dated_stems_walk_by_day(self) -> None:
        early = crud.stem_position("2026-01-02-zzz")
        late = crud.stem_position("2026-03-01-aaa")
        assert (early.at, early.id) < (late.at, late.id)

    def test_position_is_a_pure_function_of_the_stem(self) -> None:
        assert crud.stem_position("2026-09-05-x") == crud.stem_position("2026-09-05-x")
        assert crud.stem_position("2026-09-05-x") != crud.stem_position("2026-09-05-y")

    def test_an_undated_or_impossible_date_sorts_first(self) -> None:
        for stem in ("no-date-here", "2026-13-45-bad-month"):
            assert crud.stem_position(stem).at == datetime(1970, 1, 1, tzinfo=UTC)


# ===========================================================================
# 3. D8 — the walked keys have no UPDATE site
# ===========================================================================


#: An UPDATE of either walked table whose SET clause names ``created_at``.
_SQL_UPDATE = re.compile(
    r"UPDATE\s+(?:agent\.)?work_artifact(?:s|_edges)\b[^;]{0,600}?"
    r"\bSET\b[^;]{0,600}?\bcreated_at\b",
    re.IGNORECASE | re.DOTALL,
)
#: A SQLAlchemy ``update(WorkArtifact…)`` whose values name ``created_at``.
_ORM_UPDATE = re.compile(
    r"update\(\s*WorkArtifact(?:Edge)?\s*\)[^#]{0,600}?\bcreated_at\s*[=:]",
    re.DOTALL,
)
#: An attribute write / metadata tuple naming the column.
_ATTR_WRITE = re.compile(r"\.created_at\s*=(?!=)|\(\s*\"created_at\"\s*,")


def _sources() -> list[Path]:
    return [
        *sorted((BACKEND / "app").rglob("*.py")),
        *sorted((BACKEND / "alembic" / "versions").glob("*.py")),
    ]


class TestTheSortKeyIsImmutable:
    def test_the_patterns_catch_what_they_claim_to(self) -> None:
        """Self-validation: a grep that matches nothing proves nothing."""
        assert _SQL_UPDATE.search(
            "UPDATE agent.work_artifacts SET status = 'x', created_at = now()"
        )
        assert _SQL_UPDATE.search("update work_artifact_edges\n set created_at=now()")
        assert _ORM_UPDATE.search("update(WorkArtifact).values(created_at=now)")
        assert _ATTR_WRITE.search("row.created_at = moment")
        assert _ATTR_WRITE.search('("created_at", metadata.created_at)')
        assert not _SQL_UPDATE.search("UPDATE agent.work_artifacts SET status = 'x'")

    def test_nothing_updates_a_walked_created_at(self) -> None:
        hits: list[str] = []
        for path in _sources():
            text = path.read_text(encoding="utf-8")
            rel = path.relative_to(BACKEND).as_posix()
            for pattern in (_SQL_UPDATE, _ORM_UPDATE):
                hits.extend(
                    f"{rel}: {m.group(0)[:80]!r}" for m in pattern.finditer(text)
                )
            if "WorkArtifact" in text:
                hits.extend(
                    f"{rel}: {m.group(0)!r}" for m in _ATTR_WRITE.finditer(text)
                )
        assert not hits, (
            "a keyset sort key (agent.work_artifacts / work_artifact_edges "
            "created_at) gained an UPDATE site — an unreached row whose key "
            "moves across a cursor is silently dropped from the walk (D8):\n"
            + "\n".join(hits)
        )

    def test_authored_at_is_written_which_is_why_it_never_keys_a_walk(self) -> None:
        """D8 names ``authored_at`` as eligible; here it is NOT — the upsert
        rewrites it. If this ever stops matching, it may become eligible."""
        crud_src = (BACKEND / "app" / "crud" / "work_artifact.py").read_text(
            encoding="utf-8"
        )
        assert re.search(r"\(\s*\"authored_at\"\s*,", crud_src)
        for key in (
            crud.ARTIFACT_LIST_SORT_KEY,
            crud.CANDIDATE_SORT_KEY,
            crud.FOLLOWUP_SORT_KEY,
        ):
            assert "authored_at" not in key.id and "updated_at" not in key.id


# ===========================================================================
# 4. The routes
# ===========================================================================


async def _post(client: httpx.AsyncClient, **overrides: Any) -> dict[str, Any]:
    resp = await client.post(API_PREFIX, json=_payload(**overrides))
    assert resp.status_code in (200, 201), resp.text
    return dict(resp.json()["artifact"])


async def _walk(
    client: httpx.AsyncClient, path: str, params: dict[str, Any]
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Every page of a walk, following ``next_cursor`` to its end."""
    rows: list[dict[str, Any]] = []
    pages: list[dict[str, Any]] = []
    cursor: str | None = None
    for _ in range(50):
        query = dict(params)
        if cursor is not None:
            query["cursor"] = cursor
        resp = await client.get(path, params=query)
        assert resp.status_code == 200, resp.text
        page = resp.json()
        pages.append(page)
        rows.extend(page["items"])
        cursor = page["next_cursor"]
        if cursor is None:
            return rows, pages
    raise AssertionError("the walk did not terminate")


@pytest.mark.asyncio
class TestTheListWalk:
    async def test_the_walk_tiles_the_corpus_and_every_page_states_its_bound(
        self, client: httpx.AsyncClient
    ) -> None:
        stem = f"walk-{uuid4().hex[:8]}"
        ids = {
            (await _post(client, slug=f"{stem}-{n}", work_unit_slug=stem))["id"]
            for n in range(5)
        }
        rows, pages = await _walk(
            client, API_PREFIX, {"work_unit_slug": stem, "limit": 2}
        )
        assert [r["id"] for r in rows] == list(dict.fromkeys(r["id"] for r in rows))
        assert {r["id"] for r in rows} == ids
        assert [p["total"] for p in pages] == [5, 3, 1]
        assert [p["truncated"] for p in pages] == [True, True, False]
        assert all(p["bound_kind"] == "exact" for p in pages)
        assert all(p["enumerate_via"] is None for p in pages)
        assert pages[0]["ordering"] == "newest_captured_first"
        assert "offset" not in pages[0]

    async def test_an_update_mid_walk_does_not_drop_the_row(
        self, client: httpx.AsyncClient
    ) -> None:
        """The defect D8 exists for: under ``updated_at DESC`` an unreached row
        that is written to jumps ahead of the cursor and is never served."""
        stem = f"mutate-{uuid4().hex[:8]}"
        posted = [
            await _post(client, slug=f"{stem}-{n}", work_unit_slug=stem, body=f"v{n}")
            for n in range(4)
        ]
        first = await client.get(
            API_PREFIX, params={"work_unit_slug": stem, "limit": 2}
        )
        page1 = first.json()
        seen = {r["id"] for r in page1["items"]}
        unreached = next(p for p in posted if p["id"] not in seen)
        await _post(
            client,
            slug=unreached["slug"],
            work_unit_slug=stem,
            body="rewritten mid-walk",
            status="SHIPPED",
        )
        rest, _ = await _walk(
            client,
            API_PREFIX,
            {"work_unit_slug": stem, "limit": 2, "cursor": page1["next_cursor"]},
        )
        assert seen | {r["id"] for r in rest} == {p["id"] for p in posted}

    async def test_a_cursor_replayed_under_other_filters_is_a_typed_400(
        self, client: httpx.AsyncClient
    ) -> None:
        stem = f"replay-{uuid4().hex[:8]}"
        for n in range(3):
            await _post(client, slug=f"{stem}-{n}", work_unit_slug=stem)
        page = (
            await client.get(API_PREFIX, params={"work_unit_slug": stem, "limit": 1})
        ).json()
        replayed = await client.get(
            API_PREFIX, params={"kind": "plan", "cursor": page["next_cursor"]}
        )
        assert replayed.status_code == 400, replayed.text
        detail = replayed.json()["detail"]
        assert detail["error"] == "cursor_malformed"
        assert detail["parameter"] == "cursor"
        assert detail["reason"] == "scope"

        garbage = await client.get(API_PREFIX, params={"cursor": "%%%"})
        assert garbage.status_code == 400
        assert garbage.json()["detail"]["error"] == "cursor_malformed"

    async def test_offset_is_deleted_not_deprecated(
        self, client: httpx.AsyncClient
    ) -> None:
        for path in ("", "/candidates", "/followups", "/reconciliation"):
            resp = await client.get(f"{API_PREFIX}{path}", params={"offset": 0})
            assert resp.status_code == 422, (path, resp.text)
            assert "unknown_query_parameter" in resp.text, path

    async def test_a_search_page_discloses_its_bound_and_walks_on(
        self, client: httpx.AsyncClient
    ) -> None:
        """``?q=`` returned exactly one page with no count and no way on; a
        capped search page is not evidence that a plan is absent."""
        word = f"zebrafinch{uuid4().hex[:6]}"
        ids = {
            (await _post(client, slug=f"q-{word}-{n}", body=f"# about {word}"))["id"]
            for n in range(3)
        }
        rows, pages = await _walk(client, API_PREFIX, {"q": word, "limit": 2})
        assert pages[0]["total"] == 3
        assert pages[0]["truncated"] is True
        assert pages[0]["next_cursor"]
        assert {r["id"] for r in rows} == ids


@pytest.mark.asyncio
class TestCandidatesNeverTruncateSilently:
    async def test_a_capped_coord_walk_is_disclosed_on_the_wire(
        self, client: httpx.AsyncClient
    ) -> None:
        """coord serves a full page forever; the walk stops at its cap. The
        response must SAY so — a log line is not a disclosure."""

        async def _endless(path: str, **kwargs: Any) -> Any:
            if path in ("/coord/work-units", "/coord/agent-work-units"):
                offset = int((kwargs.get("params") or {}).get("offset", "0"))
                unit = _coord_unit(
                    f"2026-07-0{offset + 1}-endless-{offset}",
                    created_at=f"2026-07-0{offset + 1}T00:00:00Z",
                )
                return {"work_units": [unit], "limit": 1, "offset": offset}
            return {}

        with (
            patch("app.api.v1.endpoints.plan_library._COORD_UNIT_PAGE_LIMIT", 1),
            patch("app.api.v1.endpoints.plan_library._COORD_UNIT_MAX_PAGES", 2),
            patch(
                "app.api.v1.endpoints.plan_library._proxy_coord_get",
                new=AsyncMock(side_effect=_endless),
            ),
            patch(
                "app.api.v1.endpoints.plan_library._soft_tenant_id",
                new=AsyncMock(return_value=uuid4()),
            ),
        ):
            # include_coord stays on; the walk is followed to its end. The
            # NULL org bucket may hold other tests' committed plans, so the
            # page count is not fixed — the bound on each page is.
            pages = []
            cursor: str | None = None
            for _ in range(500):
                params: dict[str, Any] = {"limit": 1}
                if cursor is not None:
                    params["cursor"] = cursor
                resp = await client.get(f"{API_PREFIX}/candidates", params=params)
                assert resp.status_code == 200, resp.text
                pages.append(resp.json())
                cursor = pages[-1]["next_cursor"]
                if cursor is None:
                    break

        assert len(pages) >= 2
        assert all(p["work_unit_population_state"] == "truncated" for p in pages)
        assert all(p["work_unit_population_reason"] for p in pages)
        assert all(p["total"] is None for p in pages), "never an exact count"
        for page in pages[:-1]:
            assert page["bound_kind"] == "at_least"
            assert page["truncated"] is True
            assert page["next_cursor"]
        # The last page shows everything READ, and nothing proves that was
        # everything: unknown, never a confident "that is all".
        assert pages[-1]["bound_kind"] == "unknown"
        assert pages[-1]["truncated"] is None
        slugs = [i["slug"] for p in pages for i in p["items"]]
        assert "2026-07-01-endless-0" in slugs and "2026-07-02-endless-1" in slugs
