"""Round-trip test for ``plan_library_10_archive``.

Plan ``2026-09-12-plan-library-has-no-delete-so-a-junk-row-is-permanent``
Phase 1. The API suite builds its schema from the MODEL, so it cannot notice a
migration that disagrees with it. What only the alembic-built table can show:

* the three archive columns land NULLABLE with the model's types, and a row
  that existed before them reads as LIVE (``archived_at IS NULL``);
* the live-row partial index exists, is VALID (it is built CONCURRENTLY), and
  carries the ``archived_at IS NULL`` predicate the reads compose;
* head → downgrade → head leaves no residue.

Statically, it also pins the shape coord's migration classifier admits: no SQL
through ``op.get_bind()`` and no ``DROP`` outside ``downgrade()``.

Substrate is ``tests/_alembic_harness``. ⚠️ A skip proves nothing — point it at
a live instance with ``QONTINUI_TEST_PG=localhost:<port>``.
"""

from __future__ import annotations

import ast
import sys
import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.engine import Engine

from app.models.work_artifact import WorkArtifact
from tests._alembic_harness import (
    admin_database_url,
    backend_root,
    can_connect,
    ephemeral_database,
    run_alembic,
)

# The head gate's own parser — see the 06 revision's test for why.
_SCRIPTS_CI = backend_root().parent / "scripts" / "ci"
sys.path.insert(0, str(_SCRIPTS_CI))

from _alembic_graph import PARENT_REF_RE, parse_source  # noqa: E402

_REVISION_ID = "plan_library_10_archive"
_REVISION_FILENAME = "plan_library_10_archive.py"
_INDEX = "ix_work_artifacts_live_kind_status"

#: ``column -> information_schema.columns.data_type``.
_EXPECTED_COLUMNS = {
    "archived_at": "timestamp with time zone",
    "archived_by": "text",
    "archive_reason": "text",
}


def _revision_source() -> str:
    return (backend_root() / "alembic" / "versions" / _REVISION_FILENAME).read_text(
        encoding="utf-8"
    )


def _parent_revision_id() -> str:
    """The single revision this one revises, read from its source at runtime —
    never pinned, because ``alembic-heads-pr`` re-points open revisions."""
    parsed = parse_source(_revision_source())
    assert parsed is not None, f"{_REVISION_FILENAME} declares no parseable revision"
    parents = PARENT_REF_RE.findall(parsed[1].partition("#")[0])
    assert len(parents) == 1, f"expected ONE parent, parsed {parents!r}"
    return parents[0]


_PARENT_REVISION_ID = _parent_revision_id()


def test_down_revision_names_a_revision_that_exists_in_the_chain() -> None:
    versions = backend_root() / "alembic" / "versions"
    declared = {
        parsed[0]
        for path in versions.glob("*.py")
        for parsed in [parse_source(path.read_text(encoding="utf-8"))]
        if parsed is not None
    }
    assert _PARENT_REVISION_ID in declared


def test_it_was_hand_authored_and_imports_nothing_from_the_app() -> None:
    source = _revision_source()
    assert "### commands auto generated by Alembic" not in source
    assert "from app" not in source
    assert "import app" not in source


def test_the_model_mirrors_the_migration() -> None:
    table = WorkArtifact.__table__
    for column in _EXPECTED_COLUMNS:
        assert table.c[column].nullable, column
    index = next(i for i in table.indexes if i.name == _INDEX)
    assert [c.name for c in index.columns] == ["kind", "status"]
    where = index.dialect_options["postgresql"]["where"]
    assert str(where) == "archived_at IS NULL"


def _classifier_surface() -> str:
    """The module as coord's migration classifier judges it, as CODE: every
    top-level statement except ``downgrade()``, with docstrings removed (so
    prose cannot trip the keyword scans). ``ast.unparse`` keeps the SQL string
    literals, which are what the scans must read."""
    tree = ast.parse(_revision_source())
    kept: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == "downgrade":
            continue
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant):
            continue  # the module docstring
        if isinstance(node, ast.FunctionDef):
            body = node.body
            if body and isinstance(body[0], ast.Expr):
                if isinstance(body[0].value, ast.Constant):
                    node.body = body[1:] or [ast.Pass()]
        kept.append(node)
    return ast.unparse(ast.Module(body=kept, type_ignores=[]))


def test_the_upgrade_surface_is_what_coords_classifier_admits() -> None:
    surface = _classifier_surface()
    assert "get_bind" not in surface, (
        "coord's classifier rejects executing SQL through op.get_bind()"
    )
    assert "DROP" not in surface.upper(), "no DROP outside downgrade()"
    assert "CREATE INDEX CONCURRENTLY IF NOT EXISTS" in " ".join(surface.split())
    assert "ADD COLUMN IF NOT EXISTS archived_at" in surface


_PG_SKIP = pytest.mark.skipif(
    not can_connect(admin_database_url()),
    reason=(
        "Postgres not reachable at the conftest URL. CI provisions a postgres "
        "service; locally, set QONTINUI_TEST_PG=localhost:<port>."
    ),
)


def _columns(engine: Engine) -> dict[str, tuple[str, str]]:
    with engine.connect() as conn:
        return {
            r.column_name: (r.data_type, r.is_nullable)
            for r in conn.execute(
                text(
                    "SELECT column_name, data_type, is_nullable "
                    "FROM information_schema.columns "
                    "WHERE table_schema = 'agent' AND table_name = 'work_artifacts'"
                )
            )
        }


def _index(engine: Engine) -> tuple[bool, str] | None:
    """``(indisvalid, predicate)`` of the live-row index, or ``None``."""
    with engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT i.indisvalid, pg_get_expr(i.indpred, i.indrelid) "
                "FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid "
                "JOIN pg_namespace n ON n.oid = c.relnamespace "
                "WHERE n.nspname = 'agent' AND c.relname = :name"
            ),
            {"name": _INDEX},
        ).first()
    return None if row is None else (bool(row[0]), str(row[1]))


@_PG_SKIP
def test_upgrade_downgrade_upgrade_round_trip() -> None:
    root = backend_root()
    with ephemeral_database(admin_database_url(), "planlib_archive") as (
        engine,
        db_url,
    ):
        run_alembic(root, db_url, "upgrade", _PARENT_REVISION_ID)
        row_id = uuid.uuid4()
        with engine.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO agent.work_artifacts "
                    "(id, kind, slug, body, content_sha256) "
                    "VALUES (:id, 'plan', :slug, '# plan', 'x')"
                ),
                {"id": row_id, "slug": f"s-{row_id.hex[:8]}"},
            )

        run_alembic(root, db_url, "upgrade", "head")
        columns = _columns(engine)
        for name, data_type in _EXPECTED_COLUMNS.items():
            assert columns.get(name) == (data_type, "YES"), name
        index = _index(engine)
        assert index is not None, "the live-row index was not built"
        assert index[0] is True, "the CONCURRENTLY-built index is INVALID"
        assert index[1] == "(archived_at IS NULL)"
        with engine.connect() as conn:
            live = conn.execute(
                text(
                    "SELECT archived_at IS NULL FROM agent.work_artifacts WHERE id = :id"
                ),
                {"id": row_id},
            ).scalar_one()
        assert live is True, "a pre-existing row must read as live"

        run_alembic(root, db_url, "downgrade", _PARENT_REVISION_ID)
        assert not set(_EXPECTED_COLUMNS) & set(_columns(engine))
        assert _index(engine) is None

        run_alembic(root, db_url, "upgrade", "head")
        assert set(_EXPECTED_COLUMNS) <= set(_columns(engine))
        assert _index(engine) is not None
