"""Guards that let ``/api/v1/operations`` be split into per-domain modules.

Plan ``2026-10-04-web-operations-py-is-one-router-for-every-coord-domain``,
Phase 0. ``app/api/v1/endpoints/operations.py`` is one router for every coord
domain; the plan moves it, a domain at a time, into an ``operations/``
package. Each move must be behaviour-preserving, and these tests are what
makes that checkable:

* ``test_operations_route_table`` — one line per mounted ``/operations``
  route (methods, path, name, response model, status code, schema
  visibility, sorted tags, and the qualnames of every dependency FastAPI
  resolves for it, router-level ones included) must equal the committed
  fixture. Qualnames,
  not module paths, so a move between modules does not change a line while a
  dropped ``Depends`` or a changed response model does.

  Regenerate after an INTENDED route change, and review the diff::

      UPDATE_OPERATIONS_ROUTE_TABLE=1 poetry run pytest tests/test_operations_route_table.py

* ``test_operations_openapi_digest`` — the sha256 of the OpenAPI ``paths``
  subtree for ``/api/v1/operations`` (parameters, request bodies, response
  schemas, summaries, operation ids) TOGETHER WITH every ``components``
  entry reachable from it by following ``$ref`` transitively, serialized
  with ``sort_keys=True``, must equal the committed digest. Path bodies
  mostly say ``$ref: #/components/schemas/X``, so hashing ``paths`` alone
  would miss a field change inside ``X`` or anything ``X`` nests. The route
  table above names a response model; this catches a change inside the
  schema it renders to. Regenerated by the same variable.

  One false alarm to expect: FastAPI qualifies a component name that
  collides across modules, so a new model elsewhere in the app (a
  cloud-control model, say) whose class name equals an operations model's
  renames that model's ``$ref`` and moves this digest with no operations
  change. The remedy is the same regeneration command, after confirming the
  diff is only that rename.

* ``test_operations_shadow_order`` — FastAPI matches in registration order,
  so a literal route (``/memory/list``) must be registered before the
  parameter route that would also match it (``/memory/{name}``). The pairs
  are computed from the live route table, not listed, so a pair added later
  is covered too.

* ``test_operations_package_has_no_init_imports`` — decision D4: once
  ``operations`` is a package, no module under it imports from the package
  ``__init__`` (a partial-init cycle). ``from . import fleet`` where
  ``fleet`` is a submodule on disk imports the sibling, not the ``__init__``,
  and is allowed. Trivially green while it is one file.
"""

from __future__ import annotations

import ast
import hashlib
import json
import os
import re
import types
import typing
from pathlib import Path
from typing import Any

import pytest
from fastapi.routing import APIRoute, APIWebSocketRoute

from tests._ops_patch import ops_submodules

OPS_PREFIX = "/api/v1/operations"
OPS_PACKAGE = "app.api.v1.endpoints.operations"
FIXTURE = Path(__file__).parent / "fixtures" / "operations_route_table.txt"
OPENAPI_FIXTURE = Path(__file__).parent / "fixtures" / "operations_openapi.sha256"
UPDATE_ENV = "UPDATE_OPERATIONS_ROUTE_TABLE"
REGEN_COMMAND = f"{UPDATE_ENV}=1 poetry run pytest tests/test_operations_route_table.py"
BACKEND = Path(__file__).resolve().parent.parent

# A path parameter, with or without a convertor (``{name}``, ``{p:path}``).
_PARAM = re.compile(r"\{[^}]+\}")
# Substituted for every path parameter to make a concrete sample path. It must
# never equal a literal segment (``x`` could), and it must match every
# parameter pattern in use: ``[^/]+`` for a plain ``{name}`` and ``.*`` for
# ``{name:path}``. No ``int``/``float``/``uuid`` convertor is mounted under
# /operations; ``test_operations_sample_token_matches_every_parameter``
# fails if one appears.
_SAMPLE_TOKEN = "\x00sample"


def _ops_routes() -> list[tuple[int, Any]]:
    """``(registration index, route)`` for every mounted /operations route."""
    from app.main import app

    return [
        (index, route)
        for index, route in enumerate(app.routes)
        if isinstance(route, APIRoute | APIWebSocketRoute)
        and (route.path == OPS_PREFIX or route.path.startswith(OPS_PREFIX + "/"))
    ]


def _methods(route: Any) -> list[str]:
    if isinstance(route, APIWebSocketRoute):
        return ["WS"]
    return sorted(route.methods)


def _type_name(value: Any) -> str:
    """A module-independent, address-free rendering of a type annotation."""
    if value is None:
        return "None"
    if value is type(None):
        return "None"
    origin = typing.get_origin(value)
    if origin is not None:
        args = typing.get_args(value)
        if origin in (typing.Union, types.UnionType):
            return " | ".join(_type_name(arg) for arg in args)
        rendered = ", ".join(_type_name(arg) for arg in args)
        return f"{_type_name(origin)}[{rendered}]"
    qualname = getattr(value, "__qualname__", None)
    if isinstance(qualname, str):
        return qualname
    return type(value).__qualname__


def _call_name(call: Any) -> str:
    """Qualname of a dependency callable — never a repr with an address."""
    func = getattr(call, "func", None)
    if func is not None and hasattr(call, "args"):  # functools.partial
        return f"partial({_call_name(func)})"
    qualname = getattr(call, "__qualname__", None)
    if isinstance(qualname, str):
        return qualname
    return f"{type(call).__qualname__}()"


def _dependency_names(dependant: Any) -> list[str]:
    """Every dependency call under ``dependant``, depth-first, in order.

    The endpoint itself (the root call) is excluded; it is the ``name`` column.
    """
    names: list[str] = []
    for sub in dependant.dependencies:
        if sub.call is not None:
            names.append(_call_name(sub.call))
        names.extend(_dependency_names(sub))
    return names


def _route_line(route: Any) -> str:
    if isinstance(route, APIWebSocketRoute):
        response_model = status_code = include_in_schema = "-"
    else:
        response_model = _type_name(route.response_model)
        status_code = str(route.status_code)
        include_in_schema = str(route.include_in_schema)
    dependencies = ", ".join(_dependency_names(route.dependant))
    return " ".join(
        [
            ",".join(_methods(route)),
            route.path,
            route.name,
            response_model,
            status_code,
            include_in_schema,
            f"tags={','.join(sorted(str(tag) for tag in route.tags))}"
            if isinstance(route, APIRoute)
            else "tags=-",
            f"[{dependencies}]",
        ]
    )


def _route_table() -> list[str]:
    return sorted(_route_line(route) for _, route in _ops_routes())


def test_operations_route_table() -> None:
    table = _route_table()
    assert len(table) > 200, f"only {len(table)} /operations routes — app not mounted?"
    for line in table:
        assert not re.search(r"0x[0-9a-fA-F]{6,}", line), (
            f"route-table line carries a memory address, so it is not "
            f"deterministic: {line}"
        )
    rendered = "\n".join(table) + "\n"
    if os.environ.get(UPDATE_ENV) == "1":
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(rendered, encoding="utf-8", newline="\n")
    expected = FIXTURE.read_text(encoding="utf-8").splitlines()
    missing = sorted(set(expected) - set(table))
    added = sorted(set(table) - set(expected))
    assert table == expected, (
        "The mounted /api/v1/operations route table differs from "
        f"{FIXTURE.name}.\n  in the fixture, not served: {missing}\n"
        f"  served, not in the fixture: {added}\n"
        "A behaviour-preserving move must leave this table unchanged. If the "
        f"change is intended, regenerate and review the diff:\n  {REGEN_COMMAND}"
    )


_REF_PREFIX = "#/components/"


def _refs(node: Any) -> set[str]:
    """Every ``$ref`` string anywhere under ``node``."""
    found: set[str] = set()
    if isinstance(node, dict):
        ref = node.get("$ref")
        if isinstance(ref, str):
            found.add(ref)
        for value in node.values():
            found |= _refs(value)
    elif isinstance(node, list):
        for value in node:
            found |= _refs(value)
    return found


def _openapi_subset(openapi: dict[str, Any], prefix: str) -> dict[str, Any]:
    """The ``paths`` under ``prefix`` plus every component they reach.

    ``$ref`` is followed transitively through ``components`` (any section,
    not only ``schemas``), so a field change in a model nested several
    references deep still lands in the subset. A ``$ref`` that does not
    resolve is kept as a ``None`` entry rather than skipped, so a dangling
    reference also moves the digest.
    """
    paths = {
        path: value
        for path, value in openapi.get("paths", {}).items()
        if path == prefix or path.startswith(prefix + "/")
    }
    components = openapi.get("components", {})
    reached: dict[str, dict[str, Any]] = {}
    pending = sorted(_refs(paths))
    seen: set[str] = set()
    while pending:
        ref = pending.pop()
        if ref in seen or not ref.startswith(_REF_PREFIX):
            continue
        seen.add(ref)
        section, _, name = ref[len(_REF_PREFIX) :].partition("/")
        value = components.get(section, {}).get(name)
        reached.setdefault(section, {})[name] = value
        pending.extend(sorted(_refs(value) - seen))
    return {"paths": paths, "components": reached}


def _openapi_digest(openapi: dict[str, Any], prefix: str = OPS_PREFIX) -> str:
    subset = _openapi_subset(openapi, prefix)
    return hashlib.sha256(json.dumps(subset, sort_keys=True).encode()).hexdigest()


def test_operations_openapi_digest() -> None:
    from app.main import app

    openapi = app.openapi()
    subset = _openapi_subset(openapi, OPS_PREFIX)
    assert len(subset["paths"]) > 100, (
        f"only {len(subset['paths'])} /operations OpenAPI paths"
    )
    assert len(subset["components"].get("schemas", {})) > 20, (
        "the /operations paths reach almost no component schema — the $ref "
        "walk went vacuous"
    )
    digest = _openapi_digest(openapi)
    if os.environ.get(UPDATE_ENV) == "1":
        OPENAPI_FIXTURE.write_text(digest + "\n", encoding="utf-8", newline="\n")
    expected = OPENAPI_FIXTURE.read_text(encoding="utf-8").strip()
    assert digest == expected, (
        "The /api/v1/operations OpenAPI paths, or a component schema they "
        f"reference, differ from {OPENAPI_FIXTURE.name}. A behaviour-preserving "
        "move must leave the served schema unchanged. (A model elsewhere whose "
        "class name collides with an operations model renames its $ref, which "
        "also moves this digest.) If the change is intended, regenerate and "
        f"review the route-table diff that comes with it:\n  {REGEN_COMMAND}"
    )


def _tiny_openapi(inner_field_type: type) -> dict[str, Any]:
    """OpenAPI of a one-route app whose response nests ``Inner`` two refs deep,
    plus an unrelated route outside the prefix."""
    from fastapi import FastAPI
    from pydantic import BaseModel, create_model

    inner = create_model("Inner", value=(inner_field_type, ...))
    middle = create_model("Middle", inner=(inner, ...))
    outer = create_model("Outer", middle=(middle, ...))

    class Unreached(BaseModel):
        other: int

    tiny = FastAPI()
    tiny.add_api_route(OPS_PREFIX + "/x", lambda: None, response_model=outer)
    tiny.add_api_route("/elsewhere", lambda: None, response_model=Unreached)
    return tiny.openapi()


def test_the_openapi_digest_sees_a_field_change_in_a_referenced_model() -> None:
    as_int = _tiny_openapi(int)
    as_str = _tiny_openapi(str)
    # The paths subtree alone is identical: only the $ref target changed.
    assert as_int["paths"][OPS_PREFIX + "/x"] == as_str["paths"][OPS_PREFIX + "/x"]
    reached = _openapi_subset(as_int, OPS_PREFIX)["components"]["schemas"]
    assert set(reached) == {"Outer", "Middle", "Inner"}
    assert _openapi_digest(as_int) != _openapi_digest(as_str)
    assert _openapi_digest(as_int) == _openapi_digest(_tiny_openapi(int))


def _sample_path(path: str) -> str:
    return _PARAM.sub(_SAMPLE_TOKEN, path)


def _shadow_pairs(
    routes: list[tuple[int, Any]],
) -> list[tuple[tuple[int, Any], tuple[int, Any]]]:
    """``[(literal, shadow)]``: same-method routes where ``shadow``'s pattern
    matches a concrete sample of ``literal``'s path but not the reverse — so
    ``literal`` is reachable only if it is registered first."""
    pairs = []
    for literal in routes:
        sample = _sample_path(literal[1].path)
        for shadow in routes:
            if shadow is literal or shadow[1].path == literal[1].path:
                continue
            if not set(_methods(shadow[1])) & set(_methods(literal[1])):
                continue
            if not shadow[1].path_regex.match(sample):
                continue
            if literal[1].path_regex.match(_sample_path(shadow[1].path)):
                # Each matches the other's sample: neither is more specific,
                # so registration order cannot make both reachable. Not a
                # shadow pair; report it as an ambiguity instead.
                raise AssertionError(
                    f"ambiguous /operations routes: {literal[1].path} and "
                    f"{shadow[1].path} each match the other"
                )
            pairs.append((literal, shadow))
    return pairs


def test_operations_sample_token_matches_every_parameter() -> None:
    for _, route in _ops_routes():
        if not _PARAM.search(route.path):
            continue
        assert route.path_regex.match(_sample_path(route.path)), (
            f"the sample token does not match {route.path}'s parameter pattern "
            "(a new convertor?) — the shadow-order check would go blind to it"
        )


def test_operations_shadow_order() -> None:
    pairs = _shadow_pairs(_ops_routes())
    print(f"order-dependent /operations route pairs: {len(pairs)}")
    assert pairs, (
        "no order-dependent /operations pair found — the computation went "
        "vacuous (there were 9 at plan authoring)"
    )
    wrong = [
        f"{','.join(_methods(lit))} {lit.path} (#{li}) is registered after "
        f"{shadow.path} (#{si}), which matches it first"
        for (li, lit), (si, shadow) in pairs
        if li > si
    ]
    assert not wrong, "Shadowed /operations routes:\n" + "\n".join(wrong)


def _resolve_import(module: str | None, level: int, package: str) -> str:
    """Absolute name an ``ImportFrom`` resolves to, from inside ``package``."""
    if level == 0:
        return module or ""
    parts = package.split(".")
    if level > len(parts):
        return ""  # beyond the top-level package: not ours
    base = ".".join(parts[: len(parts) - (level - 1)])
    return f"{base}.{module}" if module else base


def _imports_package_init(
    source: str,
    package: str = OPS_PACKAGE,
    submodules: frozenset[str] | None = None,
) -> list[int]:
    """Lines importing the operations package ``__init__`` itself.

    ``package`` is the ``__package__`` of the module ``source`` belongs to,
    so relative imports resolve: in ``operations/fleet.py`` (package
    ``operations``) ``from . import x`` names the ``__init__``; in
    ``operations/a/b.py`` (package ``operations.a``) ``from .. import x``
    does. A submodule import (``from .fleet import x``,
    ``import ...operations.fleet``) is a sibling, and allowed — and so is
    ``from . import fleet`` when ``fleet`` is in ``submodules`` (dotted
    names; default: what is on disk), since that imports the submodule
    rather than reading a name off the ``__init__``. A line naming any
    non-submodule (or ``*``) is flagged.
    """
    if submodules is None:
        submodules = ops_submodules(BACKEND)
    lines = []
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom):
            if _resolve_import(node.module, node.level, package) == OPS_PACKAGE and any(
                f"{OPS_PACKAGE}.{alias.name}" not in submodules for alias in node.names
            ):
                lines.append(node.lineno)
        elif isinstance(node, ast.Import):
            if any(alias.name == OPS_PACKAGE for alias in node.names):
                lines.append(node.lineno)
    return lines


def _module_package(path: Path, package_dir: Path) -> str:
    """``__package__`` of the module at ``path`` under the operations package."""
    return ".".join([OPS_PACKAGE, *path.parent.relative_to(package_dir).parts])


# A ``fleet.py`` module and a ``sub/`` subpackage under ``operations/``.
_FAKE_SUBMODULES = frozenset({f"{OPS_PACKAGE}.fleet", f"{OPS_PACKAGE}.sub"})


def test_ops_submodules_reads_files_and_subpackages(tmp_path: Path) -> None:
    package_dir = tmp_path / Path(*OPS_PACKAGE.split("."))
    (package_dir / "sub").mkdir(parents=True)
    for rel in ("__init__.py", "fleet.py", "sub/__init__.py", "sub/leaf.py"):
        (package_dir / rel).write_text("", encoding="utf-8")
    assert ops_submodules(tmp_path) == {
        f"{OPS_PACKAGE}.fleet",
        f"{OPS_PACKAGE}.sub",
        f"{OPS_PACKAGE}.sub.leaf",
    }
    assert ops_submodules(tmp_path / "nowhere") == frozenset()


@pytest.mark.parametrize(
    ("source", "package"),
    [
        ("from app.api.v1.endpoints.operations import router", OPS_PACKAGE),
        ("from . import router", OPS_PACKAGE),
        ("from .. import router", OPS_PACKAGE + ".sub"),
        ("from ...operations import router", OPS_PACKAGE + ".sub"),
        ("import app.api.v1.endpoints.operations", OPS_PACKAGE),
        ("import app.api.v1.endpoints.operations as ops", OPS_PACKAGE),
        # Not a submodule, so read off the __init__ — even beside one that is.
        ("from . import router as r", OPS_PACKAGE),
        ("from .. import fleet, router", OPS_PACKAGE + ".sub"),
        ("from app.api.v1.endpoints.operations import fleet, router", OPS_PACKAGE),
        ("from . import *", OPS_PACKAGE),
    ],
)
def test_the_init_import_scan_flags_every_spelling(source: str, package: str) -> None:
    assert _imports_package_init(source, package, _FAKE_SUBMODULES) == [1], source


@pytest.mark.parametrize(
    ("source", "package"),
    [
        ("from .fleet import x", OPS_PACKAGE),
        ("from app.api.v1.endpoints.operations.fleet import x", OPS_PACKAGE),
        ("import app.api.v1.endpoints.operations.fleet", OPS_PACKAGE),
        ("from . import x", OPS_PACKAGE + ".sub"),
        ("from ..fleet import x", OPS_PACKAGE + ".sub"),
        ("from app.api import coord_proxy", OPS_PACKAGE),
        # Sibling submodules (a .py file, a subpackage) imported by name.
        ("from . import fleet", OPS_PACKAGE),
        ("from . import fleet as f, sub", OPS_PACKAGE),
        ("from .. import fleet", OPS_PACKAGE + ".sub"),
        ("from app.api.v1.endpoints.operations import sub", OPS_PACKAGE),
    ],
)
def test_the_init_import_scan_allows_sibling_imports(source: str, package: str) -> None:
    assert _imports_package_init(source, package, _FAKE_SUBMODULES) == [], source


def test_operations_package_has_no_init_imports() -> None:
    package_dir = BACKEND / Path(*OPS_PACKAGE.split("."))
    assert package_dir.is_dir() or package_dir.with_suffix(".py").is_file(), (
        f"neither {package_dir} nor its .py exists — the guard lost its target"
    )
    if not package_dir.is_dir():
        return  # still one module: no submodule can import its __init__
    offenders = {
        str(path.relative_to(BACKEND)): lines
        for path in sorted(package_dir.rglob("*.py"))
        # The package's own __init__ imports its submodules; not a cycle.
        if path != package_dir / "__init__.py"
        and (
            lines := _imports_package_init(
                path.read_text(encoding="utf-8"), _module_package(path, package_dir)
            )
        )
    }
    assert not offenders, (
        f"modules under {OPS_PACKAGE} import from the package __init__ "
        f"(D4: import siblings or app.api.coord_proxy instead): {offenders}"
    )
