"""Round-trip test for ``gatecorr_01_coord_gate_corrections``.

Plan ``2026-09-21-a-cleared-gate-is-uncorrectable-and-every-repair-mints-another-false-green-row``,
Phase 7. Nothing in qontinui-web reads or writes ``coord.gate_corrections`` —
coord does — so the API suite cannot notice a shape that disagrees with what
coord's later phase will INSERT. What only the alembic-built table can show:

* the table and its ``(tenant_id, gate_id)`` index land in ``coord``;
* every column arrives with the type and nullability the correction verb needs
  — in particular that the three attribution/replacement columns are NULLABLE
  (a correction with no replacement and no resolvable author is a real case)
  while ``gate_id``/``tenant_id``/``relation``/``reason`` are NOT;
* ``correction_id`` defaults to ``gen_random_uuid()``, so coord inserts without
  minting an id;
* the ``relation`` CHECK admits exactly the three-word vocabulary and refuses a
  fourth word — a typo in a writer must be an ``IntegrityError`` here rather
  than a word the console silently paints;
* ``gate_id`` carries **no foreign key**, deliberately: an annotation about a
  gate must not couple its lifetime to ``coord.gates``;
* N corrections per gate are accepted (no unique constraint on ``gate_id``);
* head -> ``downgrade`` -> head leaves no residue.

The one property this file CANNOT test is the one the revision's docstring
flags: append-only is not expressible in this DDL, so a direct ``UPDATE``
succeeds. That property is enforced coord-side by the source-scanning test in
the phase that adds ``coord_correct_gate``. This test asserts the docstring
SAYS so, which is the only part of it that lives in this repo.

Substrate is ``tests/_alembic_harness``. ⚠️ A skip proves nothing — point it at
a live instance with ``QONTINUI_TEST_PG=localhost:<port>``.
"""

from __future__ import annotations

import re
import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError

from tests._alembic_harness import (
    admin_database_url,
    backend_root,
    can_connect,
    ephemeral_database,
    index_exists,
    run_alembic,
    table_exists,
)

_REVISION_ID = "gatecorr_01_coord_gate_corrections"
_REVISION_FILENAME = "gatecorr_01_coord_gate_corrections.py"

_SCHEMA = "coord"
_TABLE = "gate_corrections"
_INDEX = "idx_gate_corrections_tenant_gate"

#: ``column -> (information_schema data_type, is_nullable)``.
_EXPECTED_COLUMNS = {
    "correction_id": ("uuid", "NO"),
    "gate_id": ("uuid", "NO"),
    "tenant_id": ("uuid", "NO"),
    "relation": ("text", "NO"),
    "reason": ("text", "NO"),
    "replacement_gate_id": ("uuid", "YES"),
    "corrected_by_device_id": ("uuid", "YES"),
    "corrected_by_agent_id": ("uuid", "YES"),
    "created_at": ("timestamp with time zone", "NO"),
}

#: The closed vocabulary the CHECK pins. Phase 9 reuses the latter two.
_RELATIONS = ("mispredicated", "reopened_from", "repointed_from")


def _revision_source() -> str:
    return (backend_root() / "alembic" / "versions" / _REVISION_FILENAME).read_text(
        encoding="utf-8"
    )


def _parent_revision_id() -> str:
    """Parse this revision's own ``down_revision`` at runtime.

    Never hardcode the parent. ``alembic-heads-pr`` serialises alembic PRs by
    construction, so any revision that lands ahead of this one re-forks the
    chain and ``down_revision`` is re-pointed at the new head. A pinned
    constant does not merely rot: it makes this test upgrade to a revision that
    is no longer this one's parent, so the "clean database" it then asserts
    against is the wrong one.
    """
    match = re.search(
        r'^down_revision:.*=\s*"([^"]+)"', _revision_source(), re.MULTILINE
    )
    assert match, f"{_REVISION_FILENAME} must declare a single-string down_revision"
    return match.group(1)


_PARENT_REVISION_ID = _parent_revision_id()

_TENANT = uuid.UUID("2f2b1f6a-6d4e-4a2f-9a05-6c9a7c3d1e88")


# --------------------------------------------------------------------------
# Offline — these run with no database at all.
# --------------------------------------------------------------------------


def test_it_was_hand_authored_not_autogenerated() -> None:
    """``coord.*`` is alembic-sole-authored and autogenerate is never run
    against it (no SQLAlchemy models back the schema, so it emits spurious
    drops)."""
    assert "### commands auto generated by Alembic" not in _revision_source()


def test_it_imports_nothing_from_the_app() -> None:
    """No revision in this tree imports ``app``; a migration must not freeze an
    application constant into the revision history."""
    source = _revision_source()
    assert "from app" not in source
    assert "import app" not in source


def test_the_docstring_says_append_only_is_not_a_database_guarantee() -> None:
    """The revision's own docstring is the only place a reader of THIS repo
    learns that the append-only property is enforced coord-side. If that
    sentence is ever edited away, the next reader assumes a guarantee Postgres
    is not making here."""
    source = _revision_source()
    assert "APPEND-ONLY IS NOT A DATABASE GUARANTEE" in source
    assert "source-scanning test" in source


def test_the_upgrade_path_drops_nothing() -> None:
    """``upgrade()`` is purely additive; every DROP belongs to ``downgrade()``.
    This is what keeps the coord column-drop guard silent, and it is a property
    of the revision rather than of the guard's scan rules."""
    source = _revision_source()
    upgrade_src = source[
        source.index("def upgrade()") : source.index("def downgrade()")
    ]
    assert "DROP" not in upgrade_src.upper()


def test_downgrade_is_not_a_no_op() -> None:
    """``migration-reversal.yml``'s required *Migration Reversal Gate* exercises
    upgrade -> ``downgrade -1`` -> upgrade; a no-op downgrade fails it."""
    source = _revision_source()
    downgrade_src = source[source.index("def downgrade()") :]
    assert "DROP TABLE IF EXISTS coord.gate_corrections" in downgrade_src
    assert f"DROP INDEX IF EXISTS coord.{_INDEX}" in downgrade_src


# --------------------------------------------------------------------------
# Against a real Postgres.
# --------------------------------------------------------------------------

_PG_SKIP = pytest.mark.skipif(
    not can_connect(admin_database_url()),
    reason=(
        "Postgres not reachable at the conftest URL. CI provisions a postgres "
        "service; locally, set QONTINUI_TEST_PG=localhost:<port>."
    ),
)


def _columns(engine: Engine) -> dict[str, tuple[str, str]]:
    with engine.connect() as conn:
        return {
            r.column_name: (r.data_type, r.is_nullable)
            for r in conn.execute(
                text(
                    "SELECT column_name, data_type, is_nullable "
                    "FROM information_schema.columns "
                    "WHERE table_schema = :schema AND table_name = :table"
                ),
                {"schema": _SCHEMA, "table": _TABLE},
            )
        }


def _foreign_keys(engine: Engine) -> set[str]:
    with engine.connect() as conn:
        return {
            r[0]
            for r in conn.execute(
                text(
                    "SELECT conname FROM pg_constraint "
                    "WHERE conrelid = 'coord.gate_corrections'::regclass "
                    "AND contype = 'f'"
                )
            )
        }


def _insert(engine: Engine, **overrides: object) -> uuid.UUID:
    """Insert one correction the way coord's verb will, and return its id."""
    row = {
        "gate_id": uuid.uuid4(),
        "tenant_id": _TENANT,
        "relation": "mispredicated",
        "reason": "predicate asked migration_at_head; the table is absent",
        "replacement_gate_id": None,
        "corrected_by_device_id": None,
        "corrected_by_agent_id": None,
    }
    row.update(overrides)
    with engine.begin() as conn:
        return conn.execute(  # type: ignore[return-value]
            text(
                "INSERT INTO coord.gate_corrections "
                "(gate_id, tenant_id, relation, reason, replacement_gate_id, "
                " corrected_by_device_id, corrected_by_agent_id) "
                "VALUES (:gate_id, :tenant_id, :relation, :reason, "
                "        :replacement_gate_id, :corrected_by_device_id, "
                "        :corrected_by_agent_id) "
                "RETURNING correction_id"
            ),
            row,
        ).scalar_one()


@_PG_SKIP
def test_upgrade_write_downgrade_upgrade_round_trip() -> None:
    root = backend_root()
    with ephemeral_database(admin_database_url(), "gatecorr") as (engine, db_url):
        # The chain up to, but not including, this revision.
        run_alembic(root, db_url, "upgrade", _PARENT_REVISION_ID)
        assert not table_exists(engine, _SCHEMA, _TABLE), (
            "the parent must not already carry this table"
        )

        run_alembic(root, db_url, "upgrade", "head")
        assert table_exists(engine, _SCHEMA, _TABLE)
        assert index_exists(engine, _INDEX, schema=_SCHEMA)

        columns = _columns(engine)
        assert columns == _EXPECTED_COLUMNS, (
            "column shape drifted from what coord's correction verb inserts"
        )

        assert _foreign_keys(engine) == set(), (
            "gate_id is deliberately FK-free: an annotation about a gate must "
            "not couple its lifetime to coord.gates"
        )

        # The default mints the id, so coord inserts without one.
        first = _insert(engine)
        assert isinstance(first, uuid.UUID)

        # N corrections per gate — no unique constraint stands in the way of a
        # correction being itself corrected.
        gate = uuid.uuid4()
        replacement = uuid.uuid4()
        _insert(engine, gate_id=gate, relation="reopened_from")
        _insert(
            engine,
            gate_id=gate,
            relation="repointed_from",
            replacement_gate_id=replacement,
            corrected_by_device_id=uuid.uuid4(),
            corrected_by_agent_id=uuid.uuid4(),
        )
        with engine.connect() as conn:
            count = conn.execute(
                text(
                    "SELECT count(*) FROM coord.gate_corrections "
                    "WHERE tenant_id = :t AND gate_id = :g"
                ),
                {"t": _TENANT, "g": gate},
            ).scalar_one()
        assert count == 2

        # created_at is filled by the insert clock, not by the caller.
        with engine.connect() as conn:
            created = conn.execute(
                text(
                    "SELECT created_at FROM coord.gate_corrections "
                    "WHERE correction_id = :id"
                ),
                {"id": first},
            ).scalar_one()
        assert created is not None

        # head -> parent -> head leaves no residue and re-creates cleanly.
        run_alembic(root, db_url, "downgrade", "-1")
        assert not table_exists(engine, _SCHEMA, _TABLE)
        assert not index_exists(engine, _INDEX, schema=_SCHEMA)

        run_alembic(root, db_url, "upgrade", "head")
        assert table_exists(engine, _SCHEMA, _TABLE)
        assert index_exists(engine, _INDEX, schema=_SCHEMA)


@_PG_SKIP
@pytest.mark.parametrize("relation", _RELATIONS)
def test_the_check_admits_every_word_in_the_vocabulary(relation: str) -> None:
    root = backend_root()
    with ephemeral_database(admin_database_url(), "gatecorr_ok") as (engine, db_url):
        run_alembic(root, db_url, "upgrade", "head")
        assert _insert(engine, relation=relation) is not None


@_PG_SKIP
def test_the_check_refuses_a_word_outside_the_vocabulary() -> None:
    """A typo in a writer must be an IntegrityError here, not a word the
    console silently paints."""
    root = backend_root()
    with ephemeral_database(admin_database_url(), "gatecorr_bad") as (engine, db_url):
        run_alembic(root, db_url, "upgrade", "head")
        with pytest.raises(IntegrityError):
            _insert(engine, relation="superseded_by")
