"""Round-trip test for ``plan_library_07_plan_difficulty``.

Plan ``2026-09-18-plan-library-difficulty-field``. The API suite builds its
schema from the MODEL, so it cannot notice a migration that disagrees with it.
What only the alembic-built table can show:

* the six columns land NULLABLE with the model's types — every row that exists
  at deploy time is unrated, and NULL is how it says so;
* the CHECKs admit the three levels (and NULL) and refuse anything else, so a
  typo in a writer is an IntegrityError here rather than a console that paints
  an unknown word;
* the re-rater's Core UPDATE runs against the migrated table and fills a
  pre-existing plan row without moving its ``updated_at``;
* head → downgrade → head leaves no residue.

Substrate is ``tests/_alembic_harness``. ⚠️ A skip proves nothing — point it at
a live instance with ``QONTINUI_TEST_PG=localhost:<port>``.
"""

from __future__ import annotations

import json
import sys
import uuid

import pytest
from sqlalchemy import text
from sqlalchemy.engine import Engine
from sqlalchemy.exc import IntegrityError

from app.crud.work_artifact import DIFFICULTY_COLUMNS, difficulty_values
from tests._alembic_harness import (
    admin_database_url,
    backend_root,
    can_connect,
    ephemeral_database,
    run_alembic,
)

# The head gate's own parser — see the 06 revision's test for why.
_SCRIPTS_CI = backend_root().parent / "scripts" / "ci"
sys.path.insert(0, str(_SCRIPTS_CI))

from _alembic_graph import PARENT_REF_RE, parse_source  # noqa: E402

_REVISION_ID = "plan_library_07_plan_difficulty"
_REVISION_FILENAME = "plan_library_07_plan_difficulty.py"

#: ``column -> information_schema.columns.data_type``.
_EXPECTED_COLUMNS = {
    "difficulty": "text",
    "difficulty_conceptual": "text",
    "difficulty_implementation": "text",
    "difficulty_source": "text",
    "difficulty_rubric_version": "integer",
    "difficulty_signals": "jsonb",
}

_CHECK_NAMES = (
    "ck_work_artifacts_difficulty",
    "ck_work_artifacts_difficulty_conceptual",
    "ck_work_artifacts_difficulty_implementation",
    "ck_work_artifacts_difficulty_source",
)


def _revision_source() -> str:
    return (backend_root() / "alembic" / "versions" / _REVISION_FILENAME).read_text(
        encoding="utf-8"
    )


def _parent_revision_id() -> str:
    """The single revision this one revises, read from its source at runtime —
    never pinned, because ``alembic-heads-pr`` re-points open revisions."""
    parsed = parse_source(_revision_source())
    assert parsed is not None, f"{_REVISION_FILENAME} declares no parseable revision"
    parents = PARENT_REF_RE.findall(parsed[1].partition("#")[0])
    assert len(parents) == 1, f"expected ONE parent, parsed {parents!r}"
    return parents[0]


_PARENT_REVISION_ID = _parent_revision_id()


def test_down_revision_names_a_revision_that_exists_in_the_chain() -> None:
    versions = backend_root() / "alembic" / "versions"
    declared = {
        parsed[0]
        for path in versions.glob("*.py")
        for parsed in [parse_source(path.read_text(encoding="utf-8"))]
        if parsed is not None
    }
    assert _PARENT_REVISION_ID in declared


def test_the_revision_id_is_unique_in_the_chain() -> None:
    versions = backend_root() / "alembic" / "versions"
    same_id = [
        path.name
        for path in versions.glob("*.py")
        for parsed in [parse_source(path.read_text(encoding="utf-8"))]
        if parsed is not None and parsed[0] == _REVISION_ID
    ]
    assert same_id == [_REVISION_FILENAME]


def test_it_was_hand_authored_not_autogenerated() -> None:
    assert "### commands auto generated by Alembic" not in _revision_source()


def test_it_imports_nothing_from_the_app() -> None:
    """No revision in this tree imports ``app``; this one must not freeze the
    rubric into the migration history either."""
    source = _revision_source()
    assert "from app" not in source
    assert "import app" not in source


def test_the_static_upgrade_sql_spells_every_column_in_columns() -> None:
    """``upgrade()`` spells its DDL as plain literals (coord's classifier rejects
    f-strings); ``_COLUMNS`` is the same DDL as data. Keep them in step."""
    import importlib.util

    path = backend_root() / "alembic" / "versions" / _REVISION_FILENAME
    spec = importlib.util.spec_from_file_location("_pl07", path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    source = _revision_source()
    upgrade_src = source[
        source.index("def upgrade()") : source.index("def downgrade()")
    ]
    flat = " ".join(upgrade_src.replace('"\n', " ").split())
    assert 'f"' not in upgrade_src, "upgrade() must use plain string literals"
    for column, column_type, check_name, check in module._COLUMNS:
        assert f"ADD COLUMN IF NOT EXISTS {column} {column_type}" in flat.replace(
            '" "', ""
        ).replace('"', ""), column
        if check_name:
            assert f"CONSTRAINT {check_name} CHECK ({check})" in flat.replace(
                '" "', ""
            ).replace('"', ""), check_name


_PG_SKIP = pytest.mark.skipif(
    not can_connect(admin_database_url()),
    reason=(
        "Postgres not reachable at the conftest URL. CI provisions a postgres "
        "service; locally, set QONTINUI_TEST_PG=localhost:<port>."
    ),
)


def _columns(engine: Engine) -> dict[str, tuple[str, str]]:
    with engine.connect() as conn:
        return {
            r.column_name: (r.data_type, r.is_nullable)
            for r in conn.execute(
                text(
                    "SELECT column_name, data_type, is_nullable "
                    "FROM information_schema.columns "
                    "WHERE table_schema = 'agent' AND table_name = 'work_artifacts'"
                )
            )
        }


def _checks(engine: Engine) -> set[str]:
    with engine.connect() as conn:
        return {
            r[0]
            for r in conn.execute(
                text(
                    "SELECT conname FROM pg_constraint "
                    "WHERE conrelid = 'agent.work_artifacts'::regclass AND contype = 'c'"
                )
            )
        }


def _insert_plan(engine: Engine, *, body: str) -> uuid.UUID:
    row_id = uuid.uuid4()
    with engine.begin() as conn:
        conn.execute(
            text(
                "INSERT INTO agent.work_artifacts "
                "(id, kind, slug, body, content_sha256, updated_at) "
                "VALUES (:id, 'plan', :slug, :body, 'x', "
                "        '2026-01-01T00:00:00+00:00')"
            ),
            {"id": row_id, "slug": f"s-{row_id.hex[:8]}", "body": body},
        )
    return row_id


@_PG_SKIP
def test_upgrade_rate_downgrade_upgrade_round_trip() -> None:
    root = backend_root()
    with ephemeral_database(admin_database_url(), "planlib_difficulty") as (
        engine,
        db_url,
    ):
        # A plan that exists BEFORE the columns do — the whole corpus at deploy.
        run_alembic(root, db_url, "upgrade", _PARENT_REVISION_ID)
        row_id = _insert_plan(engine, body="# plan\n\n**Difficulty:** high\n")

        run_alembic(root, db_url, "upgrade", "head")
        columns = _columns(engine)
        for name, data_type in _EXPECTED_COLUMNS.items():
            assert columns.get(name) == (data_type, "YES"), (
                f"{name} must be {data_type} and NULLABLE — NULL is UNRATED"
            )
        assert set(_CHECK_NAMES) <= _checks(engine)

        with engine.connect() as conn:
            unrated = conn.execute(
                text(
                    "SELECT difficulty, difficulty_signals IS NULL "
                    "FROM agent.work_artifacts WHERE id = :id"
                ),
                {"id": row_id},
            ).one()
        assert tuple(unrated) == (None, True), "the migration backfills nothing"

        # The re-rater's write, against the migrated table: every column the
        # crud fills, and ``updated_at`` assigned to itself.
        values = difficulty_values("plan", "# plan\n\n**Difficulty:** high\n")
        assert set(values) == set(DIFFICULTY_COLUMNS)
        with engine.begin() as conn:
            conn.execute(
                text(
                    "UPDATE agent.work_artifacts SET "
                    "difficulty = :difficulty, "
                    "difficulty_conceptual = :difficulty_conceptual, "
                    "difficulty_implementation = :difficulty_implementation, "
                    "difficulty_source = :difficulty_source, "
                    "difficulty_rubric_version = :difficulty_rubric_version, "
                    "difficulty_signals = CAST(:signals AS JSONB), "
                    "updated_at = updated_at "
                    "WHERE id = :id"
                ),
                {
                    **{k: v for k, v in values.items() if k != "difficulty_signals"},
                    "signals": json.dumps(values["difficulty_signals"]),
                    "id": row_id,
                },
            )
        with engine.connect() as conn:
            rated = conn.execute(
                text(
                    "SELECT difficulty, difficulty_source, updated_at::text "
                    "FROM agent.work_artifacts WHERE id = :id"
                ),
                {"id": row_id},
            ).one()
        assert rated[0] == "high"
        assert rated[1] == "declared"
        assert rated[2].startswith("2026-01-01")

        # The CHECKs refuse a word outside the vocabulary.
        for column, bad in (
            ("difficulty", "extreme"),
            ("difficulty_conceptual", "HIGH"),
            ("difficulty_implementation", ""),
            ("difficulty_source", "guessed"),
        ):
            with pytest.raises(IntegrityError), engine.begin() as conn:
                conn.execute(
                    text(
                        f"UPDATE agent.work_artifacts SET {column} = :v WHERE id = :id"
                    ),
                    {"v": bad, "id": row_id},
                )

        # Round trip.
        run_alembic(root, db_url, "downgrade", _PARENT_REVISION_ID)
        columns = _columns(engine)
        assert not set(_EXPECTED_COLUMNS) & set(columns), "downgrade left a column"
        assert not set(_CHECK_NAMES) & _checks(engine), "downgrade left a CHECK"

        run_alembic(root, db_url, "upgrade", "head")
        assert set(_EXPECTED_COLUMNS) <= set(_columns(engine))
        assert set(_CHECK_NAMES) <= _checks(engine)
