"""Round-trip + upsert test for ``plan_library_06_scan_root_slug_census``.

Phase 1 (web half) of
``2026-09-15-captured-vs-authored-coverage-is-a-set-difference``.

The API suite runs against a ``create_all`` schema built from the MODEL, so it
cannot notice a migration that disagrees with it. What would bite only in
production here is the census resolution: the upsert compares an incoming
digest with the STORED one and calls ``jsonb_set`` on the stored census, so a
column that is TEXT rather than JSONB, or missing altogether, is an error on the
first device to report a census and nowhere else. The walk below therefore runs
the crud's EXACT statement (:func:`app.crud.plan_scan_root.upsert_statement`)
against the alembic-built table, through both directions of the withheld-set
rule.

Also asserted: the six columns land nullable and with the right types, the
table's constraints are UNCHANGED (this revision adds none), and
head → downgrade → head leaves no residue.

Substrate is ``tests/_alembic_harness``. ⚠️ A skip proves nothing — point it at
a live instance with ``QONTINUI_TEST_PG=localhost:<port>`` when 5432 is not the
one accepting the test credentials.
"""

from __future__ import annotations

import re
import uuid
from datetime import UTC, datetime, timedelta

import pytest
from sqlalchemy import text
from sqlalchemy.engine import Engine

from app.crud.plan_scan_root import upsert_statement
from app.schemas.plan_library_scan_roots import slug_census_digest
from tests._alembic_harness import (
    admin_database_url,
    backend_root,
    can_connect,
    ephemeral_database,
    run_alembic,
)

_REVISION_ID = "plan_library_06_scan_root_slug_census"
_PARENT_REVISION_ID = "coord_repo_branches_touched_files_authoritative_01"
_REVISION_FILENAME = "plan_library_06_scan_root_slug_census.py"
_TABLE = "plan_scan_root_observations"

#: ``column -> information_schema.columns.data_type``.
_EXPECTED_COLUMNS = {
    "ref_census": "jsonb",
    "ref_census_digest": "text",
    "work_tree_census": "jsonb",
    "work_tree_census_digest": "text",
    "census_ref_sha": "text",
    "census_observed_at": "timestamp with time zone",
}

_REF_STEMS = ["2026-09-01-alpha", "2026-09-02-beta", "2026-09-03-gamma"]
_MOVED_STEMS = [*_REF_STEMS, "2026-09-04-delta"]


def _revision_source() -> str:
    return (backend_root() / "alembic" / "versions" / _REVISION_FILENAME).read_text(
        encoding="utf-8"
    )


# ---------------------------------------------------------------------------
# Guards — no database, so these never skip.
# ---------------------------------------------------------------------------


def test_down_revision_pins_the_head_it_was_authored_against() -> None:
    match = re.search(
        r'down_revision[^=]*=\s*\(?\s*["\'](?P<parent>[^"\']+)["\']',
        _revision_source(),
    )
    assert match is not None
    assert match.group("parent") == _PARENT_REVISION_ID


def test_the_revision_id_is_unique_in_the_chain() -> None:
    versions = backend_root() / "alembic" / "versions"
    same_id = [
        path.name
        for path in versions.glob("*.py")
        if re.search(
            rf'^revision[^=]*=\s*["\']{re.escape(_REVISION_ID)}["\']',
            path.read_text(encoding="utf-8"),
            re.MULTILINE,
        )
    ]
    assert same_id == [_REVISION_FILENAME], (
        f"revision id {_REVISION_ID!r} is claimed by {same_id}"
    )


def test_it_was_hand_authored_not_autogenerated() -> None:
    """``alembic revision --autogenerate`` is never run against this chain
    (served policy ``production-and-cost`` ``alembic-sole-authorship``); its
    output leaves these markers."""
    source = _revision_source()
    assert "### commands auto generated by Alembic" not in source


# ---------------------------------------------------------------------------
# The database walk.
# ---------------------------------------------------------------------------

_PG_SKIP = pytest.mark.skipif(
    not can_connect(admin_database_url()),
    reason=(
        "Postgres not reachable at the conftest URL. CI provisions a "
        "postgres service; locally, set QONTINUI_TEST_PG=localhost:<port> "
        "before running this test."
    ),
)


def _census(source: str, slugs: list[str] | None, *, digest_over: list[str], **over):
    body = {
        "source": source,
        "ref_sha": "a" * 40 if source == "ref" else None,
        "count": len(digest_over),
        "digest": slug_census_digest(digest_over),
        "slugs": sorted(slugs) if slugs is not None else None,
        "truncated": False,
    }
    body.update(over)
    return body


def _reading(**overrides: object) -> dict[str, object]:
    body: dict[str, object] = {
        "state": "measured",
        "plans_dir": "/p/plans",
        "repo_root": "/p",
        "source_repo": "p/plans",
        "default_ref": "origin/main",
        "ref_sha": "a" * 40,
        "head_sha": "b" * 40,
        "behind": 254,
        "ahead": 0,
        "ref_age_secs": 220,
        "counts_are_floors": False,
        "detail": None,
        "observed_at": datetime.now(UTC),
        "censuses": [],
    }
    body.update(overrides)
    return body


def _upsert(
    engine: Engine,
    *,
    org_id: uuid.UUID | None,
    device_id: uuid.UUID,
    **fields: object,
) -> bool:
    stmt = upsert_statement(
        org_id=org_id,
        device_id=device_id,
        fields=_reading(**fields),
        received_at=datetime.now(UTC),
    )
    with engine.begin() as conn:
        _row_id, inserted, _applied = conn.execute(stmt).one()
    return bool(inserted)


def _census_row(engine: Engine, device_id: uuid.UUID) -> dict[str, object]:
    with engine.connect() as conn:
        row = conn.execute(
            text(
                "SELECT ref_census, ref_census_digest, work_tree_census, "
                "work_tree_census_digest, census_ref_sha, census_observed_at "
                f"FROM agent.{_TABLE} WHERE device_id = :d"
            ),
            {"d": device_id},
        ).one()
    return dict(row._mapping)


def _columns(engine: Engine) -> dict[str, tuple[str, str]]:
    with engine.connect() as conn:
        return {
            r.column_name: (r.data_type, r.is_nullable)
            for r in conn.execute(
                text(
                    "SELECT column_name, data_type, is_nullable "
                    "FROM information_schema.columns "
                    "WHERE table_schema = 'agent' AND table_name = :t"
                ),
                {"t": _TABLE},
            )
        }


@_PG_SKIP
def test_upgrade_census_upsert_downgrade_upgrade_round_trip() -> None:
    admin_url = admin_database_url()
    root = backend_root()

    with ephemeral_database(admin_url, "planlib_census") as (engine, db_url):
        run_alembic(root, db_url, "upgrade", "head")

        columns = _columns(engine)
        for name, data_type in _EXPECTED_COLUMNS.items():
            assert name in columns, f"{name} did not land"
            assert columns[name] == (data_type, "YES"), (
                f"{name} must be {data_type} and NULLABLE — a device whose "
                "build predates the census sends none, and NULL is UNKNOWN"
            )

        org = uuid.uuid4()
        device = uuid.uuid4()

        # 1. A report with no census at all — the whole fleet when this landed.
        assert _upsert(engine, org_id=org, device_id=device) is True
        stored = _census_row(engine, device)
        assert stored["ref_census"] is None
        assert stored["census_observed_at"] is None

        # 2. A census with stems is stored whole, digest lifted out.
        _upsert(
            engine,
            org_id=org,
            device_id=device,
            censuses=[_census("ref", _REF_STEMS, digest_over=_REF_STEMS)],
        )
        stored = _census_row(engine, device)
        assert stored["ref_census"]["slugs"] == sorted(_REF_STEMS)
        assert stored["ref_census_digest"] == slug_census_digest(_REF_STEMS)
        assert stored["census_ref_sha"] == "a" * 40
        assert stored["census_observed_at"] is not None

        # 3. The heartbeat form: stems withheld, digest MATCHES -> kept, and
        #    the rest of the census refreshed from this cycle. This is the
        #    ``jsonb_set`` arm, which only the migrated table can prove.
        _upsert(
            engine,
            org_id=org,
            device_id=device,
            censuses=[_census("ref", None, digest_over=_REF_STEMS, ref_sha="c" * 40)],
        )
        stored = _census_row(engine, device)
        assert stored["ref_census"]["slugs"] == sorted(_REF_STEMS)
        assert stored["ref_census"]["ref_sha"] == "c" * 40
        assert stored["census_ref_sha"] == "c" * 40

        # 4. Stems withheld, digest does NOT match -> cleared to UNKNOWN.
        _upsert(
            engine,
            org_id=org,
            device_id=device,
            censuses=[_census("ref", None, digest_over=_MOVED_STEMS)],
        )
        stored = _census_row(engine, device)
        assert stored["ref_census"]["slugs"] is None
        assert stored["ref_census_digest"] == slug_census_digest(_MOVED_STEMS)

        # 5. An out-of-order report changes no census.
        _upsert(
            engine,
            org_id=org,
            device_id=device,
            censuses=[_census("work_tree", _REF_STEMS, digest_over=_REF_STEMS)],
            observed_at=datetime.now(UTC) - timedelta(hours=1),
        )
        stored = _census_row(engine, device)
        assert stored["work_tree_census"] is None
        assert stored["ref_census_digest"] == slug_census_digest(_MOVED_STEMS)

        run_alembic(root, db_url, "downgrade", _PARENT_REVISION_ID)
        remaining = _columns(engine)
        assert not (set(_EXPECTED_COLUMNS) & set(remaining)), (
            "the downgrade left census columns behind"
        )
        # The table it hung off is untouched by this revision's downgrade.
        assert "counts_are_floors" in remaining

        run_alembic(root, db_url, "upgrade", "head")
        assert set(_EXPECTED_COLUMNS) <= set(_columns(engine))
