"""add_session_activity_table

Revision ID: 6a54cc0f9180
Revises: c1464319e0e2
Create Date: 2025-10-24 09:50:23.110995

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = "6a54cc0f9180"
down_revision: str | None = "c1464319e0e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_activities",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("jti", sa.String(), nullable=False),
        sa.Column("first_login_at", sa.DateTime(), nullable=False),
        sa.Column("last_activity_at", sa.DateTime(), nullable=False),
        sa.Column("absolute_expiry_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_activities_jti"), "session_activities", ["jti"], unique=True
    )
    op.create_index(
        op.f("ix_session_activities_user_id"),
        "session_activities",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_session_activities_user_id"), table_name="session_activities"
    )
    op.drop_index(op.f("ix_session_activities_jti"), table_name="session_activities")
    op.drop_table("session_activities")
    # ### end Alembic commands ###
