"""add_ai_prompt_tables

Revision ID: 53ce8daacd89
Revises: 05a366f58455
Create Date: 2025-12-18 10:28:46.335948

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53ce8daacd89"
down_revision: str | None = "05a366f58455"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_prompt_templates",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("default_timeout", sa.Integer(), nullable=True),
        sa.Column("default_working_directory", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_category"),
        "ai_prompt_templates",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_created_by"),
        "ai_prompt_templates",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_id"), "ai_prompt_templates", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_name"),
        "ai_prompt_templates",
        ["name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_prompt_templates_project_id"),
        "ai_prompt_templates",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "prompt_sequences",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("on_failure", sa.String(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("results_directory", sa.String(), nullable=True),
        sa.Column("default_timeout", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompt_sequences_category"),
        "prompt_sequences",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_sequences_created_by"),
        "prompt_sequences",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompt_sequences_id"), "prompt_sequences", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_sequences_name"), "prompt_sequences", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_prompt_sequences_project_id"),
        "prompt_sequences",
        ["project_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_sequences_project_id"), table_name="prompt_sequences")
    op.drop_index(op.f("ix_prompt_sequences_name"), table_name="prompt_sequences")
    op.drop_index(op.f("ix_prompt_sequences_id"), table_name="prompt_sequences")
    op.drop_index(op.f("ix_prompt_sequences_created_by"), table_name="prompt_sequences")
    op.drop_index(op.f("ix_prompt_sequences_category"), table_name="prompt_sequences")
    op.drop_table("prompt_sequences")
    op.drop_index(
        op.f("ix_ai_prompt_templates_project_id"), table_name="ai_prompt_templates"
    )
    op.drop_index(op.f("ix_ai_prompt_templates_name"), table_name="ai_prompt_templates")
    op.drop_index(op.f("ix_ai_prompt_templates_id"), table_name="ai_prompt_templates")
    op.drop_index(
        op.f("ix_ai_prompt_templates_created_by"), table_name="ai_prompt_templates"
    )
    op.drop_index(
        op.f("ix_ai_prompt_templates_category"), table_name="ai_prompt_templates"
    )
    op.drop_table("ai_prompt_templates")
    # ### end Alembic commands ###
