"""verify_schema_sync

Revision ID: 675031faaab9
Revises: 0a5fcb4bb6cd
Create Date: 2025-11-18 18:09:43.766277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision: str = '675031faaab9'
down_revision: Union[str, None] = '0a5fcb4bb6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if analytics_events table already exists (production compatibility)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing_tables = inspector.get_table_names()

    if 'analytics_events' not in existing_tables:
        op.create_table('analytics_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('event_name', sa.String(length=255), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=True),
        sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_analytics_events_event_name'), 'analytics_events', ['event_name'], unique=False)
        op.create_index('ix_analytics_events_name_timestamp', 'analytics_events', ['event_name', 'timestamp'], unique=False)
        op.create_index(op.f('ix_analytics_events_timestamp'), 'analytics_events', ['timestamp'], unique=False)
        op.create_index('ix_analytics_events_timestamp_desc', 'analytics_events', [sa.literal_column('timestamp DESC')], unique=False)
        op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
        op.create_index('ix_analytics_events_user_name', 'analytics_events', ['user_id', 'event_name'], unique=False)
    else:
        print("⚠️  analytics_events table already exists (production state), skipping creation")

    if 'analysis_jobs' not in existing_tables:
        op.create_table('analysis_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('annotation_set_id', sa.UUID(), nullable=False),
        sa.Column('analyzers_used', sa.JSON(), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('fusion_enabled', sa.Integer(), nullable=False),
        sa.Column('fusion_config', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('total_elements_found', sa.Integer(), nullable=True),
        sa.Column('total_fused_elements', sa.Integer(), nullable=True),
        sa.Column('analyzer_statistics', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_analysis_jobs_annotation_set_id'), 'analysis_jobs', ['annotation_set_id'], unique=False)
        op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    else:
        print("⚠️  analysis_jobs table already exists (production state), skipping creation")

    if 'region_analysis_jobs' not in existing_tables:
        op.create_table('region_analysis_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('annotation_set_id', sa.UUID(), nullable=False),
        sa.Column('analyzers_used', sa.JSON(), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('fusion_enabled', sa.Integer(), nullable=False),
        sa.Column('fusion_config', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('total_regions_found', sa.Integer(), nullable=True),
        sa.Column('total_fused_regions', sa.Integer(), nullable=True),
        sa.Column('analyzer_statistics', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['annotation_set_id'], ['annotation_sets.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_region_analysis_jobs_annotation_set_id'), 'region_analysis_jobs', ['annotation_set_id'], unique=False)
        op.create_index(op.f('ix_region_analysis_jobs_status'), 'region_analysis_jobs', ['status'], unique=False)
    else:
        print("⚠️  region_analysis_jobs table already exists (production state), skipping creation")

    if 'analyzer_results' not in existing_tables:
        op.create_table('analyzer_results',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('analysis_job_id', sa.UUID(), nullable=False),
        sa.Column('analyzer_name', sa.String(), nullable=False),
        sa.Column('analyzer_type', sa.String(), nullable=False),
        sa.Column('analyzer_version', sa.String(), nullable=True),
        sa.Column('elements_found', sa.Integer(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('analyzer_metadata', sa.JSON(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_analyzer_results_analysis_job_id'), 'analyzer_results', ['analysis_job_id'], unique=False)
        op.create_index(op.f('ix_analyzer_results_analyzer_name'), 'analyzer_results', ['analyzer_name'], unique=False)
        op.create_index(op.f('ix_analyzer_results_analyzer_type'), 'analyzer_results', ['analyzer_type'], unique=False)
    else:
        print("⚠️  analyzer_results table already exists (production state), skipping creation")

    if 'fused_elements' not in existing_tables:
        op.create_table('fused_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('source_confidences', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('element_type', sa.String(), nullable=True),
    sa.Column('screenshot_index', sa.Integer(), nullable=False),
    sa.Column('element_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fused_elements_analysis_job_id'), 'fused_elements', ['analysis_job_id'], unique=False)
    op.create_index('ix_fused_elements_confidence', 'fused_elements', ['confidence'], unique=False)
    op.create_index(op.f('ix_fused_elements_element_type'), 'fused_elements', ['element_type'], unique=False)
    op.create_index('ix_fused_elements_job_screenshot', 'fused_elements', ['analysis_job_id', 'screenshot_index'], unique=False)
    op.create_index(op.f('ix_fused_elements_screenshot_index'), 'fused_elements', ['screenshot_index'], unique=False)
    op.create_index('ix_fused_elements_votes', 'fused_elements', ['votes'], unique=False)
    op.create_table('fused_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=False),
    sa.Column('source_confidences', sa.JSON(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('region_type', sa.String(), nullable=True),
    sa.Column('screenshot_index', sa.Integer(), nullable=False),
    sa.Column('grid_metadata', sa.JSON(), nullable=True),
    sa.Column('region_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['region_analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fused_regions_analysis_job_id'), 'fused_regions', ['analysis_job_id'], unique=False)
    op.create_index('ix_fused_regions_confidence', 'fused_regions', ['confidence'], unique=False)
    op.create_index('ix_fused_regions_job_screenshot', 'fused_regions', ['analysis_job_id', 'screenshot_index'], unique=False)
    op.create_index(op.f('ix_fused_regions_region_type'), 'fused_regions', ['region_type'], unique=False)
    op.create_index(op.f('ix_fused_regions_screenshot_index'), 'fused_regions', ['screenshot_index'], unique=False)
    op.create_index('ix_fused_regions_type', 'fused_regions', ['region_type'], unique=False)
    op.create_index('ix_fused_regions_votes', 'fused_regions', ['votes'], unique=False)
    op.create_table('region_analyzer_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_job_id', sa.UUID(), nullable=False),
    sa.Column('analyzer_name', sa.String(), nullable=False),
    sa.Column('analyzer_version', sa.String(), nullable=True),
    sa.Column('regions_found', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('analyzer_metadata', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['region_analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_analyzer_results_analysis_job_id'), 'region_analyzer_results', ['analysis_job_id'], unique=False)
    op.create_index(op.f('ix_region_analyzer_results_analyzer_name'), 'region_analyzer_results', ['analyzer_name'], unique=False)
    op.create_table('detected_elements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzer_result_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('element_type', sa.String(), nullable=True),
    sa.Column('screenshot_index', sa.Integer(), nullable=False),
    sa.Column('element_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analyzer_result_id'], ['analyzer_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_elements_analyzer_result_id'), 'detected_elements', ['analyzer_result_id'], unique=False)
    op.create_index('ix_detected_elements_analyzer_screenshot', 'detected_elements', ['analyzer_result_id', 'screenshot_index'], unique=False)
    op.create_index(op.f('ix_detected_elements_element_type'), 'detected_elements', ['element_type'], unique=False)
    op.create_index(op.f('ix_detected_elements_screenshot_index'), 'detected_elements', ['screenshot_index'], unique=False)
    op.create_table('detected_regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analyzer_result_id', sa.UUID(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('region_type', sa.String(), nullable=True),
    sa.Column('screenshot_index', sa.Integer(), nullable=False),
    sa.Column('grid_metadata', sa.JSON(), nullable=True),
    sa.Column('region_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['analyzer_result_id'], ['region_analyzer_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detected_regions_analyzer_result_id'), 'detected_regions', ['analyzer_result_id'], unique=False)
    op.create_index('ix_detected_regions_analyzer_screenshot', 'detected_regions', ['analyzer_result_id', 'screenshot_index'], unique=False)
    op.create_index(op.f('ix_detected_regions_region_type'), 'detected_regions', ['region_type'], unique=False)
    op.create_index(op.f('ix_detected_regions_screenshot_index'), 'detected_regions', ['screenshot_index'], unique=False)
    op.create_index('ix_detected_regions_type', 'detected_regions', ['region_type'], unique=False)
    op.drop_index(op.f('ix_activity_logs_project_created'), table_name='activity_logs')
    # Removed JSONB->JSON conversions due to GIN index conflicts (keeping JSONB is better anyway)
    op.drop_index(op.f('ix_automation_videos_s3_key'), table_name='automation_videos')
    op.create_unique_constraint(None, 'automation_videos', ['s3_key'])
    op.drop_constraint(op.f('automation_videos_project_id_fkey'), 'automation_videos', type_='foreignkey')
    op.drop_constraint(op.f('automation_videos_user_id_fkey'), 'automation_videos', type_='foreignkey')
    op.create_foreign_key(None, 'automation_videos', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'automation_videos', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('uq_invitation_token'), 'organization_invitations', type_='unique')
    op.create_index(op.f('ix_organization_invitations_token'), 'organization_invitations', ['token'], unique=True)
    op.drop_constraint(op.f('uq_organization_slug'), 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.drop_constraint(op.f('organizations_owner_id_fkey'), 'organizations', type_='foreignkey')
    op.create_foreign_key(None, 'organizations', 'users', ['owner_id'], ['id'])
    op.drop_constraint(op.f('patterns_pattern_id_key'), 'patterns', type_='unique')
    op.drop_index(op.f('ix_patterns_pattern_id'), table_name='patterns')
    op.create_index(op.f('ix_patterns_pattern_id'), 'patterns', ['pattern_id'], unique=True)
    op.drop_index(op.f('ix_project_comments_created_at'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_resolved'), table_name='project_comments')
    op.drop_index(op.f('ix_project_locks_expires_at'), table_name='project_locks')
    op.drop_index(op.f('ix_project_locks_project_resource'), table_name='project_locks')
    # Removed JSONB->JSON conversion for screenshot_input_associations
    op.create_index(op.f('ix_screenshot_input_associations_log_id'), 'screenshot_input_associations', ['log_id'], unique=False)
    op.create_index(op.f('ix_screenshot_input_associations_screenshot_id'), 'screenshot_input_associations', ['screenshot_id'], unique=False)
    op.drop_constraint(op.f('snapshot_runs_run_id_key'), 'snapshot_runs', type_='unique')
    op.drop_index(op.f('ix_snapshot_runs_run_id'), table_name='snapshot_runs')
    op.create_index(op.f('ix_snapshot_runs_run_id'), 'snapshot_runs', ['run_id'], unique=True)
    op.drop_constraint(op.f('team_members_invited_by_fkey'), 'team_members', type_='foreignkey')
    op.create_foreign_key(None, 'team_members', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_members', type_='foreignkey')
    op.create_foreign_key(op.f('team_members_invited_by_fkey'), 'team_members', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_snapshot_runs_run_id'), table_name='snapshot_runs')
    op.create_index(op.f('ix_snapshot_runs_run_id'), 'snapshot_runs', ['run_id'], unique=False)
    op.create_unique_constraint(op.f('snapshot_runs_run_id_key'), 'snapshot_runs', ['run_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_screenshot_input_associations_screenshot_id'), table_name='screenshot_input_associations')
    op.drop_index(op.f('ix_screenshot_input_associations_log_id'), table_name='screenshot_input_associations')
    # Removed JSON->JSONB conversion (kept JSONB)
    op.create_index(op.f('ix_project_locks_project_resource'), 'project_locks', ['project_id', 'resource_id'], unique=False)
    op.create_index(op.f('ix_project_locks_expires_at'), 'project_locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_project_comments_resolved'), 'project_comments', ['resolved'], unique=False)
    op.create_index(op.f('ix_project_comments_created_at'), 'project_comments', ['created_at'], unique=False)
    op.drop_index(op.f('ix_patterns_pattern_id'), table_name='patterns')
    op.create_index(op.f('ix_patterns_pattern_id'), 'patterns', ['pattern_id'], unique=False)
    op.create_unique_constraint(op.f('patterns_pattern_id_key'), 'patterns', ['pattern_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.create_foreign_key(op.f('organizations_owner_id_fkey'), 'organizations', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint(op.f('uq_organization_slug'), 'organizations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_organization_invitations_token'), table_name='organization_invitations')
    op.create_unique_constraint(op.f('uq_invitation_token'), 'organization_invitations', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'automation_videos', type_='foreignkey')
    op.drop_constraint(None, 'automation_videos', type_='foreignkey')
    op.create_foreign_key(op.f('automation_videos_user_id_fkey'), 'automation_videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('automation_videos_project_id_fkey'), 'automation_videos', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'automation_videos', type_='unique')
    op.create_index(op.f('ix_automation_videos_s3_key'), 'automation_videos', ['s3_key'], unique=True)
    # Removed JSON->JSONB conversions (kept JSONB)
    op.create_index(op.f('ix_activity_logs_project_created'), 'activity_logs', ['project_id', 'created_at'], unique=False)
    op.drop_index('ix_detected_regions_type', table_name='detected_regions')
    op.drop_index(op.f('ix_detected_regions_screenshot_index'), table_name='detected_regions')
    op.drop_index(op.f('ix_detected_regions_region_type'), table_name='detected_regions')
    op.drop_index('ix_detected_regions_analyzer_screenshot', table_name='detected_regions')
    op.drop_index(op.f('ix_detected_regions_analyzer_result_id'), table_name='detected_regions')
    op.drop_table('detected_regions')
    op.drop_index(op.f('ix_detected_elements_screenshot_index'), table_name='detected_elements')
    op.drop_index(op.f('ix_detected_elements_element_type'), table_name='detected_elements')
    op.drop_index('ix_detected_elements_analyzer_screenshot', table_name='detected_elements')
    op.drop_index(op.f('ix_detected_elements_analyzer_result_id'), table_name='detected_elements')
    op.drop_table('detected_elements')
    op.drop_index(op.f('ix_region_analyzer_results_analyzer_name'), table_name='region_analyzer_results')
    op.drop_index(op.f('ix_region_analyzer_results_analysis_job_id'), table_name='region_analyzer_results')
    op.drop_table('region_analyzer_results')
    op.drop_index('ix_fused_regions_votes', table_name='fused_regions')
    op.drop_index('ix_fused_regions_type', table_name='fused_regions')
    op.drop_index(op.f('ix_fused_regions_screenshot_index'), table_name='fused_regions')
    op.drop_index(op.f('ix_fused_regions_region_type'), table_name='fused_regions')
    op.drop_index('ix_fused_regions_job_screenshot', table_name='fused_regions')
    op.drop_index('ix_fused_regions_confidence', table_name='fused_regions')
    op.drop_index(op.f('ix_fused_regions_analysis_job_id'), table_name='fused_regions')
    op.drop_table('fused_regions')
    op.drop_index('ix_fused_elements_votes', table_name='fused_elements')
    op.drop_index(op.f('ix_fused_elements_screenshot_index'), table_name='fused_elements')
    op.drop_index('ix_fused_elements_job_screenshot', table_name='fused_elements')
    op.drop_index(op.f('ix_fused_elements_element_type'), table_name='fused_elements')
    op.drop_index('ix_fused_elements_confidence', table_name='fused_elements')
    op.drop_index(op.f('ix_fused_elements_analysis_job_id'), table_name='fused_elements')
    op.drop_table('fused_elements')
    op.drop_index(op.f('ix_analyzer_results_analyzer_type'), table_name='analyzer_results')
    op.drop_index(op.f('ix_analyzer_results_analyzer_name'), table_name='analyzer_results')
    op.drop_index(op.f('ix_analyzer_results_analysis_job_id'), table_name='analyzer_results')
    op.drop_table('analyzer_results')
    op.drop_index(op.f('ix_region_analysis_jobs_status'), table_name='region_analysis_jobs')
    op.drop_index(op.f('ix_region_analysis_jobs_annotation_set_id'), table_name='region_analysis_jobs')
    op.drop_table('region_analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_annotation_set_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index('ix_analytics_events_user_name', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_timestamp_desc', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_timestamp'), table_name='analytics_events')
    op.drop_index('ix_analytics_events_name_timestamp', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_name'), table_name='analytics_events')
    op.drop_table('analytics_events')
    # ### end Alembic commands ###
