"""remove_runner_tokens

Revision ID: 7931bff72fe5
Revises: 951df6f04439
Create Date: 2025-12-24 22:19:12.331604

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7931bff72fe5"
down_revision: Union[str, None] = "951df6f04439"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # First remove the FK constraint and column from runner_connections
    op.drop_index(
        op.f("ix_runner_connections_runner_token_id"), table_name="runner_connections"
    )
    op.drop_constraint(
        op.f("runner_connections_runner_token_id_fkey"),
        "runner_connections",
        type_="foreignkey",
    )
    op.drop_column("runner_connections", "runner_token_id")

    # Now we can safely drop the runner_tokens table
    op.drop_index(op.f("ix_runner_tokens_is_revoked"), table_name="runner_tokens")
    op.drop_index(op.f("ix_runner_tokens_last_used_at"), table_name="runner_tokens")
    op.drop_index(op.f("ix_runner_tokens_token_hash"), table_name="runner_tokens")
    op.drop_index(op.f("ix_runner_tokens_user_id"), table_name="runner_tokens")
    op.drop_table("runner_tokens")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "runner_connections",
        sa.Column("runner_token_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("runner_connections_runner_token_id_fkey"),
        "runner_connections",
        "runner_tokens",
        ["runner_token_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(
        op.f("ix_runner_connections_runner_token_id"),
        "runner_connections",
        ["runner_token_id"],
        unique=False,
    )
    op.create_table(
        "runner_tokens",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="User-friendly name like 'My Laptop', 'Work Desktop'",
        ),
        sa.Column(
            "token_hash",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
            comment="SHA-256 hash of the token",
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Token expiration time. None = never expires",
        ),
        sa.Column(
            "last_used_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Last time this token was used for authentication",
        ),
        sa.Column(
            "is_revoked",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Soft delete flag for audit trail",
        ),
        sa.Column(
            "revoked_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="When the token was revoked",
        ),
        sa.Column(
            "last_ip_address",
            sa.VARCHAR(length=45),
            autoincrement=False,
            nullable=True,
            comment="Last IP address that used this token",
        ),
        sa.Column(
            "last_user_agent",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="Last user agent that used this token",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("runner_tokens_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("runner_tokens_pkey")),
    )
    op.create_index(
        op.f("ix_runner_tokens_user_id"), "runner_tokens", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_runner_tokens_token_hash"),
        "runner_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_runner_tokens_last_used_at"),
        "runner_tokens",
        ["last_used_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runner_tokens_is_revoked"),
        "runner_tokens",
        ["is_revoked"],
        unique=False,
    )
    # ### end Alembic commands ###
