"""add_phase1_analytics_features

Revision ID: 8720b6a82cc1
Revises: 4fb27f2a4495
Create Date: 2025-10-01 21:27:59.959367

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8720b6a82cc1"
down_revision: str | None = "4fb27f2a4495"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Extend users table
    op.add_column("users", sa.Column("company", sa.String(), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.add_column(
        "users", sa.Column("email_verification_token", sa.String(), nullable=True)
    )
    op.add_column("users", sa.Column("subscription_tier", sa.String(), nullable=True))

    # Create usage_metrics table
    op.create_table(
        "usage_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("metric_type", sa.String(), nullable=False),
        sa.Column("value", sa.DECIMAL(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("metric_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_usage_metrics_user_id", "usage_metrics", ["user_id"])
    op.create_index("ix_usage_metrics_timestamp", "usage_metrics", ["timestamp"])

    # Create storage_usage table
    op.create_table(
        "storage_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_storage_usage_user_id", "storage_usage", ["user_id"])

    # Create audit_logs table
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("resource_type", sa.String(), nullable=True),
        sa.Column("resource_id", sa.String(), nullable=True),
        sa.Column("log_metadata", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"])
    op.create_index("ix_audit_logs_created_at", "audit_logs", ["created_at"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop audit_logs table
    op.drop_index("ix_audit_logs_created_at", "audit_logs")
    op.drop_index("ix_audit_logs_user_id", "audit_logs")
    op.drop_table("audit_logs")

    # Drop storage_usage table
    op.drop_index("ix_storage_usage_user_id", "storage_usage")
    op.drop_table("storage_usage")

    # Drop usage_metrics table
    op.drop_index("ix_usage_metrics_timestamp", "usage_metrics")
    op.drop_index("ix_usage_metrics_user_id", "usage_metrics")
    op.drop_table("usage_metrics")

    # Drop columns from users table
    op.drop_column("users", "subscription_tier")
    op.drop_column("users", "email_verification_token")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "phone")
    op.drop_column("users", "company")
    # ### end Alembic commands ###
