"""add_detected_issues_table

Revision ID: 951df6f04439
Revises: 53ce8daacd89
Create Date: 2025-12-18 17:04:37.406070

"""

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy.generics
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "951df6f04439"
down_revision: str | None = "53ce8daacd89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detected_issues",
        sa.Column(
            "id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "user_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file", sa.String(length=1000), nullable=True),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detected_issues_project_id"),
        "detected_issues",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        "ix_detected_issues_project_status",
        "detected_issues",
        ["project_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_detected_issues_session", "detected_issues", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_detected_issues_session_id"),
        "detected_issues",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detected_issues_severity"),
        "detected_issues",
        ["severity"],
        unique=False,
    )
    op.create_index(
        "ix_detected_issues_source",
        "detected_issues",
        ["source"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"source": "jsonb_path_ops"},
    )
    op.create_index(
        op.f("ix_detected_issues_status"), "detected_issues", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_detected_issues_user_id"), "detected_issues", ["user_id"], unique=False
    )
    op.create_index(
        "ix_detected_issues_user_severity",
        "detected_issues",
        ["user_id", "severity"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detected_issues_user_severity", table_name="detected_issues")
    op.drop_index(op.f("ix_detected_issues_user_id"), table_name="detected_issues")
    op.drop_index(op.f("ix_detected_issues_status"), table_name="detected_issues")
    op.drop_index(
        "ix_detected_issues_source",
        table_name="detected_issues",
        postgresql_using="gin",
        postgresql_ops={"source": "jsonb_path_ops"},
    )
    op.drop_index(op.f("ix_detected_issues_severity"), table_name="detected_issues")
    op.drop_index(op.f("ix_detected_issues_session_id"), table_name="detected_issues")
    op.drop_index("ix_detected_issues_session", table_name="detected_issues")
    op.drop_index("ix_detected_issues_project_status", table_name="detected_issues")
    op.drop_index(op.f("ix_detected_issues_project_id"), table_name="detected_issues")
    op.drop_table("detected_issues")
    # ### end Alembic commands ###
