"""project.agent_commands + project.agent_command_versions

Revision ID: avac_01_agent_commands
Revises: merge_enabled_01
Create Date: 2026-08-04

Phase 1 of plan ``2026-07-29-account-versioned-agent-commands``
(account-versioned agent commands).

The runner ships its fleet commands (``/vet-plan``, ``/implement-plan``, …)
embedded in its binary. These two tables add the OPTIONAL account layer on top:
an organization may store an override that replaces a default BY NAME, with a
real append-only version history so an edit is revertable.

There is no "default row" — the embedded defaults are never written here, so
deleting an override row can only ever mean "let the embedded default apply
again". That is why the delete path is a plain row delete rather than a
soft-delete flag.

Two unique constraints carry the design:

* ``uq_agent_command_org_name`` — one override per command per account. This
  deliberately does NOT copy ``project.skills.slug``'s GLOBAL unique index,
  which is a cross-org collision hazard. ``(organization_id, name)`` is the
  correct multi-tenant key.
* ``uq_agent_command_version`` — the monotonic version chain. Without it,
  "append-only and monotonic" is enforced only by application code: two
  concurrent appends read the same ``max(version_number)`` and both write it.
  The DB constraint is what makes the claim true rather than aspirational.

Hand-written rather than autogenerated: ``alembic revision --autogenerate`` is
banned in this repo and ``./scripts/safe_migrate.sh`` does not exist here.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "avac_01_agent_commands"
down_revision: str | Sequence[str] | None = "merge_enabled_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the agent-command override table and its version chain."""
    op.create_table(
        "agent_commands",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("organization_id", UUID(as_uuid=True), nullable=True),
        sa.Column("created_by_user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(128), nullable=True),
        sa.Column(
            "is_shared",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
        sa.Column(
            "current_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["auth.organizations.id"],
            name="fk_agent_commands_organization_id",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint(
            "organization_id", "name", name="uq_agent_command_org_name"
        ),
        schema="project",
    )
    op.create_index(
        op.f("ix_project_agent_commands_organization_id"),
        "agent_commands",
        ["organization_id"],
        unique=False,
        schema="project",
    )
    op.create_index(
        op.f("ix_project_agent_commands_created_by_user_id"),
        "agent_commands",
        ["created_by_user_id"],
        unique=False,
        schema="project",
    )

    op.create_table(
        "agent_command_versions",
        sa.Column(
            "id",
            UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("agent_command_id", UUID(as_uuid=True), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(128), nullable=True),
        sa.Column("created_by_user_id", UUID(as_uuid=True), nullable=True),
        sa.Column("change_description", sa.Text(), nullable=True),
        sa.Column("restored_from", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["agent_command_id"],
            ["project.agent_commands.id"],
            name="fk_agent_command_versions_agent_command_id",
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "agent_command_id", "version_number", name="uq_agent_command_version"
        ),
        schema="project",
    )
    op.create_index(
        op.f("ix_project_agent_command_versions_agent_command_id"),
        "agent_command_versions",
        ["agent_command_id"],
        unique=False,
        schema="project",
    )
    op.create_index(
        op.f("ix_project_agent_command_versions_created_by_user_id"),
        "agent_command_versions",
        ["created_by_user_id"],
        unique=False,
        schema="project",
    )


def downgrade() -> None:
    """Drop the version chain, then the override table."""
    op.drop_index(
        op.f("ix_project_agent_command_versions_created_by_user_id"),
        table_name="agent_command_versions",
        schema="project",
    )
    op.drop_index(
        op.f("ix_project_agent_command_versions_agent_command_id"),
        table_name="agent_command_versions",
        schema="project",
    )
    op.drop_table("agent_command_versions", schema="project")

    op.drop_index(
        op.f("ix_project_agent_commands_created_by_user_id"),
        table_name="agent_commands",
        schema="project",
    )
    op.drop_index(
        op.f("ix_project_agent_commands_organization_id"),
        table_name="agent_commands",
        schema="project",
    )
    op.drop_table("agent_commands", schema="project")
