"""coordinator phase a 01 coord tables

Revision ID: coordinator_phase_a_01_coord_tables
Revises: consolidation_phase2_zz_final_runner_cleanup
Create Date: 2026-04-29

Phase 5 sub-phase A of the multi-machine coordinator plan
(``D:/qontinui-root/tmp_multimachine_coordinator_plan.md`` §12.5).

Creates four ``coord.*`` tables that the coordinator service (qontinui-coord)
needs as durable storage for cross-machine state:

* ``coord.machines`` — per-machine identity + presence (last-seen, current
  branches per repo, alembic head per local DB).
* ``coord.claims_audit`` — durable audit log of claim acquire / heartbeat /
  release / expiry / steal events. The live claim *state* lives in Redis
  (sub-second TTL keys); this table is the forensic record.
* ``coord.repo_branches`` — pushed-but-unmerged branch tip cache, populated
  by GitHub webhook ingest (``POST /webhooks/github`` + dedicated handlers
  for ``pull_request`` / ``push`` / ``branch`` / ``check_run``).
* ``coord.events`` — append-only timeline for `/coordinate` UI rendering
  ("what changed in the last hour"). Already partially populated via
  Redis pub/sub fanout; this table is the durable mirror.

Schema choice: every table lives in ``coord`` per the schema-mapping
section of the migration consolidation plan. Cross-machine coordination
is exactly the ``coord.*`` mandate.

Pre-existing ``coord.*`` tables this revision deliberately does NOT
touch (created by Phase 1 of the consolidation):

  - ``coord.coordinator_decisions``      (legacy — single-machine decision log)
  - ``coord.coordinator_leader``         (legacy — single-PG-cluster lease;
                                          superseded by the per-machine
                                          identity in coord.machines but
                                          kept for backwards compat)
  - ``coord.plans``                      (productivity stack)
  - ``coord.tasks``                      (productivity stack)
  - ``coord.reviews``                    (productivity stack)
  - ``coord.session_file_snapshots``     (productivity stack)
  - ``coord.runner_instances``           (operational process state — distinct
                                          from coord.machines which is
                                          per-host identity)
  - ``coord.process_sessions``           (operational process state)
  - ``coord.gui_lock``                   (singleton resource lock)
  - ``coord.worktrees``                  (worktree leases)
  - ``coord.session_touched_files``      (file edit tracking)

Notable design choices:

1. **Generic claim_kind in coord.claims_audit.** Rather than a table per
   claim type (alembic_revision, branch_name, file_glob, phase), one
   normalized table keyed by ``(claim_kind, resource_key)`` — matches
   the partial-unique idiom in the original plan, even though the live
   table is now Redis. The audit log is queried by humans for
   "who claimed X when?" and a normalized table is easier to grep.

2. **machine_id is UUID generated by the runner.** Stored in
   ``~/.qontinui/machine.json`` per topology plan §3. The coord service
   trusts the caller-supplied ``machine_id`` — auth posture is "you
   identified yourself, don't lie." Topology plan Phase 7 (auth
   promotion) replaces this with JWT claims.

3. **Heartbeat-driven presence.** ``coord.machines.last_seen_at`` is the
   single source of truth for "is this machine online right now?" — no
   separate Redis presence key. The runner heartbeats every 60s; >5min
   means stale (yellow), >30min means dead (red).

4. **GIN index on touched_files for branch-conflict queries.** The
   file-conflict prediction endpoint runs glob-overlap against
   ``coord.repo_branches.touched_files``; a GIN array_ops index lets
   the planner do fast set-membership lookups for any-overlap queries.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "coordinator_phase_a_01_coord_tables"
down_revision: str = "consolidation_phase2_zz_final_runner_cleanup"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ------------------------------------------------------------------
    # coord.machines
    # ------------------------------------------------------------------
    op.create_table(
        "machines",
        sa.Column(
            "machine_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column("hostname", sa.Text(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "current_branches",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "last_alembic_head",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="coord",
    )
    op.create_index(
        "idx_machines_last_seen",
        "machines",
        [sa.text("last_seen_at DESC")],
        schema="coord",
    )
    op.create_index(
        "idx_machines_hostname",
        "machines",
        ["hostname"],
        schema="coord",
    )

    # ------------------------------------------------------------------
    # coord.claims_audit
    # ------------------------------------------------------------------
    op.create_table(
        "claims_audit",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("claim_kind", sa.Text(), nullable=False),
        sa.Column("resource_key", sa.Text(), nullable=False),
        sa.Column(
            "machine_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("coord.machines.machine_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "event",
            sa.Text(),
            nullable=False,
            comment="acquire | heartbeat | release | expire | steal",
        ),
        sa.Column(
            "ttl_seconds",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="coord",
    )
    op.create_index(
        "idx_claims_audit_resource",
        "claims_audit",
        ["claim_kind", "resource_key", sa.text("occurred_at DESC")],
        schema="coord",
    )
    op.create_index(
        "idx_claims_audit_machine",
        "claims_audit",
        ["machine_id", sa.text("occurred_at DESC")],
        schema="coord",
        postgresql_where=sa.text("machine_id IS NOT NULL"),
    )
    op.create_index(
        "idx_claims_audit_event",
        "claims_audit",
        ["event", sa.text("occurred_at DESC")],
        schema="coord",
    )

    # ------------------------------------------------------------------
    # coord.repo_branches
    # ------------------------------------------------------------------
    op.create_table(
        "repo_branches",
        sa.Column("repo", sa.Text(), nullable=False),
        sa.Column("branch", sa.Text(), nullable=False),
        sa.Column("base_branch", sa.Text(), nullable=False, server_default=sa.text("'main'")),
        sa.Column("head_sha", sa.Text(), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column(
            "pr_state",
            sa.Text(),
            nullable=False,
            server_default=sa.text("'open'"),
            comment="open | draft | merged | closed | unknown",
        ),
        sa.Column(
            "head_author_machine",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("coord.machines.machine_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "touched_files",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column(
            "touched_alembic_revisions",
            postgresql.ARRAY(sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::text[]"),
        ),
        sa.Column(
            "last_refreshed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("repo", "branch"),
        schema="coord",
    )
    op.create_index(
        "idx_repo_branches_pr_state",
        "repo_branches",
        ["pr_state"],
        schema="coord",
    )
    op.create_index(
        "idx_repo_branches_refreshed",
        "repo_branches",
        [sa.text("last_refreshed_at DESC")],
        schema="coord",
    )
    # GIN array_ops index for fast any-overlap queries on touched_files —
    # used by /coordinator/coord/file-conflicts. Without this, the
    # endpoint scans every unmerged branch row.
    op.execute(
        "CREATE INDEX idx_repo_branches_touched_files "
        "ON coord.repo_branches USING GIN (touched_files array_ops)"
    )

    # ------------------------------------------------------------------
    # coord.events
    # ------------------------------------------------------------------
    op.create_table(
        "events",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "machine_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("coord.machines.machine_id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema="coord",
    )
    op.create_index(
        "idx_events_created",
        "events",
        [sa.text("created_at DESC")],
        schema="coord",
    )
    op.create_index(
        "idx_events_kind_created",
        "events",
        ["kind", sa.text("created_at DESC")],
        schema="coord",
    )
    op.create_index(
        "idx_events_machine_created",
        "events",
        ["machine_id", sa.text("created_at DESC")],
        schema="coord",
        postgresql_where=sa.text("machine_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS coord.idx_events_machine_created")
    op.execute("DROP INDEX IF EXISTS coord.idx_events_kind_created")
    op.execute("DROP INDEX IF EXISTS coord.idx_events_created")
    op.drop_table("events", schema="coord")

    op.execute("DROP INDEX IF EXISTS coord.idx_repo_branches_touched_files")
    op.execute("DROP INDEX IF EXISTS coord.idx_repo_branches_refreshed")
    op.execute("DROP INDEX IF EXISTS coord.idx_repo_branches_pr_state")
    op.drop_table("repo_branches", schema="coord")

    op.execute("DROP INDEX IF EXISTS coord.idx_claims_audit_event")
    op.execute("DROP INDEX IF EXISTS coord.idx_claims_audit_machine")
    op.execute("DROP INDEX IF EXISTS coord.idx_claims_audit_resource")
    op.drop_table("claims_audit", schema="coord")

    op.execute("DROP INDEX IF EXISTS coord.idx_machines_hostname")
    op.execute("DROP INDEX IF EXISTS coord.idx_machines_last_seen")
    op.drop_table("machines", schema="coord")
