"""coord.session_compliance.nudge_attempts — record whether the correction fired

Revision ID: coord_sesscompl_04
Revises: coord_memory_anchor_obs
Create Date: 2026-08-06

Follow-up to §A4 of plan
``D:/qontinui-root/qontinui-dev-notes/plans/2026-07-30-session-compliance-report-enforcement.md``.

coord authors **zero** DDL (``[policy: alembic-sole-authorship]``), so this
lands here, in qontinui-web, and must merge BEFORE the coord PR that reads
these columns.

The gap
=======

Enforcement was switched on so the nudge's **false-positive rate** could be
measured on real sessions — that is the reason the plan shipped report-only
first (§ "ship it report-only on purpose") and gated promotion of the nudge on
*"only after §1 shows detection is accurate"*.

That measurement is not currently possible, because nothing records whether a
session was ever nudged. A stored verdict of ``unverified/absent`` is equally
consistent with:

* the session was nudged and ignored it — the nudge fired and did not work; and
* the session was never nudged at all — the nudge did not fire.

Those support opposite conclusions about whether the mechanism works, and the
row cannot distinguish them. A false positive is specifically *a session that
was nudged when it should not have been*, so without an attempt count the
quantity the soak exists to produce is undefined.

What this migration does
========================

Adds two columns to ``coord.session_compliance``:

* ``nudge_attempts INTEGER NOT NULL DEFAULT 0`` — how many times the runner
  actually delivered the correction into this session. ``0`` is the honest
  default for every row written before this lands, and for every row where the
  check was ``not_applicable`` (enforcement off ⇒ no nudge is ever sent).

* ``last_nudged_at TIMESTAMPTZ NULL`` — when the most recent one was
  delivered. NULL means never, which ``nudge_attempts = 0`` also says; the
  timestamp exists to correlate a nudge with the turn that provoked it, which
  a bare counter cannot do.

Design / column-contract notes
==============================

* The column set is a **shared contract** with the coord Rust code — column
  names must not drift from this list (same rule as
  ``coord_sesscompl_01``).

* ``NOT NULL DEFAULT 0`` rather than nullable. There is a real temptation to
  make it nullable so "we never asked" is distinguishable from "we asked zero
  times", but those are the same fact here: the runner reports the count it
  actually delivered, and a row written by a runner that predates the field
  simply carries the default. What must NOT happen is a NULL rendering as a
  confident ``0`` downstream — with a NOT NULL column there is no NULL to
  misrender, and the "was this row written by an attempts-aware runner?"
  question is answered by ``last_nudged_at`` plus the row's own age rather
  than by overloading the counter.

* ``nudge_attempts >= 0`` is CHECK-constrained. A negative count is not a
  degraded reading, it is a bug in whatever wrote it, and it should fail at
  the write rather than be averaged into a rate.

* Deliberately NOT a cap enforcement mechanism. ``max_attempts`` lives in
  ``coord.session_compliance_config`` (``coord_sesscompl_02``) and the runner
  enforces it; this column is the *observation* of what happened, which is a
  separate concern from the policy about what is allowed to happen. Storing
  the observation is what makes it possible to check the cap was honoured —
  and at the time of writing it is not: the runner parses ``max_attempts`` and
  never reads it, capping at one-per-session via an in-process
  ``HashSet<String>`` instead. This column is how that becomes visible rather
  than inferred.

* The in-process set is also why the count is reported by the runner rather
  than derived by coord: coord cannot see a nudge, it only sees the POST that
  follows one. A runner restart mid-session loses the set, so a long session
  spanning a restart can be nudged again — that shows up here as
  ``nudge_attempts`` exceeding the configured cap, which is exactly the sort
  of thing this column exists to surface rather than hide.
"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "coord_sesscompl_04"
down_revision = "coord_memory_anchor_obs"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Raw ``op.execute`` with IF NOT EXISTS — the convention the sibling
    # ``coord.gates.agent_session_id`` column used (``coord_sesscompl_03``),
    # and what keeps a re-run harmless.
    op.execute(
        """
        ALTER TABLE coord.session_compliance
            ADD COLUMN IF NOT EXISTS nudge_attempts INTEGER NOT NULL DEFAULT 0
        """
    )
    op.execute(
        """
        ALTER TABLE coord.session_compliance
            ADD COLUMN IF NOT EXISTS last_nudged_at TIMESTAMPTZ
        """
    )
    # Named so the drop below can be idempotent, and so a violation names the
    # invariant rather than an autogenerated string.
    op.execute(
        """
        ALTER TABLE coord.session_compliance
            DROP CONSTRAINT IF EXISTS ck_session_compliance_nudge_attempts_nonneg
        """
    )
    op.execute(
        """
        ALTER TABLE coord.session_compliance
            ADD CONSTRAINT ck_session_compliance_nudge_attempts_nonneg
            CHECK (nudge_attempts >= 0)
        """
    )


def downgrade() -> None:
    op.execute(
        """
        ALTER TABLE coord.session_compliance
            DROP CONSTRAINT IF EXISTS ck_session_compliance_nudge_attempts_nonneg
        """
    )
    op.execute(
        "ALTER TABLE coord.session_compliance DROP COLUMN IF EXISTS last_nudged_at"
    )
    op.execute(
        "ALTER TABLE coord.session_compliance DROP COLUMN IF EXISTS nudge_attempts"
    )
