"""coord memory_records — anchors + anchor_state (anchored/derived memory)

Revision ID: coord_memory_anchors
Revises: avac_01_agent_commands
Create Date: 2026-08-04

Phase 1 of plan ``2026-07-29-memory-anchored-derived-records``
(``D:/qontinui-root/plans/2026-07-29-memory-anchored-derived-records.md``).

Today every row in ``coord.memory_records`` is a timeless narrative assertion
whose confidence erodes on the Ebbinghaus curve alone. A large class of records
is not like that: they assert something about an external artifact and are true
exactly as long as that artifact holds. This revision adds the two columns that
let such a record name its ground truth, so a later phase can invalidate it by
that artifact instead of by the clock.

* ``anchors``      — ``JSONB NOT NULL DEFAULT '[]'::jsonb``. Zero or more typed
                     references to the ground truth this record asserts
                     something about. The initial vocabulary (plan §3.1) is five
                     discriminated shapes, each resolvable over a seam coord
                     already operates::

                         {"type": "blob", "repo": "...", "path": "...",
                          "sha": "<git blob sha>"}
                         {"type": "pr", "repo": "...", "number": 832}
                         {"type": "migration", "revision": "coord_memory_links"}
                         {"type": "schema", "object": "coord.memory_records.x"}
                         {"type": "flag", "name": "merge_rollout"}

* ``anchor_state`` — ``TEXT NOT NULL DEFAULT 'none'``, one of
                     ``none`` / ``fresh`` / ``moved`` / ``gone``. The watcher's
                     roll-up verdict across the array; **maintained by the
                     watcher, never by the writer**. ``gone`` only on unanimity
                     (plan §3.2), so a single dead anchor degrades a record to
                     the advisory ``moved`` rather than hiding it.

Design notes
============

* **The ``::jsonb`` casts are load-bearing, not decorative.** Comparing a
  ``jsonb`` column against an untyped ``'[]'`` literal in an index predicate
  leaves the operator unresolved (``anchors <> '[]'`` has no ``jsonb <>
  unknown`` candidate that PostgreSQL will pin down inside ``CREATE INDEX``'s
  immutability check). Every comparison of the array — here, and in Phase 3's
  decay ``WHERE`` and the watcher's enumeration — carries the explicit cast.
* **JSONB, not a side table.** Anchors are read as a whole with their record,
  never joined across records, and the vocabulary will churn. A side table
  would buy a join we never want and a migration per new anchor type.
* **Two indexes, two different questions.**
  ``idx_memory_records_anchors_gin`` is a default-``jsonb_ops`` GIN index
  serving the *reverse* containment lookup — "which records are anchored to
  repo X" — as ``anchors @> '[{"repo":"qontinui-web"}]'::jsonb``. It does
  **not** accelerate the watcher's enumeration of *distinct* anchors, which is
  a scan + ``jsonb_array_elements``; that is what the partial btree index
  ``idx_memory_records_tenant_anchor_state`` on ``(tenant_id, anchor_state)
  WHERE anchors <> '[]'::jsonb`` narrows, since anchored rows are expected to
  stay a small minority of the corpus for a long time.

  That partial index serves the ANCHORED side only — the watcher's
  enumeration and both halves of the ``anchor_gone_sweep``, all of which
  filter ``anchors <> '[]'::jsonb``. It emphatically does **not** serve
  Phase 3's decay exemption, whose predicate ``anchors = '[]'::jsonb`` is the
  index's exact COMPLEMENT: no row the exemption selects is in this index.
  (An earlier draft of this note claimed otherwise. The exemption needs no
  index of its own — ``decay_invalidate`` is a full-corpus sweep that has to
  visit every anchorless row anyway.)
* ``anchor_state`` is TEXT + a **named** CHECK rather than a PG enum — same
  rationale as the sibling ``scope`` / ``kind`` columns: text+CHECK evolves
  without ``ALTER TYPE`` acrobatics. It is named explicitly (rather than left
  to PostgreSQL's inline default) so ``downgrade`` and any future widening drop
  it by a name this file states, instead of one inferred from convention — the
  trap ``coord_memory_links`` had to work around for ``kind``.
* **Additive and inert.** ``ADD COLUMN ... NOT NULL DEFAULT`` is a metadata-only
  operation on PostgreSQL >= 11 (no table rewrite, no long lock). Existing rows
  read back ``anchors = []`` and ``anchor_state = 'none'``; nothing reads either
  column until Phase 2, so behaviour is byte-identical to today.
* Idempotency: every DDL uses ``IF NOT EXISTS`` / ``IF EXISTS`` so a re-run
  against an already-applied DB is a no-op.

Hand-written rather than autogenerated: ``alembic revision --autogenerate`` is
banned in this repo and ``./scripts/safe_migrate.sh`` does not exist here.

*Deploy order:* this migration must land and deploy **before** any coord build
that reads the columns — the 2026-07-13 missing-column incident class.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "coord_memory_anchors"
down_revision: str | Sequence[str] | None = "avac_01_agent_commands"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The watcher's roll-up vocabulary (plan §3.2). ``none`` is the anchorless
# default; ``fresh`` / ``moved`` / ``gone`` are watcher verdicts.
_ANCHOR_STATES = "'none', 'fresh', 'moved', 'gone'"

# Constraint / index names, stated once so upgrade and downgrade cannot drift.
_CK_ANCHOR_STATE = "memory_records_anchor_state_check"
_IX_ANCHORS_GIN = "idx_memory_records_anchors_gin"
_IX_TENANT_ANCHOR_STATE = "idx_memory_records_tenant_anchor_state"


def upgrade() -> None:
    """Add anchors + anchor_state to coord.memory_records, with both indexes."""
    # ----------------------------------------------------------------
    # 1. The two columns. Metadata-only on PG >= 11 — existing rows are
    #    served the defaults without a rewrite.
    # ----------------------------------------------------------------
    op.execute(
        """
        ALTER TABLE coord.memory_records
            ADD COLUMN IF NOT EXISTS anchors JSONB NOT NULL
                DEFAULT '[]'::jsonb,
            ADD COLUMN IF NOT EXISTS anchor_state TEXT NOT NULL
                DEFAULT 'none'
        """
    )

    # ----------------------------------------------------------------
    # 2. Named CHECK on anchor_state. Dropped-then-added so a re-run is
    #    a no-op; alembic runs the migration in one transaction, so no
    #    window exists where the column is unconstrained.
    # ----------------------------------------------------------------
    op.execute(
        f"""
        ALTER TABLE coord.memory_records
            DROP CONSTRAINT IF EXISTS {_CK_ANCHOR_STATE}
        """
    )
    op.execute(
        f"""
        ALTER TABLE coord.memory_records
            ADD CONSTRAINT {_CK_ANCHOR_STATE}
                CHECK (anchor_state IN ({_ANCHOR_STATES}))
        """
    )

    # ----------------------------------------------------------------
    # 3. Reverse containment lookup: "records anchored to repo X", as
    #    anchors @> '[{"repo": "qontinui-web"}]'::jsonb. Default
    #    jsonb_ops (not jsonb_path_ops) — the queries this serves match
    #    on keys as well as key/value pairs, and jsonb_path_ops cannot
    #    answer a key-existence probe.
    # ----------------------------------------------------------------
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_IX_ANCHORS_GIN}
            ON coord.memory_records USING gin (anchors)
        """
    )

    # ----------------------------------------------------------------
    # 4. The watcher's working set: anchored rows only, by tenant and
    #    state. Partial on the same '[]'::jsonb predicate the Phase 3
    #    decay exemption uses, so the planner can match it.
    # ----------------------------------------------------------------
    op.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {_IX_TENANT_ANCHOR_STATE}
            ON coord.memory_records (tenant_id, anchor_state)
            WHERE anchors <> '[]'::jsonb
        """
    )


def downgrade() -> None:
    """Reverse: drop both indexes, the CHECK, then both columns.

    Dropping the columns would take the indexes and the CHECK with them,
    but they are dropped explicitly first for symmetry with their
    explicit CREATEs — and so a partially-applied upgrade (indexes
    present, columns already gone by some other hand) still downgrades
    cleanly. Index names are schema-qualified: an index lives in its
    table's schema, and ``DROP INDEX`` does not resolve through
    ``search_path`` the way the table reference above does.
    """
    op.execute(f"DROP INDEX IF EXISTS coord.{_IX_TENANT_ANCHOR_STATE}")
    op.execute(f"DROP INDEX IF EXISTS coord.{_IX_ANCHORS_GIN}")
    op.execute(
        f"""
        ALTER TABLE coord.memory_records
            DROP CONSTRAINT IF EXISTS {_CK_ANCHOR_STATE}
        """
    )
    op.execute(
        """
        ALTER TABLE coord.memory_records
            DROP COLUMN IF EXISTS anchor_state,
            DROP COLUMN IF EXISTS anchors
        """
    )
