"""Add annotation tables.

Revision ID: d42d46b1738d
Revises: 93687f70383c
Create Date: 2025-11-12 18:48:36.123507

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d42d46b1738d"
down_revision: str | None = "93687f70383c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add annotation_sets and annotations tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotation_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("screenshot_name", sa.String(), nullable=False),
        sa.Column("screenshot_url", sa.String(), nullable=False),
        sa.Column("image_width", sa.Integer(), nullable=False),
        sa.Column("image_height", sa.Integer(), nullable=False),
        sa.Column("screenshots", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("boundary_width", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotation_sets_screenshot_name"),
        "annotation_sets",
        ["screenshot_name"],
        unique=False,
    )
    op.create_table(
        "annotations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("annotation_set_id", sa.UUID(), nullable=False),
        sa.Column("screenshot_index", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["annotation_set_id"], ["annotation_sets.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_annotations_screenshot_index"),
        "annotations",
        ["screenshot_index"],
        unique=False,
    )
    op.create_index(
        "ix_annotations_set_screenshot",
        "annotations",
        ["annotation_set_id", "screenshot_index"],
        unique=False,
    )
    # Drop analytics_events table and indexes if they exist
    # Use IF EXISTS to handle production database that may not have these
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_event_name")
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_name_timestamp")
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_timestamp")
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_timestamp_desc")
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_user_id")
    op.execute("DROP INDEX IF EXISTS ix_analytics_events_user_name")
    op.execute("DROP TABLE IF EXISTS analytics_events CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_device_sessions_user_id_fingerprint")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove annotation_sets and annotations tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_device_sessions_user_id_fingerprint"),
        "device_sessions",
        ["user_id", "device_fingerprint"],
        unique=False,
    )
    op.create_table(
        "analytics_events",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "event_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "properties",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("analytics_events_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("analytics_events_pkey")),
    )
    op.create_index(
        op.f("ix_analytics_events_user_name"),
        "analytics_events",
        ["user_id", "event_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_user_id"),
        "analytics_events",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_timestamp_desc"),
        "analytics_events",
        [sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_timestamp"),
        "analytics_events",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_name_timestamp"),
        "analytics_events",
        ["event_name", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_events_event_name"),
        "analytics_events",
        ["event_name"],
        unique=False,
    )
    op.drop_index("ix_annotations_set_screenshot", table_name="annotations")
    op.drop_index(op.f("ix_annotations_screenshot_index"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(
        op.f("ix_annotation_sets_screenshot_name"), table_name="annotation_sets"
    )
    op.drop_table("annotation_sets")
    # ### end Alembic commands ###
