"""coord.memory_records — add ``seq``, a monotone write-order key

Revision ID: memseq_01
Revises: coord_tenant_fk_01
Create Date: 2026-08-19

Phase 1 of plan
``2026-08-08-memory-stats-recent-titles-nondeterministic-recency-tiebreak``.

Why a new column exists at all
==============================

Several reads in ``app/services/memory_store.py`` order by
``created_at DESC, memory_id DESC`` and then apply a ``LIMIT``. That reads
like a determinism guard, and it is one — ``memory_id`` is the primary key,
so the order is *total* and the same corpus queried twice returns the
identical list. What it is **not** is recency-faithful: ``memory_id`` is
``gen_random_uuid()`` (``coord_memory_records.py:136``; ``insert_record``
proposes it client-side with ``uuid4()``, which is equally non-monotone), so
the moment two rows share a ``created_at`` the tiebreak orders them by a key
unrelated to write order.

Ties are the ORDINARY case, not a test artifact. ``insert_records_batch``
(``memory_store.py``) writes every item of a ``POST /memory/records``
request in one ``INSERT … FROM unnest(…)``, so all N rows carry the identical
transaction-start ``now()``. Measured on a throwaway ``pgvector:pg16``: one
25-record request produced **one** distinct ``created_at`` across all 25
rows, and ``/memory/stats``'s ``recent_titles`` came back as a pure
``memory_id DESC`` permutation — it dropped the SECOND-NEWEST record and kept
the OLDEST. The ``LIMIT 20`` cap therefore admits a write-order-arbitrary 20.

Why not reuse ``content_hash``
==============================

``memory_store.py:1280`` (the FTS arm) already carries a content-derived
tiebreak, and ``:1190-1194`` explains it: ``content_hash`` is identical across
machines and across a re-seed, where ``memory_id`` is reproducible only within
one corpus instance. That buys **stability**, which this order already has,
and it cannot recover write order — so it would leave "newest first" exactly
as false while making the test look fixed. There is no existing monotone
column to reuse: ``created_at`` / ``updated_at`` / ``valid_from`` are all
``TIMESTAMPTZ DEFAULT now()``, and ``updated_at`` moves on update, so it is
not write-order monotone either.

``seq`` is a real write-order key, reusable by any future changefeed or
``since``-cursor, and it removes the tie class instead of freezing it.

The backfill order is a RECONSTRUCTION, not the true write order
================================================================

Existing rows predate the column, and the true order in which they were
written is not recoverable — that is the whole defect. The backfill orders by
``(created_at, memory_id)``, which is the best available approximation:
``created_at`` is genuinely knowable, and ``memory_id`` only decides what
``created_at`` cannot separate — i.e. exactly the batch-written groups whose
internal order is unknown. **Do not read a historical row's ``seq`` as
evidence of write order within its batch.** From this revision forward the
identity supplies the real thing.

Five steps, in this order, and each is load-bearing
===================================================

1. ``ADD COLUMN seq BIGINT`` — nullable, no default, so it is metadata-only
   and does not rewrite the table.
2. Backfill by window function. Adding the column already
   ``GENERATED … AS IDENTITY`` in step 1 would have filled it in *heap*
   order, which is neither the true write order nor the reconstruction.
3. ``SET NOT NULL``. Load-bearing for the read path: a NULL in a
   ``seq DESC`` sort sorts FIRST, so a nullable column would put un-backfilled
   rows at the head of every "newest" sample.
4. ``ADD GENERATED BY DEFAULT AS IDENTITY`` plus a ``setval`` past the
   backfilled maximum, so the first new insert does not collide with a
   reconstructed value. ``BY DEFAULT`` rather than ``ALWAYS`` so a restore or
   a future backfill can write the column explicitly without ``OVERRIDING
   SYSTEM VALUE``.
5. ``UNIQUE INDEX`` on ``seq`` — the correctness guard for step 4's choice.

Steps 3 and 4 take ``ACCESS EXCLUSIVE`` and step 3 scans the table. The
corpus is tenant-quota-bounded (500k rows/tenant) and this is a one-shot cost.

One index, and it is a CORRECTNESS guard — not a plan optimisation
==================================================================

``list_records_page``'s keyset predicate ``(created_at, seq) < (:c, :s)`` is
only correct while ``(created_at, seq)`` is a TOTAL order — i.e. while ``seq``
is unique. An identity column creates **no** unique index of its own, and
``GENERATED BY DEFAULT`` (chosen above, on purpose) is exactly what permits an
explicit write that could mint a duplicate. Nothing in the tree writes ``seq``
today, so this is unreachable from application code; a restore or a hand-run
backfill is not. The failure it would cause — a page boundary that silently
skips or repeats a row — is the same defect class this revision exists to
close, so the invariant is ENFORCED rather than assumed. ``ALWAYS`` would not
have substituted for it: ``pg_restore`` writes identity columns with
``OVERRIDING SYSTEM VALUE`` regardless.

This index is a DIFFERENT object from the ``(tenant_id, seq DESC)`` index that
would turn the facets ``LIMIT 20`` into an index scan. That one is a plan
optimisation and is out of scope. This one cannot serve
``ORDER BY created_at DESC, seq DESC`` at all — a single-column ``seq`` index
provides no ordering over the leading ``created_at`` — so the read paths keep
their existing plan shape (``Seq Scan`` -> top-N heapsort -> ``Limit``),
confirmed with ``EXPLAIN`` before and after rather than assumed. See
``memory_store.py:1180-1189`` for a measured case in this same file where an
extra sort key destroyed an index scan; that is why the plan is checked, not
just the result.

Deploy order: migrate, THEN serve
=================================

``facets``, ``anchored_search`` and ``list_records_page`` all SELECT ``seq``
after this lands, so an application image serving BEFORE this revision applies
answers ``/memory/stats``, anchored retrieval and ``GET /memory/records`` with
an ``UndefinedColumn`` 500. That is the ordinary migrate-then-serve rollout the
web backend already performs; it is written down because the read paths are now
hard-dependent on the column rather than degrading. No coord-side (Rust) read
of ``seq`` is added, so the cross-repo migration-before-consumer ordering does
not apply — coord reads ``coord.memory_records`` only through explicit
count/sum columns, and its schema manifest gates on table presence, not
columns.

(The prose above deliberately never starts a line at column 0 with the bare
word ``revision`` or ``down_revision``. The ``alembic-heads-pr`` gate in
``.github/workflows/alembic-graph-pr.yml`` scans with line-anchored regexes
under ``re.M``; keep column-0 occurrences for the real assignments only.)
"""

from collections.abc import Sequence

from alembic import op

# The unique index name, spelled once so the DDL and the downgrade agree.
_UQ_SEQ = "uq_memory_records_seq"

# revision identifiers, used by Alembic.
# ``down_revision`` chains off the single web head at rebase time
# (``coord_tenant_fk_01``, which itself chains off ``obsappfill_01`` — this
# revision was authored against that earlier head and re-pointed rather than
# joined with a merge revision, so the chain stays linear). Keep this on ONE
# physical line and ``revision`` at
# column 0 — the ``alembic-heads-pr`` gate parses both with line-anchored
# regexes, so a wrapped tuple silently drops parents and manufactures a
# phantom extra head.
revision: str = "memseq_01"
down_revision: str | Sequence[str] | None = "coord_tenant_fk_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Add ``seq``, backfill it, then hand it to an identity sequence."""
    # ----------------------------------------------------------------
    # 1. Nullable, no default: metadata-only, no table rewrite.
    # ----------------------------------------------------------------
    op.execute(
        """
        ALTER TABLE coord.memory_records
            ADD COLUMN IF NOT EXISTS seq BIGINT
        """
    )

    # ----------------------------------------------------------------
    # 2. Backfill. (created_at, memory_id) is a RECONSTRUCTION of write
    #    order, not the true one — see the module docstring. Guarded on
    #    NULL so a re-run does not renumber rows the identity already
    #    served. NOTE: row_number() restarts at 1 for whatever the guard
    #    admits, it does NOT offset past max(seq) — which is safe only
    #    because alembic runs a revision in ONE transaction, so there is
    #    no way to observe (or resume from) a half-numbered table here.
    #    A future partial backfill must offset instead of restarting.
    # ----------------------------------------------------------------
    op.execute(
        """
        WITH ordered AS (
            SELECT memory_id,
                   row_number() OVER (ORDER BY created_at, memory_id) AS rn
            FROM coord.memory_records
            WHERE seq IS NULL
        )
        UPDATE coord.memory_records r
           SET seq = ordered.rn
          FROM ordered
         WHERE r.memory_id = ordered.memory_id
        """
    )

    # ----------------------------------------------------------------
    # 3. NOT NULL. A NULL sorts FIRST under ``seq DESC``, so leaving the
    #    column nullable would hand every "newest" sample to the rows
    #    that have no write-order key at all.
    # ----------------------------------------------------------------
    op.execute(
        """
        ALTER TABLE coord.memory_records
            ALTER COLUMN seq SET NOT NULL
        """
    )

    # ----------------------------------------------------------------
    # 4. Identity, then advance the sequence past the backfill so the
    #    first real insert cannot collide with a reconstructed value.
    #    The DO block makes the ALTER a no-op on a re-run (there is no
    #    ``ADD GENERATED … IF NOT EXISTS``).
    # ----------------------------------------------------------------
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_attribute
                WHERE attrelid = 'coord.memory_records'::regclass
                  AND attname = 'seq'
                  AND attidentity <> ''
            ) THEN
                ALTER TABLE coord.memory_records
                    ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$
        """
    )
    op.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('coord.memory_records', 'seq'),
            COALESCE((SELECT max(seq) FROM coord.memory_records), 0) + 1,
            false
        )
        """
    )

    # ----------------------------------------------------------------
    # 5. Enforce the uniqueness the keyset cursor depends on. An identity
    #    column brings no unique index of its own, and BY DEFAULT admits
    #    an explicit write (restore, hand-run backfill) that could mint a
    #    duplicate. See the module docstring — this is a correctness
    #    guard, NOT the (tenant_id, seq DESC) plan index, which stays out
    #    of scope.
    # ----------------------------------------------------------------
    op.execute(
        f"""
        CREATE UNIQUE INDEX IF NOT EXISTS {_UQ_SEQ}
            ON coord.memory_records (seq)
        """
    )


def downgrade() -> None:
    """Drop ``seq`` (its identity sequence AND its unique index are owned by
    the column and go with it).

    Lossy in the same sense every column drop is: the write order the
    identity recorded after this revision applied is not recoverable, and a
    re-``upgrade()`` reconstructs from ``(created_at, memory_id)`` again.
    """
    op.execute(
        """
        ALTER TABLE coord.memory_records
            DROP COLUMN IF EXISTS seq
        """
    )
