"""overview.* — documents and wiki: pages, page_versions, page_links, files

Revision ID: overview_03_documents_and_wiki
Revises: coord_iops_idx_01
Create Date: 2026-09-26

Phase 2 of ``2026-09-20-overview-authoring-layer`` (the overview plan's Phase 7
data model): the content a business leader reads and writes on the Documents
and Wiki pages, on the authoring contract that Phase 1 built.

``overview.pages``
    One markdown page. ``kind`` is ``document``, ``wiki`` or ``slides`` — slides
    arrive in a later phase, but the kind is admitted now because widening a
    CHECK later needs a DROP, which coord's migration classifier will not land
    unattended. ``(tenant_id, kind, slug)`` is unique. ``current_version`` is
    the version a write must name (``If-Match``). ``search_tsv`` is the stored
    full-text vector over title and body, generated by Postgres so the search
    query, its ranking and the GIN index all read one column rather than
    recomputing a vector per row.

``overview.page_versions``
    Append-only: every content write stores the page as it then stood — the
    whole snapshot, so a revert restores exactly what was there.

``overview.page_links``
    What a page points at, by ``(to_kind, to_slug)`` rather than by id, so a
    wiki link to a page nobody has written yet is still recorded (and becomes a
    backlink the moment that page exists). ``link_type`` is ``wiki`` (a
    ``[[Title]]`` in the body, derived on every save) or ``related`` (a
    document's declared related documents).

``overview.files``
    An uploaded file's metadata; the bytes live in object storage under
    ``storage_key``. ``sha256`` is the stored bytes' digest. ``page_id`` attaches
    it to a document and is set NULL, never cascaded, when that page goes — a
    file outlives the page that listed it.

Written to be provably additive for coord's migration classifier: guarded
``CREATE TABLE IF NOT EXISTS`` (constraints inline, which the classifier admits
because a new table holds no rows), and every index ``CONCURRENTLY IF NOT
EXISTS`` inside ``autocommit_block``.
"""

from collections.abc import Sequence

from alembic import op

revision: str = "overview_03_documents_and_wiki"
down_revision: str | Sequence[str] | None = "coord_iops_idx_01"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS overview.pages (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id uuid NOT NULL,
            kind text NOT NULL,
            slug text NOT NULL,
            title text NOT NULL,
            body_md text NOT NULL DEFAULT '',
            doc_number text,
            doc_status text,
            owner text,
            current_version integer NOT NULL DEFAULT 1,
            created_by text,
            updated_by text,
            created_at timestamptz NOT NULL DEFAULT now(),
            updated_at timestamptz NOT NULL DEFAULT now(),
            search_tsv tsvector GENERATED ALWAYS AS (
                to_tsvector('simple'::regconfig, title || ' ' || body_md)
            ) STORED,
            CONSTRAINT ck_overview_pages_kind
                CHECK (kind IN ('document', 'wiki', 'slides')),
            CONSTRAINT uq_overview_pages_slug UNIQUE (tenant_id, kind, slug)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS overview.page_versions (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id uuid NOT NULL,
            page_id uuid NOT NULL
                REFERENCES overview.pages (id) ON DELETE CASCADE,
            version integer NOT NULL,
            title text NOT NULL,
            body_md text NOT NULL,
            doc_number text,
            doc_status text,
            owner text,
            created_by text,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_overview_page_versions UNIQUE (page_id, version)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS overview.page_links (
            tenant_id uuid NOT NULL,
            from_page_id uuid NOT NULL
                REFERENCES overview.pages (id) ON DELETE CASCADE,
            to_kind text NOT NULL,
            to_slug text NOT NULL,
            link_type text NOT NULL,
            CONSTRAINT ck_overview_page_links_type
                CHECK (link_type IN ('wiki', 'related')),
            CONSTRAINT ck_overview_page_links_kind
                CHECK (to_kind IN ('document', 'wiki', 'slides')),
            CONSTRAINT pk_overview_page_links
                PRIMARY KEY (from_page_id, to_kind, to_slug, link_type)
        )
        """
    )
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS overview.files (
            id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
            tenant_id uuid NOT NULL,
            page_id uuid
                REFERENCES overview.pages (id) ON DELETE SET NULL,
            filename text NOT NULL,
            content_type text NOT NULL,
            size_bytes bigint NOT NULL,
            sha256 text NOT NULL,
            storage_key text NOT NULL,
            uploaded_by text,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_overview_files_size CHECK (size_bytes >= 0)
        )
        """
    )
    with op.get_context().autocommit_block():
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_overview_pages_tenant_kind "
            "ON overview.pages (tenant_id, kind, title)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_overview_pages_search "
            "ON overview.pages USING gin (search_tsv)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_overview_page_links_target "
            "ON overview.page_links (tenant_id, to_kind, to_slug)"
        )
        op.execute(
            "CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_overview_files_tenant "
            "ON overview.files (tenant_id, page_id)"
        )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS overview.files")
    op.execute("DROP TABLE IF EXISTS overview.page_links")
    op.execute("DROP TABLE IF EXISTS overview.page_versions")
    op.execute("DROP TABLE IF EXISTS overview.pages")
