"""tighten runner schema after unify_runner_concepts

Revision ID: tighten_runner_schema
Revises: unify_runner_concepts
Create Date: 2026-04-28

Follow-up to :mod:`unify_runner_concepts`. Removes the now-cosmetic
``server_mode`` and ``dispatch_secret`` columns from ``runner.runners``
(no readers after Phase 2/5 unified the dispatch path onto WebSocket)
and renames the sequence to match the renamed table.

Changes
-------

1. Rename ``runner.runner_connections_id_seq`` →
   ``runner.runner_sessions_id_seq``. Postgres doesn't auto-rename
   sequences when you ``ALTER TABLE … RENAME``; this just brings the
   sequence name in line with the table.

2. Drop ``runner.runners.server_mode``. Phase 2's dispatcher dropped
   the ``server_mode = true`` filter; nothing reads the column now.

3. Drop ``runner.runners.dispatch_secret``. Phase 5A deleted the
   HTTP-with-bearer dispatch path; the WS dispatch channel doesn't
   need a per-runner secret because the WS itself is authenticated.

The downgrade re-adds both columns and the sequence-rename, but
``dispatch_secret`` rows must be regenerated by re-registering each
runner — the original values aren't recoverable.

Idempotency
-----------
Each step is wrapped in ``information_schema`` / ``pg_class``
existence checks so re-applying after a partial fail is a no-op.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "tighten_runner_schema"
down_revision: str = "unify_runner_concepts"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_RENAME_SEQUENCE = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname = 'runner'
          AND c.relname = 'runner_connections_id_seq'
    ) AND NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname = 'runner'
          AND c.relname = 'runner_sessions_id_seq'
    ) THEN
        ALTER SEQUENCE runner.runner_connections_id_seq
            RENAME TO runner_sessions_id_seq;
        RAISE NOTICE 'Renamed sequence runner_connections_id_seq -> runner_sessions_id_seq';
    END IF;
END $$;
"""


_REVERSE_RENAME_SEQUENCE = """
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname = 'runner'
          AND c.relname = 'runner_sessions_id_seq'
    ) AND NOT EXISTS (
        SELECT 1 FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE c.relkind = 'S'
          AND n.nspname = 'runner'
          AND c.relname = 'runner_connections_id_seq'
    ) THEN
        ALTER SEQUENCE runner.runner_sessions_id_seq
            RENAME TO runner_connections_id_seq;
    END IF;
END $$;
"""


def _drop_column_if_exists(column: str) -> str:
    return f"""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'runner'
          AND table_name = 'runners'
          AND column_name = '{column}'
    ) THEN
        ALTER TABLE runner.runners DROP COLUMN {column};
        RAISE NOTICE 'Dropped runner.runners.{column}';
    END IF;
END $$;
"""


def upgrade() -> None:
    op.execute(_RENAME_SEQUENCE)
    op.execute(_drop_column_if_exists("server_mode"))
    op.execute(_drop_column_if_exists("dispatch_secret"))


def downgrade() -> None:
    # no-op'd post-consolidation; revision is in applied history, no DB will re-run it
    pass
