"""coord.verified_advances — the ledger behind each repo's ``verified`` branch

Revision ID: verified_adv_01_coord_verified_advances
Revises: coord_smckpt_01_success_metric_checkpoint_results
Create Date: 2026-10-07

Phase 1.1 of plan
``qontinui-dev-notes/plans/2026-10-01-main-is-three-things-split-landed-from-verified.md``,
**qontinui-web alembic half only**. The writer (coord's ``verified_ref.rs``
evaluator, Phase 1.2) and the ``refs/heads/verified`` publisher (Phase 2) are
separate ``qontinui-coord`` PRs that land after this one.

What a row is
=============
Per plan D1, every coord-authority repo gets a ``refs/heads/verified`` branch
that only coord writes, fast-forward only (D3), and that marks the newest
``main`` sha whose required checks are green on an equal tree (D2). This table
records every advance of that branch: **one row per advance**, written only by
coord. The newest row per ``repo`` is the current verified sha; ``prev_sha``
chains each row to the one before it, so the ledger is also the advance history
behind D7's ``coord_verified_advances_total{repo,basis}`` and lag metrics. A
repo with no row yet is in bootstrap, and every consumer falls back to ``main``
and says so (D9).

Columns (the contract coord's Rust code is written against — do not rename)
===========================================================================
* ``id BIGSERIAL PRIMARY KEY``.
* ``tenant_id UUID NOT NULL`` — no FK, like every sibling ``coord.*`` table.
* ``repo TEXT NOT NULL`` — ``owner/name``, e.g. ``qontinui/qontinui-coord``.
* ``sha TEXT NOT NULL`` — the newly verified ``main`` sha (40-hex).
* ``prev_sha TEXT NULL`` — the previous verified sha for the repo; NULL on the
  bootstrap row.
* ``tree_sha TEXT NULL`` — the git tree of ``sha``; D2 matches evidence by tree.
* ``basis TEXT NOT NULL`` — which evidence verified it, CHECK
  ``candidate | pr_head | main_push | rerun | path_inherited`` (D2 / D7's
  ``basis`` label set).
* ``evidence JSONB NOT NULL DEFAULT '{}'`` — the check runs and refs relied on.
* ``advanced_at TIMESTAMPTZ NOT NULL DEFAULT now()`` — server clock.

Constraints and index
=====================
* ``ck_verified_advances_basis`` — the five-value ``basis`` vocabulary.
* ``uq_verified_advances_repo_sha`` — ``UNIQUE (repo, sha)``: a sha is verified
  at most once per repo, which makes coord's insert idempotent
  (``ON CONFLICT (repo, sha) DO NOTHING``).
* ``verified_advances_repo_advanced_at_idx`` on ``(repo, advanced_at DESC)`` —
  the "current verified sha per repo" read and one repo's advance history.
  Built ``CREATE INDEX CONCURRENTLY IF NOT EXISTS`` inside
  ``op.get_context().autocommit_block()`` as a static literal: the form coord's
  merge-train migration classifier
  (``qontinui-coord/crates/coord/src/pr_merge/migration_classifier.rs``) admits
  for a standalone index build (precedent
  ``coord_smckpt_01_success_metric_checkpoint_results``). A KILLED concurrent
  build leaves an INVALID index that ``IF NOT EXISTS`` would then skip — check
  ``pg_index.indisvalid`` and ``DROP INDEX`` + re-run if it is invalid.

Idempotency
===========
``CREATE TABLE IF NOT EXISTS`` / ``CREATE INDEX … IF NOT EXISTS`` /
``DROP … IF EXISTS`` throughout, so a re-run is a no-op. The CHECK and UNIQUE
are inline so they ride the table's guard. No ``lock_timeout``: every
statement creates a NEW object.

Deploy ordering (load-bearing)
==============================
Served policy ``production-and-cost`` ``alembic-sole-authorship``: alembic is
the sole author of ``coord.*`` schema, and a coord read or write of a new
``coord.*`` object needs its qontinui-web migration to land FIRST. This revision
lands and deploys before the coord PR that writes and reads the table.

Hand-written rather than autogenerated (same served clause). ``down_revision``
is the local head at authoring time; coord re-points it at land time if the
head moves — re-point it, do NOT author an ``alembic merge`` revision.
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "verified_adv_01_coord_verified_advances"
down_revision: str | Sequence[str] | None = (
    "coord_smckpt_01_success_metric_checkpoint_results"
)
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create coord.verified_advances + its (repo, advanced_at DESC) index."""
    # Kept for the same collision-safety reason every sibling coord.*
    # revision keeps it.
    op.execute("CREATE SCHEMA IF NOT EXISTS coord")

    # ----------------------------------------------------------------
    # 1. The table. Raw SQL, as in every sibling coord.* revision: the
    #    IF NOT EXISTS guard and the named inline CHECK / UNIQUE want to
    #    be stated literally.
    # ----------------------------------------------------------------
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS coord.verified_advances (
            id           BIGSERIAL PRIMARY KEY,
            tenant_id    UUID NOT NULL,
            repo         TEXT NOT NULL,
            sha          TEXT NOT NULL,
            prev_sha     TEXT NULL,
            tree_sha     TEXT NULL,
            basis        TEXT NOT NULL,
            evidence     JSONB NOT NULL DEFAULT '{}'::jsonb,
            advanced_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

            CONSTRAINT ck_verified_advances_basis
                CHECK (basis IN ('candidate',
                                 'pr_head',
                                 'main_push',
                                 'rerun',
                                 'path_inherited')),

            -- A sha is verified at most once per repo: coord's
            -- ON CONFLICT (repo, sha) DO NOTHING key.
            CONSTRAINT uq_verified_advances_repo_sha
                UNIQUE (repo, sha)
        )
        """
    )

    op.execute(
        """
        COMMENT ON TABLE coord.verified_advances IS
            'Ledger behind the per-repo refs/heads/verified branch: one row per advance of that branch, written only by coord (verified_ref evaluator). The newest row per repo is the current verified sha; prev_sha chains each advance to the one before (NULL on bootstrap); basis names the evidence (candidate | pr_head | main_push | rerun | path_inherited) and evidence carries it. A repo with no row is in bootstrap and consumers fall back to main. Plan 2026-10-01-main-is-three-things-split-landed-from-verified, Phase 1.'
        """
    )

    # ----------------------------------------------------------------
    # 2. Current verified sha per repo + advance history. A static
    #    literal, CONCURRENTLY, in an autocommit_block: the index build
    #    coord's migration classifier admits (docstring).
    # ----------------------------------------------------------------
    with op.get_context().autocommit_block():
        op.execute(
            """
            CREATE INDEX CONCURRENTLY IF NOT EXISTS
                verified_advances_repo_advanced_at_idx
            ON coord.verified_advances (repo, advanced_at DESC)
            """
        )


def downgrade() -> None:
    """Reverse: drop the index, then the table (and every recorded advance).

    The index name is schema-qualified because ``coord`` is not on the
    migration connection's ``search_path``. Nothing references this table.
    """
    op.execute("DROP INDEX IF EXISTS coord.verified_advances_repo_advanced_at_idx")
    op.execute("DROP TABLE IF EXISTS coord.verified_advances")
