"""wave 6 01 coord.merge_batches — bors-style batching state

Revision ID: wave_6_01_coord_merge_batches
Revises: row_10_item_8_01_spec_check_run_id
Create Date: 2026-05-16

Wave 6 of the branch-per-agent bottlenecks tracker, Row 3 lockfile-half
(bors-style batching). Mirrors the coord-side self-heal at
``qontinui-coord/src/merge_scheduler.rs::ensure_merge_batches_table``
(shipped in coord PR #19, ``fcb9119``). The Rust scheduler already
runs an idempotent ``CREATE TABLE IF NOT EXISTS`` + ``ALTER TABLE
ADD COLUMN IF NOT EXISTS`` pass on every startup; this migration is
the authoritative alembic record so a fresh canonical PG ends up with
the same shape without depending on a coord boot.

## Why two artifacts (self-heal + alembic)?

Standard pattern across this repo:

* coord's self-heal exists so coord can start against an arbitrarily
  back-leveled canonical PG and immediately function (see
  [[feedback_canonical_db_behind_alembic]]).
* alembic carries the authoritative shape so a clean ``alembic
  upgrade head`` against an empty database recreates the same
  schema, and so the diff-against-autogenerate workflow knows what's
  in scope.

The two **must** stay in lockstep. Schema changes here must be
mirrored in ``ensure_merge_batches_table`` and vice versa.

## Schema rationale

* ``batch_id`` UUID PK. Generated by the scheduler at batch-formation
  time (``Uuid::now_v7``); we never INSERT one server-side.
* ``parent_batch_id`` UUID nullable. Set on bisect halves to point at
  the failed parent batch — the bisect lineage. Indexed (partial,
  ``WHERE NOT NULL``) so the events-stream can walk a parent's
  children.
* ``status`` TEXT + CHECK. Same rationale as
  ``row_9_phase_4_01_coord_alerts`` — text+CHECK evolves cleanly
  without ``ALTER TYPE``. Allowed values mirror the lifecycle in the
  ``merge_scheduler.rs`` module doc:
    - ``awaiting-ci`` — candidate-batch ref pushed, watching CI
    - ``landing``    — CI green, fast-forwarding main
    - ``merged``     — atomic land succeeded, all members merged
    - ``bisecting``  — CI red, parent split into halves
    - ``failed``     — bisect bottomed out OR rollback path
* ``candidate_ref`` + ``combined_tip`` TEXT NULL. The git ref that
  CI runs against and the rebased tip it points to. NULL until the
  scheduler's first push for the batch succeeds.
* ``ci_attempt`` INTEGER. Incremented on every flake-retry; bisect
  begins only after ``ci_attempt >= QONTINUI_COORD_MERGE_CI_RETRY_CAP``
  (default 3, per [[feedback_autonomous_commit_ship]]).
* ``error`` TEXT NULL. The most recent failure reason (CI failure
  detail, bisect rationale, rollback message). Carries between
  state transitions.

Indices:

* ``idx_merge_batches_status`` — the dispatch loop reads
  ``status='awaiting-ci'`` every tick; a plain b-tree on the column
  keeps the scan cheap as the table grows historically.
* ``idx_merge_batches_parent`` (partial) — fed when a bisect lands
  to compute children of a failed parent.

## ``coord.merge_proposals.batch_id``

Companion column added in the same revision (one-shot Wave-6
schema change). NULL when the proposal is owned by the singleton
dispatch path; non-NULL UUID when an in-flight batch claims it.
``next_queued()`` filters ``batch_id IS NULL`` so the singleton and
batch paths never fight on the same row (Wave 6 invariant).

A partial index ``idx_merge_proposals_batch`` lets the scheduler's
``load_batch_members`` query (and the dashboard's batch-detail view)
walk a batch's members without touching the much larger main table.

## Chains off ``row_10_item_8_01_spec_check_run_id``

The current single head of the coord-merge lineage post-Wave-5:

    coord_phase_3_01_merge_proposals
      └─ wave_3_merge_phase_3_and_row_9_phase_3
        └─ row_9_phase_4_01_coord_alerts
          └─ row_10_item_8_01_spec_check_run_id   ← previous head
            └─ wave_6_01_coord_merge_batches      ← this revision

No sibling-head merge needed — at the time of authoring nothing else
in Wave 6 adds a migration off this same parent. Per
[[feedback_alembic_sibling_head_merge]], any concurrent Wave 6 PR
that also lands an alembic migration here must add an empty merge
revision joining the two heads.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "wave_6_01_coord_merge_batches"
down_revision: str = "row_10_item_8_01_spec_check_run_id"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Allowed statuses — keep in sync with
# ``qontinui-coord/src/merge_scheduler.rs::ensure_merge_batches_table``
# and the BatchRow lifecycle states documented in the same module.
_STATUSES = (
    "awaiting-ci",
    "landing",
    "merged",
    "bisecting",
    "failed",
)


def upgrade() -> None:
    op.create_table(
        "merge_batches",
        sa.Column(
            "batch_id",
            postgresql.UUID(as_uuid=True),
            primary_key=True,
        ),
        sa.Column(
            "parent_batch_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("candidate_ref", sa.Text(), nullable=True),
        sa.Column("combined_tip", sa.Text(), nullable=True),
        sa.Column(
            "ci_attempt",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("0"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('awaiting-ci','landing','merged','bisecting','failed')",
            name="merge_batches_status_chk",
        ),
        schema="coord",
    )

    # Dispatch-loop hot query: every tick reads
    # ``status='awaiting-ci'``. Plain b-tree on the column.
    op.create_index(
        "idx_merge_batches_status",
        "merge_batches",
        ["status"],
        schema="coord",
    )

    # Bisect lineage walk. Most rows have NULL here (no parent), so the
    # partial form keeps the index tight.
    op.create_index(
        "idx_merge_batches_parent",
        "merge_batches",
        ["parent_batch_id"],
        schema="coord",
        postgresql_where=sa.text("parent_batch_id IS NOT NULL"),
    )

    # Companion column on coord.merge_proposals — see module doc.
    op.add_column(
        "merge_proposals",
        sa.Column(
            "batch_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        schema="coord",
    )

    # Partial index — only non-null rows are queryable; matches the
    # ``WHERE batch_id IS NOT NULL`` predicate used by
    # ``load_batch_members`` and the dashboard's batch-detail view.
    op.create_index(
        "idx_merge_proposals_batch",
        "merge_proposals",
        ["batch_id"],
        schema="coord",
        postgresql_where=sa.text("batch_id IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index(
        "idx_merge_proposals_batch",
        table_name="merge_proposals",
        schema="coord",
    )
    op.drop_column("merge_proposals", "batch_id", schema="coord")
    op.drop_index(
        "idx_merge_batches_parent",
        table_name="merge_batches",
        schema="coord",
    )
    op.drop_index(
        "idx_merge_batches_status",
        table_name="merge_batches",
        schema="coord",
    )
    op.drop_table("merge_batches", schema="coord")


# Touch the symbol so linters don't strip it — same pattern as
# row_9_phase_4_01_coord_alerts.
_ = _STATUSES
