/**
 * Model Cost Comparison — the dataset
 *
 * ⚠️ AGENT-MAINTAINED FILE. This file is regenerated by the
 * /update-model-costs slash command (.claude/commands/update-model-costs.md).
 * Keep the structure stable: update values, sources, and COMPARISON_DATE;
 * add/remove models and plans as the market changes. Types and calculation
 * helpers live in ./types.ts and ./calc.ts and should rarely change.
 *
 * Ground rules for the data:
 * - API prices are official pay-as-you-go list prices in USD per 1M tokens
 *   (base context tier). `verified: false` marks numbers that could not be
 *   confirmed against an official vendor page.
 * - No vendor publishes exact token quotas for consumer subscriptions.
 *   Every `tokensPerMonthM` is therefore an ESTIMATE (`tokensEstimated: true`)
 *   with the derivation in `notes`. Official multiplier relationships
 *   (e.g. Claude Max 20x = 20× Pro) are preserved exactly.
 * - `publishedPrices` holds region-specific prices actually observed
 *   (usually VAT-inclusive); other currencies are FX-converted from USD.
 */

import type { Currency, ModelPricing, SubscriptionPlan } from "./types";

/** The date this dataset was last researched and verified. */
export const COMPARISON_DATE = "2026-07-17";

/** Mid-market FX rates on the comparison date (source: x-rates.com / mtfxgroup.com). */
export const CURRENCIES: Currency[] = [
  { code: "USD", symbol: "$", name: "US Dollar", perUsd: 1 },
  { code: "EUR", symbol: "€", name: "Euro", perUsd: 0.87 },
  { code: "GBP", symbol: "£", name: "British Pound", perUsd: 0.75 },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", perUsd: 162 },
];

/**
 * Default number of tokens (millions) for the comparison: the estimated
 * monthly allotment of the Claude Code Max 20x plan.
 */
export const DEFAULT_TOKENS_M = 200;

/** Default output-token share of the total (25% output / 75% input). */
export const DEFAULT_OUTPUT_SHARE = 0.25;

export const MODELS: ModelPricing[] = [
  // ── Anthropic ────────────────────────────────────────────────────────────
  {
    id: "claude-fable-5",
    name: "Claude Fable 5",
    provider: "Anthropic",
    inputPerMTokUsd: 10,
    outputPerMTokUsd: 50,
    cacheReadPerMTokUsd: 1,
    leaderboards: { lmarenaElo: 1507, aaIntelligenceIndex: 60, sweBenchVerified: 95.0 },
    source: "https://platform.claude.com/docs/en/about-claude/models/overview",
    verified: true,
    notes: "1M context. #1 on LMArena text and AA Index as of the comparison date.",
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "Anthropic",
    inputPerMTokUsd: 5,
    outputPerMTokUsd: 25,
    cacheReadPerMTokUsd: 0.5,
    leaderboards: { lmarenaElo: 1483, aaIntelligenceIndex: 56, sweBenchVerified: 88.6 },
    source: "https://platform.claude.com/docs/en/about-claude/models/overview",
    verified: true,
    notes: "Elo is the thinking variant (base 1476).",
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    provider: "Anthropic",
    inputPerMTokUsd: 3,
    outputPerMTokUsd: 15,
    cacheReadPerMTokUsd: 0.3,
    leaderboards: { aaIntelligenceIndex: 53, sweBenchVerified: 85.2 },
    source: "https://platform.claude.com/docs/en/about-claude/models/overview",
    verified: true,
    notes: "Introductory pricing $2/$10 through 2026-08-31; sticker price shown.",
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "Anthropic",
    inputPerMTokUsd: 3,
    outputPerMTokUsd: 15,
    leaderboards: { lmarenaElo: 1471 },
    source: "https://platform.claude.com/docs/en/about-claude/models/overview",
    verified: true,
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "Anthropic",
    inputPerMTokUsd: 1,
    outputPerMTokUsd: 5,
    cacheReadPerMTokUsd: 0.1,
    leaderboards: { aaIntelligenceIndex: 30 },
    source: "https://platform.claude.com/docs/en/about-claude/models/overview",
    verified: true,
    notes: "AA score is the reasoning variant (base 24). 200K context.",
  },
  // ── OpenAI ───────────────────────────────────────────────────────────────
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6 Sol",
    provider: "OpenAI",
    inputPerMTokUsd: 5,
    outputPerMTokUsd: 30,
    cacheReadPerMTokUsd: 0.5,
    leaderboards: { lmarenaElo: 1486, aaIntelligenceIndex: 58 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
    notes: "Current OpenAI flagship (GPT-5.6 family, launched 2026-07-09). AA score at xhigh effort.",
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6 Terra",
    provider: "OpenAI",
    inputPerMTokUsd: 2.5,
    outputPerMTokUsd: 15,
    cacheReadPerMTokUsd: 0.25,
    leaderboards: { aaIntelligenceIndex: 52 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6 Luna",
    provider: "OpenAI",
    inputPerMTokUsd: 1,
    outputPerMTokUsd: 6,
    cacheReadPerMTokUsd: 0.1,
    leaderboards: { aaIntelligenceIndex: 51 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    provider: "OpenAI",
    inputPerMTokUsd: 5,
    outputPerMTokUsd: 30,
    cacheReadPerMTokUsd: 0.5,
    leaderboards: { lmarenaElo: 1482, aaIntelligenceIndex: 55 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
    notes: "Previous flagship. AA score at xhigh effort.",
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3 Codex",
    provider: "OpenAI",
    inputPerMTokUsd: 1.75,
    outputPerMTokUsd: 14,
    cacheReadPerMTokUsd: 0.175,
    leaderboards: { sweBenchVerified: 85.0 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
    notes: "Coding-specialized.",
  },
  {
    id: "gpt-5.4-mini",
    name: "GPT-5.4 mini",
    provider: "OpenAI",
    inputPerMTokUsd: 0.75,
    outputPerMTokUsd: 4.5,
    cacheReadPerMTokUsd: 0.075,
    leaderboards: { aaIntelligenceIndex: 40 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
  },
  {
    id: "gpt-5.4-nano",
    name: "GPT-5.4 nano",
    provider: "OpenAI",
    inputPerMTokUsd: 0.2,
    outputPerMTokUsd: 1.25,
    cacheReadPerMTokUsd: 0.02,
    leaderboards: { aaIntelligenceIndex: 38 },
    source: "https://developers.openai.com/api/docs/pricing",
    verified: true,
  },
  // ── Google ───────────────────────────────────────────────────────────────
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "Google",
    inputPerMTokUsd: 2,
    outputPerMTokUsd: 12,
    cacheReadPerMTokUsd: 0.2,
    leaderboards: { lmarenaElo: 1485, aaIntelligenceIndex: 46 },
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    verified: true,
    notes: "Prompts >200K tokens cost $4/$18.",
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini 3.5 Flash",
    provider: "Google",
    inputPerMTokUsd: 1.5,
    outputPerMTokUsd: 9,
    cacheReadPerMTokUsd: 0.15,
    leaderboards: { lmarenaElo: 1476, aaIntelligenceIndex: 50 },
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    verified: true,
    notes: "Elo at high effort.",
  },
  {
    id: "gemini-3.1-flash-lite",
    name: "Gemini 3.1 Flash-Lite",
    provider: "Google",
    inputPerMTokUsd: 0.25,
    outputPerMTokUsd: 1.5,
    cacheReadPerMTokUsd: 0.025,
    leaderboards: {},
    source: "https://ai.google.dev/gemini-api/docs/pricing",
    verified: true,
  },
  // ── xAI ──────────────────────────────────────────────────────────────────
  {
    id: "grok-4.5",
    name: "Grok 4.5",
    provider: "xAI",
    inputPerMTokUsd: 2,
    outputPerMTokUsd: 6,
    cacheReadPerMTokUsd: 0.5,
    leaderboards: { aaIntelligenceIndex: 54 },
    source: "https://docs.x.ai/docs/models",
    verified: true,
    notes: "500K context; prompts ≥200K tokens cost $4/$12.",
  },
  {
    id: "grok-4.20",
    name: "Grok 4.20",
    provider: "xAI",
    inputPerMTokUsd: 1.25,
    outputPerMTokUsd: 2.5,
    cacheReadPerMTokUsd: 0.2,
    leaderboards: { lmarenaElo: 1474, sweBenchVerified: 76.7 },
    source: "https://docs.x.ai/docs/models",
    verified: true,
    notes: "1M context; base tier pricing.",
  },
  // ── DeepSeek ─────────────────────────────────────────────────────────────
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    provider: "DeepSeek",
    inputPerMTokUsd: 0.435,
    outputPerMTokUsd: 0.87,
    leaderboards: { aaIntelligenceIndex: 44 },
    source: "https://api-docs.deepseek.com/quick_start/pricing",
    verified: true,
    notes: "Cache-hit input pricing unconfirmed.",
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    provider: "DeepSeek",
    inputPerMTokUsd: 0.14,
    outputPerMTokUsd: 0.28,
    leaderboards: { aaIntelligenceIndex: 40 },
    source: "https://api-docs.deepseek.com/quick_start/pricing",
    verified: true,
  },
  // ── Alibaba ──────────────────────────────────────────────────────────────
  {
    id: "qwen3.7-max",
    name: "Qwen3.7 Max",
    provider: "Alibaba",
    inputPerMTokUsd: 2.5,
    outputPerMTokUsd: 7.5,
    leaderboards: { lmarenaElo: 1475, aaIntelligenceIndex: 46 },
    source: "https://www.alibabacloud.com/help/en/model-studio/model-pricing",
    verified: true,
    notes: "50% limited-time discount active ($1.25/$3.75). Tiered by prompt size.",
  },
  // ── Mistral ──────────────────────────────────────────────────────────────
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "Mistral",
    inputPerMTokUsd: 0.5,
    outputPerMTokUsd: 1.5,
    leaderboards: {},
    source: "https://mistral.ai/pricing/api/",
    verified: true,
    notes:
      "Official API price list; Mistral's own FAQ still shows an older $2/$6 example. Official EUR prices also published.",
  },
  {
    id: "mistral-medium-3.5",
    name: "Mistral Medium 3.5",
    provider: "Mistral",
    inputPerMTokUsd: 1.5,
    outputPerMTokUsd: 7.5,
    leaderboards: {},
    source: "https://mistral.ai/pricing/api/",
    verified: true,
  },
  // ── Meta (via Together AI — no first-party API) ──────────────────────────
  {
    id: "llama-4-maverick",
    name: "Llama 4 Maverick",
    provider: "Meta (Together AI)",
    inputPerMTokUsd: 0.27,
    outputPerMTokUsd: 0.85,
    leaderboards: { aaIntelligenceIndex: 14 },
    source: "https://www.together.ai/pricing",
    verified: true,
    notes: "Meta sells no first-party API; Together AI serverless rates. 1M context.",
  },
  // ── Amazon ───────────────────────────────────────────────────────────────
  {
    id: "nova-premier",
    name: "Amazon Nova Premier",
    provider: "Amazon",
    inputPerMTokUsd: 2.5,
    outputPerMTokUsd: 12.5,
    leaderboards: {},
    source: "https://aws.amazon.com/bedrock/pricing/",
    verified: false,
    notes: "Official page could not be extracted; figures from secondary summaries.",
  },
  {
    id: "nova-pro",
    name: "Amazon Nova Pro",
    provider: "Amazon",
    inputPerMTokUsd: 0.8,
    outputPerMTokUsd: 3.2,
    leaderboards: {},
    source: "https://aws.amazon.com/bedrock/pricing/",
    verified: false,
    notes: "Official page could not be extracted; figures from secondary summaries.",
  },
];

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  // ── Claude (Anthropic) — official multipliers: Max 5x = 5× Pro, Max 20x = 20× Pro
  {
    id: "claude-pro",
    provider: "Anthropic",
    name: "Claude Pro",
    family: "Claude Code",
    priceMonthlyUsd: 20,
    publishedPrices: { EUR: 22, GBP: 20 },
    tokensPerMonthM: 10,
    tokensEstimated: true,
    models: ["Claude Opus 4.8", "Claude Sonnet 5", "Claude Haiku 4.5"],
    source: "https://claude.com/pricing",
    notes:
      "Anthropic publishes no token quotas — usage is 5-hour windows + weekly caps. " +
      "Estimate: community per-window figures × official weekly hour caps ≈ 6–13M tokens/mo; midpoint used. " +
      "EUR/GBP are observed VAT-inclusive prices.",
  },
  {
    id: "claude-max-5x",
    provider: "Anthropic",
    name: "Claude Max 5x",
    family: "Claude Code",
    priceMonthlyUsd: 100,
    tokensPerMonthM: 50,
    tokensEstimated: true,
    models: ["Claude Opus 4.8", "Claude Sonnet 5", "Claude Fable 5"],
    source: "https://support.claude.com/en/articles/11049741-what-is-the-max-plan",
    notes: "Official: 5× Pro usage. Estimate = 5× the Pro estimate. Local prices = USD + VAT.",
  },
  {
    id: "claude-max-20x",
    provider: "Anthropic",
    name: "Claude Max 20x",
    family: "Claude Code",
    priceMonthlyUsd: 200,
    tokensPerMonthM: 200,
    tokensEstimated: true,
    models: ["Claude Opus 4.8", "Claude Sonnet 5", "Claude Fable 5"],
    source: "https://support.claude.com/en/articles/11049741-what-is-the-max-plan",
    notes:
      "Official: 20× Pro usage. Estimate = 20× the Pro estimate. " +
      "This plan's allotment is the page's default token amount.",
  },
  // ── OpenAI (ChatGPT / Codex) — credit-metered since Apr 2026
  {
    id: "chatgpt-plus",
    provider: "OpenAI",
    name: "ChatGPT Plus",
    family: "ChatGPT / Codex",
    priceMonthlyUsd: 20,
    publishedPrices: { EUR: 23, GBP: 20 },
    tokensPerMonthM: 10,
    tokensEstimated: true,
    models: ["GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"],
    source: "https://learn.chatgpt.com/docs/pricing",
    notes:
      "Codex is credit-metered (1 credit ≈ $0.04). Estimate from typical credits/task and " +
      "window limits ≈ 5–15M mixed tokens/mo; midpoint used. EUR/GBP are observed VAT-inclusive prices.",
  },
  {
    id: "chatgpt-pro-5x",
    provider: "OpenAI",
    name: "ChatGPT Pro 5x",
    family: "ChatGPT / Codex",
    priceMonthlyUsd: 100,
    tokensPerMonthM: 50,
    tokensEstimated: true,
    models: ["GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"],
    source: "https://learn.chatgpt.com/docs/pricing",
    notes: "Official: ~5× Plus window limits. Estimate scaled accordingly.",
  },
  {
    id: "chatgpt-pro-20x",
    provider: "OpenAI",
    name: "ChatGPT Pro 20x",
    family: "ChatGPT / Codex",
    priceMonthlyUsd: 200,
    tokensPerMonthM: 200,
    tokensEstimated: true,
    models: ["GPT-5.6 Sol", "GPT-5.6 Terra", "GPT-5.6 Luna"],
    source: "https://learn.chatgpt.com/docs/pricing",
    notes: "Official: ~20× Plus window limits. Estimate scaled accordingly.",
  },
  // ── Google (Gemini) — request/compute-metered, no token figures published
  {
    id: "google-ai-pro",
    provider: "Google",
    name: "Google AI Pro",
    family: "Google AI",
    priceMonthlyUsd: 19.99,
    tokensPerMonthM: 90,
    tokensEstimated: true,
    models: ["Gemini 3.1 Pro Preview", "Gemini 3.5 Flash"],
    source: "https://geminicli.com/docs/resources/quota-and-pricing/",
    notes:
      "Google meters requests/compute, not tokens. Soft ceiling estimate: 1,500 Gemini CLI " +
      "requests/day × ~2k tokens ≈ 90M/mo — a theoretical maximum, not comparable 1:1 with Claude/OpenAI estimates.",
  },
  {
    id: "google-ai-ultra-5x",
    provider: "Google",
    name: "Google AI Ultra ($100)",
    family: "Google AI",
    priceMonthlyUsd: 99.99,
    tokensPerMonthM: 120,
    tokensEstimated: true,
    models: ["Gemini 3.1 Pro Preview", "Gemini 3.5 Flash"],
    source: "https://blog.google/products-and-platforms/products/google-one/google-ai-subscriptions/",
    notes: "~5× Pro app limits; CLI 2,000 requests/day → soft ceiling ≈ 120M/mo.",
  },
  {
    id: "google-ai-ultra-20x",
    provider: "Google",
    name: "Google AI Ultra ($200)",
    family: "Google AI",
    priceMonthlyUsd: 200,
    tokensPerMonthM: 240,
    tokensEstimated: true,
    models: ["Gemini 3.1 Pro Preview", "Gemini 3.5 Flash"],
    source: "https://blog.google/products-and-platforms/products/google-one/google-ai-subscriptions/",
    notes: "20× Pro app limits; includes 20TB storage + YouTube Premium. Rough 2× the $100-tier ceiling.",
  },
  // ── xAI (Grok) — no published usage quotas at all
  {
    id: "supergrok",
    provider: "xAI",
    name: "SuperGrok",
    family: "SuperGrok",
    priceMonthlyUsd: 30,
    tokensPerMonthM: 0,
    tokensEstimated: true,
    models: ["Grok 4.5", "Grok 4.20"],
    source: "https://x.ai/pricing",
    notes: "xAI publishes no message or token quotas; usage not quantifiable.",
  },
  {
    id: "supergrok-heavy",
    provider: "xAI",
    name: "SuperGrok Heavy",
    family: "SuperGrok",
    priceMonthlyUsd: 300,
    tokensPerMonthM: 0,
    tokensEstimated: true,
    models: ["Grok 4.5", "Grok 4.20"],
    source: "https://x.ai/pricing",
    notes: "xAI publishes no message or token quotas; usage not quantifiable.",
  },
  // ── GitHub Copilot — usage-based billing (GitHub AI Credits) since Jun 2026
  {
    id: "copilot-pro",
    provider: "GitHub",
    name: "Copilot Pro",
    family: "GitHub Copilot",
    priceMonthlyUsd: 10,
    tokensPerMonthM: 2.5,
    tokensEstimated: true,
    models: ["Claude Sonnet 5", "GPT-5.6 Terra", "Gemini 3.5 Flash"],
    source: "https://github.com/features/copilot/plans",
    notes:
      "$15 included AI credits/mo, burned at API token rates. Estimate ≈ 1–4M tokens at " +
      "Sonnet-class rates; midpoint used. Completions remain unmetered.",
  },
  {
    id: "copilot-pro-plus",
    provider: "GitHub",
    name: "Copilot Pro+",
    family: "GitHub Copilot",
    priceMonthlyUsd: 39,
    tokensPerMonthM: 12,
    tokensEstimated: true,
    models: ["Claude Sonnet 5", "GPT-5.6 Sol", "Gemini 3.1 Pro Preview"],
    source: "https://github.com/features/copilot/plans",
    notes: "$70 included AI credits/mo. Estimate ≈ 5–20M tokens; midpoint used.",
  },
  {
    id: "copilot-max",
    provider: "GitHub",
    name: "Copilot Max",
    family: "GitHub Copilot",
    priceMonthlyUsd: 100,
    tokensPerMonthM: 37,
    tokensEstimated: true,
    models: ["Claude Sonnet 5", "GPT-5.6 Sol", "Gemini 3.1 Pro Preview"],
    source: "https://github.com/features/copilot/plans",
    notes: "$200 included AI credits/mo. Estimate ≈ 15–60M tokens; midpoint used.",
  },
];
