"""
Screenshot proxy endpoint.

Proxies screenshot requests to the runner's local filesystem.
Screenshots are generated by the runner during verification steps and stored
in the .dev-logs/screenshots/ directory. The path stored in verification
results is relative (e.g., '.dev-logs/screenshots/filename.png'), so this
endpoint resolves it to an absolute path and serves the file.

Fallback: if the file isn't found locally, attempts to fetch from the runner
HTTP API at localhost:9876.
"""

import mimetypes
from pathlib import Path

import httpx
import structlog
from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, StreamingResponse

logger = structlog.get_logger(__name__)
router = APIRouter()

# The parent directory where .dev-logs lives (qontinui_parent/).
# This file is at: qontinui_parent/qontinui-web/backend/app/api/v1/endpoints/screenshots.py
# parents[0]=endpoints, [1]=v1, [2]=api, [3]=app, [4]=backend, [5]=qontinui-web, [6]=qontinui_parent
_THIS_FILE = Path(__file__).resolve()
_PARENT_DIR = _THIS_FILE.parents[6]


def _resolve_screenshot_path(relative_path: str) -> Path | None:
    """Resolve a screenshot path to an absolute filesystem path.

    The runner stores paths like '.dev-logs/screenshots/filename.png'
    relative to the parent project directory.  The frontend may strip the
    '.dev-logs/' prefix before sending, so we try multiple resolution strategies.
    """
    # Strip leading slashes/dots for safety
    clean_path = relative_path.lstrip("/").lstrip("\\")

    # Try resolving relative to the parent directory directly
    # Handles: '.dev-logs/screenshots/file.png' or 'screenshots/file.png'
    candidate = _PARENT_DIR / clean_path
    if candidate.is_file():
        return candidate

    # Try under .dev-logs/ prefix (handles stripped paths like 'screenshots/file.png')
    candidate = _PARENT_DIR / ".dev-logs" / clean_path
    if candidate.is_file():
        return candidate

    # Try just the filename in common screenshot directories
    filename = Path(clean_path).name
    for subdir in ["screenshots", "playwright-screenshots"]:
        candidate = _PARENT_DIR / ".dev-logs" / subdir / filename
        if candidate.is_file():
            return candidate

    return None


@router.get("/{path:path}", response_model=None)
async def get_screenshot(path: str) -> FileResponse | StreamingResponse:
    """Serve a screenshot file.

    Attempts to resolve the path locally first (from the .dev-logs directory),
    then falls back to proxying from the runner HTTP API.
    """
    # Security: prevent path traversal
    if ".." in path:
        raise HTTPException(status_code=400, detail="Invalid path")

    # Try local filesystem first
    local_path = _resolve_screenshot_path(path)
    if local_path is not None:
        # Ensure the resolved path is still within the parent directory
        try:
            local_path.resolve().relative_to(_PARENT_DIR.resolve())
        except ValueError:
            raise HTTPException(status_code=403, detail="Access denied")

        content_type = mimetypes.guess_type(str(local_path))[0] or "image/png"
        return FileResponse(
            path=str(local_path),
            media_type=content_type,
        )

    # Fallback: proxy from runner
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(f"http://localhost:9876/screenshots/{path}")
            if response.status_code != 200:
                raise HTTPException(
                    status_code=response.status_code,
                    detail="Screenshot not found",
                )

            content_type = response.headers.get("content-type", "image/png")
            return StreamingResponse(
                iter([response.content]),
                media_type=content_type,
            )
    except httpx.ConnectError:
        logger.debug("screenshot_not_found", path=path)
        raise HTTPException(
            status_code=404,
            detail=f"Screenshot not found: {path}",
        )
    except httpx.TimeoutException:
        raise HTTPException(
            status_code=504,
            detail="Timeout fetching screenshot from runner",
        )
