/**
 * The frozen `data-testid` contract for `/admin/coord/questions`, as it
 * actually reaches the DOM.
 *
 * Added by plan `2026-08-16-coord-console-ui-unification-pipeline-style.md`
 * Phase 3 Wave 1. `tests/e2e/pages/admin-coord-questions.spec.ts` asserts
 * `coord-questions-page`, `coord-questions-tab-pending`,
 * `coord-questions-tab-answered` and `coord-questions-pending-count`, and this
 * migration replaced the elements all four used to sit on:
 *
 *   - the two tab testids are now GENERATED by `<FilterTabs>` from
 *     `testIdPrefix` + the tab id, so no grep of this route's source can prove
 *     they still exist — only a render can;
 *   - `coord-questions-pending-count` moved from a `<CardTitle>` badge onto the
 *     health strip's pending badge.
 *
 * A Playwright suite that reds two hours into CI is a worse way to learn a
 * testid was dropped than a unit test that reds in two seconds, which is why
 * this file exists at all.
 */

import { describe, expect, it, vi, beforeEach } from "vitest";
import { render, screen, waitFor } from "@testing-library/react";

const get = vi.fn();

vi.mock("@/services/service-factory", () => ({
  httpClient: {
    get: (...args: unknown[]) => get(...args),
    post: vi.fn(),
  },
}));

import CoordQuestionsPage from "./page";

const PENDING = [
  {
    question_id: "00000000-0000-0000-0000-deadbeef0001",
    agent_id: "01a01de1-9d08-7c31-a055-271ad6df6217",
    question: "Bump or pin the dependency?",
    created_at: "2026-08-20T09:00:00Z",
  },
];

beforeEach(() => {
  get.mockReset();
  get.mockImplementation(async (url: string) => {
    if (url.includes("gap=true")) return { questions: [] };
    if (url.includes("/pending")) return { questions: PENDING };
    return { questions: [] };
  });
});

describe("/admin/coord/questions frozen testids (D4a)", () => {
  it("emits every testid the Playwright suite asserts", async () => {
    render(<CoordQuestionsPage />);

    expect(screen.getByTestId("coord-questions-page")).toBeInTheDocument();

    await waitFor(() => {
      expect(
        screen.getByTestId("coord-questions-pending-count")
      ).toBeInTheDocument();
    });

    // Generated by <FilterTabs> from testIdPrefix — the strings that matter.
    expect(screen.getByTestId("coord-questions-tab-pending")).toBeInTheDocument();
    expect(
      screen.getByTestId("coord-questions-tab-answered")
    ).toBeInTheDocument();
    expect(screen.getByTestId("coord-questions-tab-gaps")).toBeInTheDocument();

    expect(screen.getByTestId("coord-questions-tabs")).toBeInTheDocument();
    expect(screen.getByTestId("coord-questions-refresh")).toBeInTheDocument();
    expect(
      screen.getByTestId("coord-questions-pending-list")
    ).toBeInTheDocument();
  });

  it("counts the pending inbox rather than claiming zero before it arrives", async () => {
    render(<CoordQuestionsPage />);
    // First paint: the fetch is in flight, so the badge reads the dash.
    expect(screen.getByTestId("coord-questions-pending-count")).toHaveTextContent(
      "–"
    );
    await waitFor(() => {
      expect(
        screen.getByTestId("coord-questions-pending-count")
      ).toHaveTextContent("1 pending");
    });
    expect(screen.getByTestId("coord-question-card")).toBeInTheDocument();
  });
});
