// AUTO-GENERATED by scripts/generate-spec-registry.ts — DO NOT EDIT
//
// 14 spec files discovered.
//
// Regenerate: npx tsx scripts/generate-spec-registry.ts

import type { DiscoveredSpec } from "./spec-prompt-builder";

import activeRunsSpec from "@/app/(app)/runs/active/active-runs.spec.uibridge.json";
import aiSettingsSpec from "@/app/(app)/settings/ai/ai-settings.spec.uibridge.json";
import chatSpec from "@/app/(app)/chat/chat.spec.uibridge.json";
import contextsSpec from "@/app/(app)/build/contexts/contexts.spec.uibridge.json";
import errorMonitorSpec from "@/app/(app)/tools/error-monitor/error-monitor.spec.uibridge.json";
import executeSpec from "@/app/(app)/execute/execute.spec.uibridge.json";
import findingsSpec from "@/app/(app)/runs/findings/findings.spec.uibridge.json";
import inspectorSpec from "@/app/(app)/tools/inspector/inspector.spec.uibridge.json";
import runnersSpec from "@/app/(app)/runners/runners.spec.uibridge.json";
import runsSpec from "@/app/(app)/runs/runs.spec.uibridge.json";
import statisticsSpec from "@/app/(app)/runs/statistics/statistics.spec.uibridge.json";
import templatesSpec from "@/app/(app)/build/templates/templates.spec.uibridge.json";
import uiBridgeStatesSpec from "@/app/(app)/automation-builder/ui-bridge-states/ui-bridge-states.spec.uibridge.json";
import workflowsSpec from "@/app/(app)/build/workflows/workflows.spec.uibridge.json";

interface RawSpec {
  specId: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  json: any;
}

const ALL_SPECS: RawSpec[] = [
  { specId: "active-runs", json: activeRunsSpec },
  { specId: "ai-settings", json: aiSettingsSpec },
  { specId: "chat", json: chatSpec },
  { specId: "contexts", json: contextsSpec },
  { specId: "error-monitor", json: errorMonitorSpec },
  { specId: "execute", json: executeSpec },
  { specId: "findings", json: findingsSpec },
  { specId: "inspector", json: inspectorSpec },
  { specId: "runners", json: runnersSpec },
  { specId: "runs", json: runsSpec },
  { specId: "statistics", json: statisticsSpec },
  { specId: "templates", json: templatesSpec },
  { specId: "ui-bridge-states", json: uiBridgeStatesSpec },
  { specId: "workflows", json: workflowsSpec },
];

/**
 * Get all page specs as DiscoveredSpec[].
 * Returns all groups from all spec files — no category filtering.
 */
export function getAllSpecs(): DiscoveredSpec[] {
  const result: DiscoveredSpec[] = [];

  for (const { specId, json } of ALL_SPECS) {
    const groups = json.groups ?? [];
    if (groups.length === 0) continue;

    result.push({
      specId,
      config: {
        version: json.version ?? "1.0.0",
        description: json.description ?? "",
        groups,
        metadata: json.metadata,
      },
    });
  }

  return result;
}
